import Link from "@/components/AppLink";
import EnglishPageShell from "@/components/english/EnglishPageShell";
import { buildEnglishMetadata } from "@/lib/englishSeo";

export const metadata = buildEnglishMetadata({ title: "About Moneysalary", description: "Who runs Moneysalary, how salary calculations and company estimates are prepared, and how sources and corrections are handled.", path: "/en/about" });

export default function EnglishAboutPage() {
  return <EnglishPageShell title="Understand your pay and the assumptions behind it" eyebrow="About Moneysalary" description="Moneysalary is a free site for exploring take-home salary, taxes and company compensation. It explains calculation assumptions, sources and limitations so that employees can compare and understand their income." breadcrumbs={[{ name: "About", href: "/en/about" }]}>
    <div className="max-w-3xl space-y-6">
      <section className="rounded-2xl border border-border bg-background p-5 sm:p-7"><h2 className="text-xl font-bold">Who runs the site?</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Moneysalary is operated by one working professional and funded through advertising. It began with the operator’s own need to compare changing salary-tax and social-insurance calculations, and is shared for others with similar questions.</p><p className="mt-3 text-sm leading-7 text-muted-foreground">The site is independently operated without professional advice from a tax accountant, labor consultant or financial institution. Tax and insurance information is checked against primary materials from the Korean National Tax Service and relevant insurance agencies. Company salaries and forward-looking scenarios include estimates. Check official sources and qualified advice for actual tax or financial decisions.</p></section>
      <section className="rounded-2xl border border-border bg-background p-5 sm:p-7"><h2 className="text-xl font-bold">Operating principles</h2><ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-7 text-muted-foreground"><li>Explain the applicable year, rates and deduction assumptions. Distinguish announcements and proposals from rules already in force.</li><li>Distinguish official rates, a company’s reported average compensation, the site’s own estimates and assumptions entered by a user.</li><li>Keep collection limited. Calculations generally run in the browser. Sending a private message stores its content and an optional reply email on the server. Sharing, advertising and analytics are explained in the privacy policy.</li></ul></section>
      <section className="rounded-2xl border border-border bg-background p-5 sm:p-7"><h2 className="text-xl font-bold">Sources and calculation methods</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Main references include the National Tax Service, National Pension Service, National Health Insurance Service and Korea Workers’ Compensation &amp; Welfare Service. Check the source and applicable date on each tool or guide. A reference to an official withholding table does not mean that every estimate reproduces that table: the English salary tool uses the simplified regular-employee model described in its method notes.</p><Link href="/en/help" className="mt-4 inline-flex min-h-11 items-center font-semibold text-primary underline">Read model assumptions and official source links</Link></section>
      <section className="rounded-2xl border border-border bg-background p-5 sm:p-7"><h2 className="text-xl font-bold">How company salary estimates are prepared</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">Company salaries and rankings are the site’s own estimates compiled from public job advertisements, average employee compensation in business or audit reports, media reports and public community reviews. They are not figures officially announced or confirmed by the companies.</p><p className="mt-3 text-sm leading-7 text-muted-foreground">The data provides general context for job seekers and employees. It does not guarantee an actual offer or rank a company’s overall quality. Grade, experience, performance and negotiation can substantially change actual pay. Correction requests are reviewed against supporting evidence; the site does not intentionally retain incorrect information or seek to damage reputations.</p><Link href="/en/salary-db" className="mt-4 inline-flex min-h-11 items-center font-semibold text-primary underline">Company pay research in English</Link></section>
      <section className="rounded-2xl border border-border bg-background p-5 sm:p-7"><h2 className="text-xl font-bold">How information is checked and corrected</h2><ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-7 text-muted-foreground"><li>Check legislation and agency announcements first, and distinguish publication dates, application deadlines and effective dates.</li><li>State whether amounts are gross or net, annual or monthly, and explain assumptions that affect the result. An estimate is not presented as a confirmed payment.</li><li>Preserve guide publication dates. Show a separate modification date when the text, calculation assumptions or sources materially change, rather than changing dates alone.</li><li>Review error reports against evidence and consider appropriate corrections or removal. The site does not operate public comments.</li></ul></section>
      <section className="rounded-2xl border border-border bg-background p-5 sm:p-7"><h2 className="text-xl font-bold">Limits and correction requests</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">All results are general reference estimates. Actual taxes can differ with deductions, credits, household eligibility and employer-specific exempt pay. Use National Tax Service resources or professional advice for tax decisions. If a formula, rate or company figure is wrong, send a private report identifying the source and issue. Reasonable correction and removal requests are reviewed.</p><Link href="/en/contact?source=about&type=data_correction" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-electric px-5 py-3 font-semibold text-white">Request a correction privately</Link></section>
      <p className="text-sm text-muted-foreground">This explanation updated <time dateTime="2026-09-09">September 9, 2026</time>.</p><nav aria-label="About resources" className="flex flex-wrap gap-4"><Link href="/en/privacy" className="inline-flex min-h-11 items-center text-primary underline">Privacy policy</Link><Link href="/en/terms" className="inline-flex min-h-11 items-center text-primary underline">Terms of use</Link></nav>
    </div>
  </EnglishPageShell>;
}
