// AUTO-GENERATED by scripts/gen-season-key.ts — 직접 수정 금지.
// 빌드 시점(KST) 시즌 세트 키. npm run build(prebuild) 가 매번 오늘 키로 재생성하고,
// verify:site 의 --check 는 커밋된 값이 오늘 키와 다르면 WARNING(만료 알람, 비차단)을 낸다.
// 수동 전환(1/2 JAN·긴급)은 src/lib/seasonKey.ts 의 SEASON_KEY_OVERRIDE 한 줄 → 재생성 → 커밋.
// 소비자: src/config/seasonLinks.ts · src/app/table/2026/SeasonalLinks.tsx · src/components/header/HeaderSearch.tsx
import type { SeasonKey } from "@/lib/seasonKey";

export const SEASON_KEY: SeasonKey = "SEP";
