// AUTO-GENERATED by scripts/gen-site-metrics.ts — 직접 수정 금지.
// 수치가 바뀌면 npm run build(prebuild) 또는 tsx scripts/gen-site-metrics.ts 로 재생성.

/** 회사 DB 수 — allCompanies.length (dedupe 후, 글로벌 포함) */
export const COMPANY_COUNT = 430;
/** 회사별 성과급 계산기 수 — BONUS_CALCS.length */
export const BONUS_CALC_COUNT = 23;
/** 직업별 연봉 프로필 수 — jobsData.length */
export const JOB_COUNT = 62;
/** 산업군 수 — industriesData.length */
export const INDUSTRY_COUNT = 27;
/** 지역 수 — regionsData.length (17개 시도 + 판교·여의도) */
export const REGION_COUNT = 19;
/** 한국어 가이드 편수 — koGuides.length */
export const GUIDE_COUNT = 329;
/** /calc/[slug] 퀵 계산기 수 — allCalculators.length */
export const SIMPLE_CALC_COUNT = 101;
/** /tools 리프 도구 수 — page.tsx 파일 수(인덱스 제외) */
export const TOOL_COUNT = 29;
