// scripts/gen-site-metrics.ts
//
// 사이트 지표 코드젠 — src/config/site-metrics.generated.ts 를 실데이터 length 로 생성.
//
// 왜 코드젠인가: Header/Footer 등 "use client" 컴포넌트가 allCompanies(~860KB)를
// 직접 import 하면 회사 DB 전체가 클라이언트 번들에 실린다. 빌드 머신에서 length 만
// 뽑아 상수 모듈로 떨어뜨리면 번들 비용 0 으로 전 표면이 같은 수치를 공유한다.
// (선례: scripts/verify-sitemap.ts 의 tsx 실행, taxConstants2026 단일 소스 패턴)
//
// 실행: tsx scripts/gen-site-metrics.ts          → 파일 생성/갱신 (npm prebuild 로 자동)
//       tsx scripts/gen-site-metrics.ts --check  → 드리프트·클라 import 오염 검사만 (exit 1)
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

import { allCompanies } from "../src/data/companies/index";
import { BONUS_CALCS } from "../src/data/bonusCalcHub";
import { jobsData } from "../src/data/jobsData";
import { industriesData } from "../src/data/industriesData";
import { regionsData } from "../src/data/regionsData";
import { koGuides } from "../src/lib/guidesData";
import { allCalculators } from "../src/lib/simpleCalculators/index";

const ROOT = join(__dirname, "..");
const OUT_PATH = join(ROOT, "src/config/site-metrics.generated.ts");

/** /tools 리프 계산기 수 — page.tsx 보유 디렉터리 중 인덱스 페이지(/tools, /tools/math) 제외 */
function countToolLeaves(): number {
  const toolsRoot = join(ROOT, "src/app/tools");
  const indexPages = new Set([join(toolsRoot, "page.tsx"), join(toolsRoot, "math/page.tsx")]);
  let count = 0;
  const walk = (dir: string) => {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      if (statSync(full).isDirectory()) walk(full);
      else if (entry === "page.tsx" && !indexPages.has(full)) count += 1;
    }
  };
  walk(toolsRoot);
  return count;
}

function buildOutput(): string {
  const metrics: Record<string, { value: number; comment: string }> = {
    COMPANY_COUNT: {
      value: allCompanies.length,
      comment: "회사 DB 수 — allCompanies.length (dedupe 후, 글로벌 포함)",
    },
    BONUS_CALC_COUNT: {
      value: BONUS_CALCS.length,
      comment: "회사별 성과급 계산기 수 — BONUS_CALCS.length",
    },
    JOB_COUNT: { value: jobsData.length, comment: "직업별 연봉 프로필 수 — jobsData.length" },
    INDUSTRY_COUNT: {
      value: industriesData.length,
      comment: "산업군 수 — industriesData.length",
    },
    REGION_COUNT: {
      value: regionsData.length,
      comment: "지역 수 — regionsData.length (17개 시도 + 판교·여의도)",
    },
    GUIDE_COUNT: { value: koGuides.length, comment: "한국어 가이드 편수 — koGuides.length" },
    SIMPLE_CALC_COUNT: {
      value: allCalculators.length,
      comment: "/calc/[slug] 퀵 계산기 수 — allCalculators.length",
    },
    TOOL_COUNT: {
      value: countToolLeaves(),
      comment: "/tools 리프 도구 수 — page.tsx 파일 수(인덱스 제외)",
    },
  };

  const lines = Object.entries(metrics).map(
    ([name, { value, comment }]) => `/** ${comment} */\nexport const ${name} = ${value};`,
  );

  return [
    "// AUTO-GENERATED by scripts/gen-site-metrics.ts — 직접 수정 금지.",
    "// 수치가 바뀌면 npm run build(prebuild) 또는 tsx scripts/gen-site-metrics.ts 로 재생성.",
    "",
    ...lines,
    "",
  ].join("\n");
}

/**
 * 클라이언트 칩입 가드 — "use client" 내비/푸터 계열 컴포넌트가 회사 데이터 배열을
 * 직접 import 하면 클라 번들이 비대해진다. site-metrics 우회를 강제.
 */
function checkClientImports(): string[] {
  const guarded = [
    "src/components/Header.tsx",
    "src/components/Footer.tsx",
    "src/components/header",
    "src/components/home",
  ];
  const offenders: string[] = [];
  const scan = (fileOrDir: string) => {
    const full = join(ROOT, fileOrDir);
    if (statSync(full).isDirectory()) {
      for (const entry of readdirSync(full)) scan(join(fileOrDir, entry));
      return;
    }
    if (!/\.(ts|tsx)$/.test(fileOrDir)) return;
    const src = readFileSync(full, "utf8");
    if (/from\s+["'][^"']*data\/companies/.test(src) || /from\s+["']@\/data\/seedCompanies/.test(src)) {
      offenders.push(fileOrDir);
    }
  };
  guarded.forEach(scan);
  return offenders;
}

const isCheck = process.argv.includes("--check");
const next = buildOutput();

const offenders = checkClientImports();
if (offenders.length > 0) {
  console.error("[gen-site-metrics] 클라 컴포넌트가 회사 데이터 배열을 직접 import:");
  offenders.forEach((f) => console.error(`  - ${f}`));
  console.error("  → src/config/site-metrics.generated.ts 상수를 대신 사용하세요.");
  process.exit(1);
}

let current = "";
try {
  current = readFileSync(OUT_PATH, "utf8");
} catch {
  /* 최초 생성 */
}

if (isCheck) {
  if (current !== next) {
    console.error("[gen-site-metrics] 드리프트 감지 — 데이터 수와 생성 상수 불일치.");
    console.error("  → tsx scripts/gen-site-metrics.ts 로 재생성 후 커밋하세요.");
    process.exit(1);
  }
  console.log("[gen-site-metrics] OK — 드리프트 0건, 클라 import 오염 0건");
} else {
  if (current === next) {
    console.log("[gen-site-metrics] 변경 없음");
  } else {
    writeFileSync(OUT_PATH, next);
    console.log(`[gen-site-metrics] 생성 완료 → ${OUT_PATH}`);
  }
}
