// scripts/gen-season-key.ts
//
// 시즌 키 코드젠 — src/config/seasonKey.generated.ts 에 빌드 시점(KST) 시즌 키를 상수로 떨어뜨린다.
// S1-1 (2026-09-11). 선례: gen-site-metrics.ts / gen-salary-amounts.ts (prebuild + --check 게이트).
//
// 왜 코드젠인가: HeaderSearch 등 "use client" 컴포넌트가 서버와 같은 세트를 렌더해야 하므로
// 모듈 스코프 `new Date()` 를 쓸 수 없다(마지막 빌드 이후 경계를 넘은 방문에서 hydration 불일치).
// 빌드 상수로 박으면 서버·클라가 항상 같은 세트를 보고, 경계일 이후 첫 배포에 자동 반영된다.
//
// 실행: tsx scripts/gen-season-key.ts          → 오늘 키로 파일 생성/갱신 (npm prebuild 로 자동)
//       tsx scripts/gen-season-key.ts --check  → 커밋된 값 ≠ 오늘 키면 WARNING (exit 0, 비차단 알람)
//         · 커밋값 만료 = 로컬·테스트가 구 세트를 본다 → 재생성 후 커밋·배포(CF 캐시 퍼지는 운영자)
//         · 1/2 이후 오버라이드 비어 있음 → JAN 수동 전환 대기 알림
//         · 다음 경계 D-7 이내 → 임박 알림
//       env SEASON_KEY_NOW=2026-09-26T00:00:00+09:00 으로 '오늘'을 고정할 수 있다(검증용).
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import {
  SEASON_KEY_OVERRIDE,
  daysToNextBoundary,
  isJanManualWindow,
  isSeasonKeyExpired,
  pickSeasonKey,
  resolveSeasonKey,
  type SeasonKey,
} from "../src/lib/seasonKey";

const ROOT = join(__dirname, "..");
const OUT_PATH = join(ROOT, "src/config/seasonKey.generated.ts");
const TAG = "[gen-season-key]";
const KEY_RE = /export const SEASON_KEY: SeasonKey = "(SEP|OCT|DEC|JAN)";/;

const nowEnv = process.env.SEASON_KEY_NOW;
const now = nowEnv ? new Date(nowEnv) : new Date();
if (Number.isNaN(now.getTime())) {
  console.error(`${TAG} SEASON_KEY_NOW 파싱 실패: ${nowEnv}`);
  process.exit(1);
}
const key: SeasonKey = resolveSeasonKey(now);

function buildOutput(k: SeasonKey): string {
  return [
    "// AUTO-GENERATED by scripts/gen-season-key.ts — 직접 수정 금지.",
    "// 빌드 시점(KST) 시즌 세트 키. npm run build(prebuild) 가 매번 오늘 키로 재생성하고,",
    "// verify:site 의 --check 는 커밋된 값이 오늘 키와 다르면 WARNING(만료 알람, 비차단)을 낸다.",
    "// 수동 전환(1/2 JAN·긴급)은 src/lib/seasonKey.ts 의 SEASON_KEY_OVERRIDE 한 줄 → 재생성 → 커밋.",
    "// 소비자: src/config/seasonLinks.ts · src/app/table/2026/SeasonalLinks.tsx · src/components/header/HeaderSearch.tsx",
    'import type { SeasonKey } from "@/lib/seasonKey";',
    "",
    `export const SEASON_KEY: SeasonKey = "${k}";`,
    "",
  ].join("\n");
}

function readCommittedKey(): SeasonKey | null {
  try {
    const m = readFileSync(OUT_PATH, "utf8").match(KEY_RE);
    return (m?.[1] as SeasonKey | undefined) ?? null;
  } catch {
    return null;
  }
}

const isCheck = process.argv.includes("--check");
const next = buildOutput(key);

if (isCheck) {
  const committed = readCommittedKey();
  const warnings: string[] = [];
  if (committed === null) {
    warnings.push(`${OUT_PATH} 없음/형식 불일치 → tsx scripts/gen-season-key.ts 로 생성 후 커밋`);
  } else if (committed !== key) {
    warnings.push(
      `시즌 세트 만료 — 커밋값 ${committed} ≠ 오늘 키 ${key}. ` +
        `tsx scripts/gen-season-key.ts 로 재생성 후 커밋·배포(배포 후 CF 캐시 퍼지는 운영자). ` +
        `※ 프로덕션 빌드(prebuild)는 이미 ${key} 로 나가지만 로컬·테스트는 구 세트를 본다.`,
    );
  }
  if (SEASON_KEY_OVERRIDE === null && isJanManualWindow(now)) {
    warnings.push(
      `JAN 수동 전환 대기 — 1/2 이후인데 SEASON_KEY_OVERRIDE 가 비어 있음(자동 키 ${pickSeasonKey(now)} 유지 중). ` +
        `확인 2건(공무원 2027 봉급표 확정 여부·간소화 오픈일) 후 src/lib/seasonKey.ts 의 ` +
        `SEASON_KEY_OVERRIDE 를 "JAN" 으로 → tsx scripts/gen-season-key.ts → 커밋.`,
    );
  }
  if (isSeasonKeyExpired(key, now)) {
    warnings.push(
      `시즌 세트 만료 — ${key} 세트의 유효기간이 지났음(src/lib/seasonKey.ts SEASON_EXPIRES_KST). ` +
        `다음 세트를 정의하거나 SEASON_KEY_OVERRIDE 를 바꿀 것 — 그때까지 프로덕션은 만료 세트를 계속 노출한다.`,
    );
  }
  const nextB = SEASON_KEY_OVERRIDE === null ? daysToNextBoundary(now) : null;
  if (nextB && nextB.days <= 7) {
    const [y, m, d] = nextB.fromKst;
    const ymd = `${y}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
    warnings.push(
      `D-${nextB.days}: ${ymd}(KST) 에 ${key} → ${nextB.key} 자동 전환 — 당일 이후 첫 배포에 반영, ` +
        `배포 후 CF 캐시 퍼지 + 헬스체크로 확인.`,
    );
  }
  if (SEASON_KEY_OVERRIDE !== null) {
    console.log(
      `${TAG} 오버라이드 활성: SEASON_KEY_OVERRIDE = ${SEASON_KEY_OVERRIDE} (자동 키였다면 ${pickSeasonKey(now)})`,
    );
  }
  if (warnings.length) {
    for (const w of warnings) console.warn(`${TAG} WARNING: ${w}`);
    console.warn(`${TAG} (비차단 — exit 0)`);
  } else {
    console.log(`${TAG} OK — 커밋값 ${committed} == 오늘 키 ${key}`);
  }
  process.exit(0);
}

let current = "";
try {
  current = readFileSync(OUT_PATH, "utf8");
} catch {
  /* 최초 생성 */
}
// CRLF 체크아웃(core.autocrlf)에서도 키가 같으면 다시 쓰지 않는다 — 불필요한 diff 방지
if (current === next || current.match(KEY_RE)?.[1] === key) {
  console.log(`${TAG} 변경 없음 (SEASON_KEY = ${key})`);
} else {
  writeFileSync(OUT_PATH, next);
  console.log(`${TAG} 생성 완료 → ${OUT_PATH} (SEASON_KEY = ${key})`);
}
