// scripts/gen-guides-meta.ts
//
// 가이드 카드 메타 추출 — 본문 포함 정본(src/lib/guidesContent.ts)에서 content 를
// 떼어낸 카드 배열을 src/lib/guidesMeta.generated.ts 로 생성한다.
// prebuild 에서 항상 실행되므로 정본 수정 후 재생성을 잊어도 빌드가 치유한다
// (site-metrics.generated.ts 와 동일한 패턴).
//
// 실행: tsx scripts/gen-guides-meta.ts

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { guides } from "../src/lib/guidesContent";
import type { GuideCardMeta } from "../src/lib/guidesData";

const OUT_PATH = join(__dirname, "../src/lib/guidesMeta.generated.ts");

const cards: GuideCardMeta[] = guides.map(({ content, ...rest }) => ({
  ...rest,
  contentChars: content.length,
}));

const banner = [
  "// AUTO-GENERATED by scripts/gen-guides-meta.ts — DO NOT EDIT BY HAND.",
  "// 정본: src/lib/guidesContent.ts (본문 포함). 이 파일은 카드 메타만 담아",
  "// 목록·홈·검색 청크가 본문 ~1.5MB 를 끌고 가지 않게 한다.",
  "// prebuild 마다 재생성 — 정본 수정 시 커밋 전 tsx scripts/gen-guides-meta.ts 실행.",
  'import type { GuideCardMeta } from "./guidesData";',
  "",
  "export const guideCards: GuideCardMeta[] = ",
].join("\n");

const next = `${banner}${JSON.stringify(cards, null, 1)};\n`;
// CRLF 체크아웃(core.autocrlf)에서 내용이 같으면 다시 쓰지 않는다 — prebuild 마다 줄바꿈만 다른
// 더티 트리가 생기던 것 방지(2026-09-12, gen-salary-amounts·gen-site-metrics 와 동일).
let current = "";
try {
  current = readFileSync(OUT_PATH, "utf8");
} catch {
  /* 최초 생성 */
}
const eol = (s: string) => s.replace(/\r\n/g, "\n");
if (eol(current) === eol(next)) {
  console.log(`[gen-guides-meta] 변경 없음 — 카드 메타 ${cards.length}편 (${OUT_PATH})`);
} else {
  writeFileSync(OUT_PATH, next, "utf8");
  console.log(`[gen-guides-meta] OK — 카드 메타 ${cards.length}편 생성 (${OUT_PATH})`);
}
