import type { CalculatorDef, CalculatorField, CalculatorResult } from "./types";

// Monthly, end-of-period cash-flow models. Defaults are examples, not statutory rates or product quotes.
const won = (name: string, label: string, value: number): CalculatorField => ({ name, label, defaultValue: value, suffix: "원", min: 0, max: 1e12, step: 1000, hint: "실제 금액 또는 비교할 가정값을 원 단위로 입력하세요." });
const num = (name: string, label: string, value: number, suffix: string, min = 0, max = 600, step = 1): CalculatorField => ({ name, label, defaultValue: value, suffix, min, max, step, hint: `${min}~${max}${suffix} 범위의 가정값입니다.` });
const rate = (name = "rate", label = "가정 연이율", value = 4) => num(name, label, value, "%", 0, 50, 0.1);
const months = (name = "months", label = "기간", value = 36) => num(name, label, value, "개월", 1, 600);
const pct = (name: string, label: string, value: number) => num(name, label, value, "%", 0, 100, 0.1);
const R = (label: string, value: number, suffix = "원") => {
  const precision = suffix === "원" || suffix === "개월" ? 1 : 100;
  const rounded = Math.round(value * precision) / precision;
  return { label, value: rounded === 0 ? 0 : rounded, suffix };
};
const result = (label: string, value: number, secondary: NonNullable<CalculatorResult["secondary"]> = [], note?: string, suffix = "원"): CalculatorResult => ({ primary: R(label, value, suffix), secondary, note });
const invalid = (note: string): CalculatorResult => ({ ...result("입력 조건 확인", 0, [], note), status: "invalid" });
const monthly = (annual: number) => annual / 1200;
const payment = (p: number, r: number, n: number) => r === 0 ? p / n : p * r / -Math.expm1(-n * Math.log1p(r));
const growth = (r: number, n: number) => Math.exp(n * Math.log1p(r));
const factor = (r: number, n: number) => r === 0 ? n : Math.expm1(n * Math.log1p(r)) / r;
const fv = (p: number, m: number, r: number, n: number) => p * growth(r, n) + m * factor(r, n);
const needMonthly = (goal: number, p: number, r: number, n: number) => Math.max(0, (goal - p * growth(r, n)) / factor(r, n));

function payoff(p: number, r: number, pay: number, limit = 600) {
  let balance = p, interest = 0, paid = 0, count = 0;
  while (balance > 0.005 && count < limit) {
    const charge = balance * r;
    if (pay <= charge) return { months: count, interest, paid, balance, finished: false };
    const actual = Math.min(pay, balance + charge);
    balance = Math.max(0, balance + charge - actual);
    interest += charge; paid += actual; count++;
  }
  return { months: count, interest, paid, balance, finished: balance <= 0.005 };
}

const SOURCES = {
  loan: [{ title: "Microsoft: PMT의 원리금균등 상환·기간 단위", url: "https://support.microsoft.com/en-US/Excel/pmt-function" }],
  saving: [{ title: "SEC Investor.gov: 목표 저축의 월 적립액", url: "https://www.investor.gov/financial-tools-calculators/calculators/savings-goal-calculator" }],
  refinance: [{ title: "CFPB: 대환 비용과 월 절감액 비교", url: "https://files.consumerfinance.gov/f/documents/cfpb_should_i_refinance_handout.pdf" }],
  debt: [{ title: "CFPB: 고금리 우선·소액 채무 우선 상환", url: "https://www.consumerfinance.gov/archive/blog/how-reduce-your-debt/" }],
  wage: [{ title: "BLS: 소비자물가지수로 실질임금 계산", url: "https://www.bls.gov/opub/hom/ces/calculation.htm" }],
  portfolio: [{ title: "SEC Investor.gov: 자산 배분과 리밸런싱", url: "https://www.investor.gov/introduction-investing/getting-started/asset-allocation" }],
  fee: [{ title: "SEC Investor.gov: 투자 수수료와 비용", url: "https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/updated" }],
};
type Spec = Omit<CalculatorDef, "description" | "explanation" | "faqs" | "categoryLabel" | "keywords"> & {
  intro: string; detail: string; questions: [string, string][]; source?: keyof typeof SOURCES;
  /** S3-1(2026-09-12): caveats 가 계산기별로 완결되어 있으면 true — 공통 예시 문장을 덧붙이지 않는다. 기본값 false(종전 동작). */
  individualCaveats?: boolean;
};
export const expandedFinanceSources: Record<string, { title: string; url: string }[]> = {};
const labels: Partial<Record<CalculatorDef["category"], string>> = { loan: "대출", salary: "연봉·급여", career: "커리어", investment: "저축·투자", family: "가족" };
function define(spec: Spec): CalculatorDef {
  const { intro, detail, questions, source, compute, individualCaveats, ...rest } = spec;
  if (source) expandedFinanceSources[spec.slug] = SOURCES[source];
  return {
    ...rest, categoryLabel: labels[spec.category] ?? "금융", keywords: [spec.title, "조건 비교", "무료 계산기"],
    publishedAt: "2026-09-10", ...(source ? { sources: SOURCES[source] } : {}),
    description: `${intro} ${detail}`,
    explanation: `${intro}\n\n${detail}`,
    faqs: questions.map(([q, a]) => ({ q, a })),
    caveats: individualCaveats ? [...(spec.caveats ?? [])] : [...(spec.caveats ?? []), "초기 숫자는 계산 예시입니다. 계약서·견적서·실제 지출 내역으로 바꾸어 비교하세요."],
    compute: (inputs) => {
      for (const field of spec.fields) {
        const value = inputs[field.name];
        if (!Number.isFinite(value) || value < (field.min ?? 0) || value > (field.max ?? 1e12)) return invalid(`${field.label}은 ${field.min ?? 0}~${field.max ?? 1e12}${field.suffix ?? ""} 범위로 입력하세요.`);
        if (field.step === 1 && field.suffix !== "원" && !Number.isInteger(value)) return invalid(`${field.label}은 정수로 입력하세요.`);
      }
      const computed = compute(inputs);
      if ([computed.primary, ...(computed.secondary ?? [])].some((value) => !Number.isFinite(value.value) || Math.abs(value.value) > 1e18)) return invalid("계산 결과가 표시 범위를 넘었어요. 금액·이율·기간을 줄여 다시 비교하세요.");
      return computed;
    },
  };
}

const LOANS: CalculatorDef[] = [
  define({ slug: "refinance-break-even", title: "대환대출 비용 회수 기간", category: "loan", source: "refinance",
    intro: "대환대출을 실행할 때 한 번 내는 비용을 매달 줄어드는 상환액으로 회수하는 데 걸리는 기간을 계산합니다. 현재 대출과 새 대출의 실제 월 납입 견적을 비교하고, 예상 유지 기간 안에 초기 비용을 만회하는지 확인할 수 있습니다.",
    detail: "월 납입액 차이는 현금 흐름의 차이이며 순수 이자 절약과 같지는 않습니다. 대출 만기가 늘어나면 월 납입액이 줄어도 총이자가 늘 수 있으므로 남은 원금과 전체 상환 일정은 별도로 대조해야 합니다.",
    fields: [won("old", "현재 월 납입액", 1000000), won("next", "새 월 납입액", 900000), won("fee", "대환 초기 비용 합계", 1200000), months("hold", "새 대출 유지 예정 기간", 36)],
    compute: ({ old, next, fee, hold }) => old <= next ? invalid("새 월 납입액이 더 작아야 비용 회수 기간이 생깁니다.") : result("비용 회수까지", Math.ceil(fee / (old - next)), [R("월 납입 감소", old - next), R("유지 기간의 현금 절감", (old - next) * hold - fee)], "월 납입액 기준 단순 회수 기간입니다. 원금 감소 속도의 차이는 반영하지 않습니다.", "개월"),
    formula: "회수 개월 = 올림(초기 비용 ÷ (기존 월 납입액 − 새 월 납입액))",
    questions: [["초기 비용에는 무엇을 넣나요?", "실제 부담하는 중도상환 수수료, 새 대출 수수료 등 일회성 비용을 합산합니다."], ["절감액이 0이면 어떻게 되나요?", "매월 회수할 금액이 없으므로 회수 기간을 산출하지 않습니다."], ["회수 뒤에는 무조건 유리한가요?", "아닙니다. 만기 연장과 원금 잔액 차이, 총이자를 함께 확인해야 합니다."]], relatedSlugs: ["loan-refinance-savings", "loan-term-extension-cost"] }),
  define({ slug: "extra-payment-term", title: "매달 추가 상환의 기간 단축", category: "loan", source: "loan",
    intro: "매달 정해진 대출 상환액에 추가 금액을 더하면 완납 시점과 총이자가 어떻게 달라지는지 비교합니다. 월별 잔액에 이자를 붙이고 상환액을 차감하는 방식으로 계산해 마지막 달의 일부 납입도 반영합니다.",
    detail: "정기 납입액과 금리는 계산 기간 동안 고정되며 추가 상환은 매월 말 동시에 이루어진다고 가정합니다. 월 납입액이 당월 이자 이하이거나 600개월 안에 완납하지 못하면 기간 대신 조건 확인 안내를 표시합니다.",
    fields: [won("p", "현재 대출 잔액", 12000000), rate(), won("pay", "기존 월 상환액", 400000), won("extra", "매달 추가 상환액", 100000)],
    compute: ({ p, rate: a, pay, extra }) => { const base = payoff(p, monthly(a), pay), next = payoff(p, monthly(a), pay + extra); return !base.finished || !next.finished ? invalid("기존 또는 추가 상환 조건으로 600개월 안에 완납할 수 없어요. 월 상환액을 높여 주세요.") : result("단축되는 기간", base.months - next.months, [R("추가 상환 후 완납", next.months, "개월"), R("줄어드는 총이자", base.interest - next.interest)], "중도상환 수수료와 추가 상환 한도는 별도입니다.", "개월"); },
    formula: "매월 잔액 = 직전 잔액 × (1 + 연이율 ÷ 12) − 실제 납입액",
    questions: [["마지막 달도 전체 금액을 내나요?", "아니요. 마지막 달에는 남은 원금과 당월 이자만 납입합니다."], ["금리가 0이면요?", "이자 없이 원금을 월 납입액으로 나누어 완납 개월을 계산합니다."], ["기존 월 상환액이 이자보다 작으면요?", "원금이 줄지 않으므로 기간을 확정하지 않고 입력 조건을 안내합니다."]], relatedSlugs: ["lump-sum-prepayment-term", "loan-monthly-payment"] }),
  define({ slug: "lump-sum-prepayment-term", title: "목돈 중도상환의 완납 시점", category: "loan", source: "loan",
    intro: "지금 목돈을 대출 원금에 넣고 기존 월 상환액을 계속 유지했을 때 얼마나 빨리 갚는지 계산합니다. 한 번에 갚는 금액, 상환 수수료와 이후 이자 차이를 함께 보여 주어 목돈 사용 계획을 비교할 수 있습니다.",
    detail: "목돈 상환은 다음 이자가 발생하기 전에 이루어지는 것으로 가정합니다. 금융회사가 월 납입액을 낮추는 방식으로 재산정하면 이 도구의 기간 단축 결과와 다르므로 실제로 기간 단축 방식이 가능한지 확인해야 합니다.",
    fields: [won("p", "현재 잔액", 12000000), rate(), won("pay", "유지할 월 상환액", 400000), won("lump", "지금 상환할 목돈", 3000000), won("fee", "실제 상환 수수료", 0)],
    compute: ({ p, rate: a, pay, lump, fee }) => { if (lump > p) return invalid("목돈 상환액은 현재 잔액 이하로 입력하세요."); const base = payoff(p, monthly(a), pay), next = payoff(p - lump, monthly(a), pay); return !base.finished || !next.finished ? invalid("기존 또는 변경 조건에서 600개월 안에 완납되지 않습니다.") : result("목돈 상환 후 완납", next.months, [R("단축 기간", base.months - next.months, "개월"), R("수수료 차감 이자 절감", base.interest - next.interest - fee)], "월 납입액을 유지하는 기간 단축 방식입니다.", "개월"); },
    formula: "새 원금 = 기존 잔액 − 목돈; 순이자 절감 = 기존 총이자 − 새 총이자 − 수수료",
    questions: [["목돈이 잔액보다 많으면요?", "대출 잔액을 넘는 상환액은 허용하지 않습니다."], ["월 납입액이 줄어드는 방식도 같나요?", "아닙니다. 이 계산은 월 납입액을 유지하고 기간을 줄이는 경우입니다."], ["전액 상환하면 기간은요?", "다음 월 납입이 필요 없으므로 0개월로 표시합니다."]], relatedSlugs: ["extra-payment-term", "prepayment-fee-quick"] }),
  define({ slug: "loan-balance-after-payments", title: "납입 횟수별 대출 잔액", category: "loan", source: "loan",
    intro: "원리금균등 대출을 일정 횟수 납입한 직후 남는 원금과 지금까지 낸 이자를 계산합니다. 대출 실행 시점의 원금·금리·만기를 입력하고 원하는 납입 횟수를 지정해 중간 시점의 자금 계획을 확인하세요.",
    detail: "월 납입액은 고정 금리와 월말 상환 가정으로 계산하며 수수료와 지연 납입은 제외합니다. 계약서의 대출 잔액은 일별 이자와 원 단위 처리 때문에 차이가 날 수 있으며, 지정한 횟수는 전체 만기를 넘을 수 없습니다.",
    fields: [won("p", "최초 대출 원금", 12000000), rate(), months("months", "전체 만기", 36), num("paid", "이미 납입한 횟수", 12, "회", 0, 600)],
    compute: ({ p, rate: a, months: n, paid: k }) => { if (k > n) return invalid("납입 횟수는 전체 만기 개월 이하로 입력하세요."); const r = monthly(a), pay = payment(p, r, n), balance = Math.max(0, r === 0 ? pay * (n - k) : pay * -Math.expm1(-(n - k) * Math.log1p(r)) / r); return result("납입 직후 남은 원금", balance, [R("월 상환액", pay), R("지금까지 낸 이자", pay * k - (p - balance))]); },
    formula: "k회 후 잔액 = P(1+r)^k − 월상환액 × ((1+r)^k−1)/r; r=0이면 P−월상환액×k",
    questions: [["납입 횟수 0은 무엇인가요?", "첫 납입 전 상태로, 원금 전액이 남습니다."], ["만기까지 납입하면요?", "정상 납입 가정에서 잔액은 0원이 됩니다."], ["중도상환 내역도 반영하나요?", "이 계산은 추가 상환 없이 원리금균등으로 납입한 경우만 다룹니다."]], relatedSlugs: ["loan-interest-principal-split", "extra-payment-term"] }),
  define({ slug: "loan-interest-principal-split", title: "이번 달 원금·이자 분해", category: "loan", source: "loan",
    intro: "대출 잔액과 금리, 이번 달 납입 예정액을 입력해 이자와 원금 상환액을 분리합니다. 매달 돈을 갚고 있는데 잔액이 얼마나 줄어드는지 알고 싶을 때 한 회차의 원금 감소와 납입 후 잔액을 확인하는 도구입니다.",
    detail: "연이율을 12로 나눈 한 달 이율을 사용하며 실제 일수 계산은 하지 않습니다. 납입액이 이자보다 적으면 미충당 이자를 별도로 표시하고 잔액에 합산하는 가정이므로 연체료나 금융회사의 회계 처리와 다를 수 있습니다.",
    fields: [won("p", "납입 전 대출 잔액", 10000000), rate("rate", "연이율", 12), won("pay", "이번 달 납입액", 500000)],
    compute: ({ p, rate: a, pay }) => { const interest = p * monthly(a), actual = Math.min(pay, p + interest); return result("이번 달 원금 감소", Math.max(0, actual - interest), [R("이번 달 발생 이자", interest), R("납입 후 잔액", p + interest - actual), R("미충당 이자", Math.max(0, interest - actual))], "한 달 단위 계산이며 연체 수수료는 포함하지 않습니다."); },
    formula: "이자 = 잔액 × 연이율/12; 원금 감소 = max(0, 실제 납입액 − 이자)",
    questions: [["납입액이 원금보다 커도 되나요?", "원금과 발생 이자의 합계까지만 실제 납입으로 처리합니다."], ["납입액이 0이면요?", "원금은 줄지 않고 발생 이자를 미충당 이자로 표시합니다."], ["금융회사 이자와 왜 다를 수 있나요?", "계약은 일수 기준이나 별도 반올림 규칙을 적용할 수 있습니다."]], relatedSlugs: ["loan-balance-after-payments", "credit-line-daily-interest"] }),
  define({ slug: "payment-holiday-cost", title: "납입 유예 이자와 이후 상환액", category: "loan", source: "loan",
    intro: "일정 기간 원금과 이자를 모두 내지 않고 이자를 원금에 합산했을 때 이후 월 상환액을 계산합니다. 유예 중 늘어나는 잔액과 재개 뒤 납입액을 분리해 당장의 현금 여유가 이후 부담에 미치는 영향을 살펴보세요.",
    detail: "유예 기간에는 월복리로 이자를 원금에 더하고, 재개 뒤에는 입력한 별도 상환 기간에 걸쳐 원리금균등으로 갚는 모델입니다. 이자만 내는 거치나 정부 지원 제도를 계산하는 기능이 아니며 실제 약정이 이런 구조인지 확인해야 합니다.",
    fields: [won("p", "유예 시작 잔액", 10000000), rate(), months("pause", "전액 납입 유예 기간", 6), months("months", "재개 후 상환 기간", 36)],
    compute: ({ p, rate: a, pause, months: n }) => { const r = monthly(a), balance = p * growth(r, pause); return result("재개 후 월 상환액", payment(balance, r, n), [R("유예 중 합산된 이자", balance - p), R("재개 시점 잔액", balance)]); },
    formula: "재개 잔액 = 원금 × (1+월이율)^유예개월; 재개 납입액 = PMT(재개 잔액, 월이율, 상환개월)",
    questions: [["이자만 내는 거치도 이 결과인가요?", "아닙니다. 이자는 내지 않고 잔액에 합산하는 경우입니다."], ["유예 기간이 만기에 포함되나요?", "입력하는 재개 후 기간은 유예 기간과 별개입니다."], ["무이자 유예라면요?", "연이율을 0으로 입력하면 유예 중 잔액이 증가하지 않습니다."]], relatedSlugs: ["loan-monthly-payment", "loan-term-extension-cost"] }),
  define({ slug: "variable-rate-stress", title: "대출 금리 상승 부담 점검", category: "loan", source: "loan",
    intro: "같은 대출 잔액과 남은 기간에 두 금리를 적용해 월 상환액이 얼마나 달라지는지 비교합니다. 현재 금리와 직접 설정한 비교 금리로 월 가계 예산의 여유가 어느 정도 변하는지 계산하는 시나리오 도구입니다.",
    detail: "변경 시점의 잔액을 기준으로 남은 기간 전체에 새 금리가 적용되고 원리금균등 납입액이 다시 계산된다고 가정합니다. 향후 시장 금리를 예측하지 않으며 실제 변동 주기나 금리 상한 약정은 포함하지 않습니다.",
    fields: [won("p", "현재 대출 잔액", 100000000), rate("old", "현재 연이율", 4), rate("next", "비교할 연이율", 6), months("months", "남은 기간", 240), won("buffer", "현재 매달 예산 여유", 300000)],
    compute: ({ p, old, next, months: n, buffer }) => { const before = payment(p, monthly(old), n), after = payment(p, monthly(next), n); return result("월 상환액 변화", after - before, [R("변경 후 월 상환액", after), R("변경 후 예산 여유", buffer - (after - before))]); },
    formula: "월 부담 변화 = PMT(P, 새 월이율, n) − PMT(P, 기존 월이율, n)",
    questions: [["금리가 낮아지는 경우도 되나요?", "비교 금리를 낮추면 월 부담 변화가 음수로 표시됩니다."], ["추가 대출을 반영하나요?", "두 조건 모두 같은 잔액을 사용합니다."], ["예산 여유가 음수면 무엇인가요?", "가정한 금리 변화 후 월 지출이 예산을 초과한다는 뜻입니다."]], relatedSlugs: ["loan-monthly-payment", "loan-affordability"] }),
  define({ slug: "loan-term-extension-cost", title: "대출 만기 연장의 총비용", category: "loan", source: "loan",
    intro: "같은 잔액과 금리로 상환 기간만 바꾸었을 때 월 납입액과 남은 총이자를 함께 비교합니다. 월 부담을 낮추기 위해 만기를 연장하거나 더 빨리 갚기 위해 줄이려는 경우 기간 변경의 비용을 따로 확인할 수 있습니다.",
    detail: "두 경우 모두 현재부터 원리금균등으로 납입하고 연장 수수료나 금리 재조정은 없다고 가정합니다. 월 납입 감소와 총이자 증가를 동시에 확인해야 하며, 이 계산은 실제 대출 연장 가능 여부를 판단하지 않습니다.",
    fields: [won("p", "현재 잔액", 12000000), rate(), months("old", "기존 남은 기간", 24), months("next", "변경할 기간", 48)],
    compute: ({ p, rate: a, old, next }) => { const before = payment(p, monthly(a), old), after = payment(p, monthly(a), next); return result("총이자 변화", after * next - before * old, [R("월 납입 감소", before - after), R("변경 후 월 납입", after)]); },
    formula: "총이자 변화 = 새 월납입×새 기간 − 기존 월납입×기존 기간",
    questions: [["기간을 줄여도 되나요?", "가능합니다. 월 부담은 늘고 총이자는 줄어들 수 있습니다."], ["금리가 바뀌는 연장인가요?", "두 조건의 금리는 동일하게 고정합니다."], ["연장 수수료가 있다면요?", "표시된 총이자 변화에 실제 수수료를 더해 판단하세요."]], relatedSlugs: ["refinance-break-even", "loan-total-interest"] }),
  define({ slug: "debt-consolidation-payment", title: "두 대출 통합 상환 비교", category: "loan", source: "loan",
    intro: "금리와 남은 기간이 다른 두 대출을 하나로 통합할 때 월 납입액과 총 남은 이자가 어떻게 바뀌는지 계산합니다. 통합 초기 비용도 따로 입력해 월 부담 감소와 총비용 절감이 같은 방향인지 확인할 수 있습니다.",
    detail: "기존 두 대출과 새 통합 대출 모두 원리금균등 방식으로 계산합니다. 통합 수수료는 현금으로 별도 납부하며 원금에 합산하지 않습니다. 각 대출의 실제 납입 견적이나 연체 내역이 있다면 계산 가정과 차이가 없는지 확인하세요.",
    fields: [won("p1", "대출 A 잔액", 6000000), rate("r1", "대출 A 연이율", 8), months("n1", "대출 A 남은 기간", 24), won("p2", "대출 B 잔액", 6000000), rate("r2", "대출 B 연이율", 12), months("n2", "대출 B 남은 기간", 24), rate("r", "통합 대출 연이율", 6), months("n", "통합 대출 기간", 36), won("fee", "통합 초기 비용", 0)],
    compute: ({ p1, r1, n1, p2, r2, n2, r, n, fee }) => { const a = payment(p1, monthly(r1), n1), b = payment(p2, monthly(r2), n2), c = payment(p1 + p2, monthly(r), n); return result("초기 월 납입 감소", a + b - c, [R("통합 후 월 납입", c), R("총비용 절감", a * n1 + b * n2 - c * n - fee)], "기존 대출이 먼저 끝나는 시점 이후에는 월 납입액 차이가 달라집니다."); },
    formula: "초기 월 절감 = PMT(A)+PMT(B)−PMT(A+B); 총 절감 = 기존 총납입−통합 총납입−초기 비용",
    questions: [["월 절감이 끝까지 같나요?", "아닙니다. 먼저 만기가 끝나는 기존 대출 때문에 이후 차이가 변합니다."], ["수수료를 대출로 내는 경우는요?", "이 계산에서는 수수료를 별도 현금 지출로 처리합니다."], ["통합 금리가 낮으면 총비용도 줄까요?", "기간이 길어지면 총비용이 더 커질 수도 있습니다."]], relatedSlugs: ["debt-avalanche-vs-snowball", "loan-term-extension-cost"] }),
  define({ slug: "debt-avalanche-vs-snowball", title: "고금리 우선·소액 우선 상환 비교", category: "loan", source: "debt",
    intro: "두 채무의 최소 납입을 유지하고 남은 월 예산을 어느 채무에 먼저 넣을지 비교합니다. 고금리 채무부터 갚는 방식과 잔액이 작은 채무부터 갚는 방식의 완납 기간과 총이자를 동일한 예산으로 시뮬레이션합니다.",
    detail: "매월 이자를 발생시킨 뒤 각 채무의 최소 납입을 하고 남은 예산을 우선순위 채무에 배분합니다. 한 채무가 끝나면 남은 예산은 다른 채무로 이동합니다. 최소 납입액은 고정이며 600개월 내 완납되지 않는 조건은 별도 안내합니다.",
    fields: [won("p1", "채무 A 잔액", 3000000), rate("r1", "채무 A 연이율", 8), won("m1", "채무 A 최소 월납입", 100000), won("p2", "채무 B 잔액", 6000000), rate("r2", "채무 B 연이율", 18), won("m2", "채무 B 최소 월납입", 150000), won("budget", "전체 월 상환 예산", 500000)],
    compute: ({ p1, r1, m1, p2, r2, m2, budget }) => {
      if (budget < m1 + m2 || budget === 0) return invalid("월 상환 예산은 두 최소 납입액 합계 이상이며 0원보다 커야 합니다.");
      const simulate = (high: boolean) => { const b = [p1, p2], rates = [monthly(r1), monthly(r2)], minimums = [m1, m2]; let interest = 0, count = 0;
        while (b[0] + b[1] > 0.005 && count < 600) { let remaining = budget; for (let i = 0; i < 2; i++) { const charge = b[i] * rates[i]; interest += charge; b[i] += charge; const paid = Math.min(b[i], minimums[i]); b[i] -= paid; remaining -= paid; }
          const order = [0, 1].sort((a, z) => high ? rates[z] - rates[a] : b[a] - b[z]); for (const i of order) { const paid = Math.min(b[i], remaining); b[i] -= paid; remaining -= paid; } count++; }
        return { interest, count, finished: b[0] + b[1] <= 0.005 }; };
      const high = simulate(true), small = simulate(false); return !high.finished || !small.finished ? invalid("주어진 월 예산으로 두 방식 모두 600개월 안에 완납되는지 확인할 수 없어요. 예산을 늘려 주세요.") : result("고금리 우선의 이자 절감", small.interest - high.interest, [R("고금리 우선 완납", high.count, "개월"), R("소액 우선 완납", small.count, "개월"), R("고금리 우선 총이자", high.interest), R("소액 우선 총이자", small.interest)]);
    }, formula: "월 이자 발생 → 각 최소 납입 → 남은 예산을 높은 금리 또는 작은 잔액 순으로 배분",
    questions: [["최소 납입은 건너뛰나요?", "아니요. 두 채무의 최소 납입액을 먼저 배분합니다."], ["하나를 다 갚으면 예산이 줄어드나요?", "전체 예산은 유지하고 남은 채무에 옮겨 갚습니다."], ["어떤 방식이 더 좋다고 추천하나요?", "이 도구는 비용과 기간만 비교합니다. 지속 가능성과 계약 조건은 별도로 판단하세요."]], relatedSlugs: ["extra-payment-term", "debt-consolidation-payment"] }),
  define({ slug: "credit-line-daily-interest", title: "마이너스통장 잔액 구간별 이자", category: "loan", source: "loan",
    intro: "한 기간 동안 사용 잔액이 바뀐 마이너스통장 이자를 두 구간으로 나누어 계산합니다. 각 잔액을 사용한 실제 일수와 연이율을 입력해 사용 금액에 따른 일별 단리 이자와 전체 기간 평균 사용액을 확인하세요.",
    detail: "구간은 서로 겹치지 않고 연이율이 같다고 가정하며 이자는 원금에 합산하지 않습니다. 계약상 연 기준 일수로 365일 또는 윤년의 366일 등 실제 기준을 입력해야 하며 사용하지 않은 한도의 수수료는 별도입니다.",
    fields: [won("p1", "첫 구간 사용 잔액", 1000000), num("d1", "첫 구간 일수", 10, "일", 0, 366), won("p2", "둘째 구간 사용 잔액", 2000000), num("d2", "둘째 구간 일수", 20, "일", 0, 366), rate("rate", "연이율", 7), num("basis", "계약상 연 기준 일수", 365, "일", 360, 366)],
    compute: ({ p1, d1, p2, d2, rate: a, basis }) => d1 + d2 === 0 || d1 + d2 > 366 ? invalid("겹치지 않는 전체 기간을 1~366일로 입력하세요.") : result("두 구간 이자 합계", (p1 * d1 + p2 * d2) * a / 100 / basis, [R("평균 사용 잔액", (p1 * d1 + p2 * d2) / (d1 + d2))]),
    formula: "이자 = (잔액A×일수A + 잔액B×일수B) × 연이율 ÷ 연 기준 일수",
    questions: [["한도 금액을 넣나요?", "한도가 아니라 실제로 사용한 잔액을 입력합니다."], ["잔액이 더 자주 바뀌면요?", "동일 잔액 구간끼리 합치거나 구간별로 나누어 계산한 이자를 합산하세요."], ["발생 이자가 다음 이자에 포함되나요?", "이 계산에서는 단리로 처리해 이자를 잔액에 합산하지 않습니다."]], relatedSlugs: ["loan-interest-principal-split", "simple-interest-quick"] }),
  define({ slug: "loan-cashflow-effective-rate", title: "선취 수수료 포함 대출 유효금리", category: "loan", source: "loan",
    intro: "대출 실행 때 수수료를 먼저 차감해 실제 받는 돈이 줄어드는 경우 월 납입액에 담긴 유효금리를 역산합니다. 실수령 대출금과 이후 동일한 월 납입을 현재가치로 맞추어 명목 금리만으로 보기 어려운 부담을 비교합니다.",
    detail: "대출 실행 직후 순수령액을 받고 다음 달 말부터 동일한 금액을 납입한다고 가정합니다. 계산한 월 수익률을 연복리로 환산한 비교용 값이며 법정 공시 연이율이나 금융회사의 공식 APR 산정 결과를 대신하지 않습니다.",
    fields: [won("p", "계약 원금", 12000000), won("fee", "실행 시 차감 수수료", 300000), won("pay", "실제 월 납입액", 400000), months()],
    compute: ({ p, fee, pay, months: n }) => { const net = p - fee; if (net <= 0 || pay <= 0 || pay * n < net) return invalid("순수령액과 월 납입액은 양수이며 총납입액은 순수령액 이상이어야 합니다."); if (pay * n === net) return result("수수료 포함 연 유효금리", 0, [R("실제 수령액", net)], undefined, "%"); let low = 0, high = 1; const pv = (r: number) => pay * -Math.expm1(-n * Math.log1p(r)) / r; if (pv(high) > net) return invalid("월 유효금리가 100%를 넘는 조건은 계산 범위 밖입니다."); for (let i = 0; i < 100; i++) { const mid = (low + high) / 2; if (pv(mid) > net) low = mid; else high = mid; } const r = (low + high) / 2; return result("수수료 포함 연 유효금리", Math.expm1(12 * Math.log1p(r)) * 100, [R("실제 수령액", net), R("순수령 대비 총비용", pay * n - net)], "법정 공시금리가 아닌 월별 현금흐름 비교용 연복리 환산입니다.", "%"); },
    formula: "순수령액 = Σ 월납입/(1+r)^k를 만족하는 월 r 역산; 연 유효금리 = (1+r)^12−1",
    questions: [["수수료를 별도로 내도 되나요?", "실행 당일 현금으로 지출하는 선취 비용은 순수령액 감소와 같은 방식으로 볼 수 있습니다."], ["월 납입액이 바뀌는 대출도 되나요?", "동일한 월 납입액과 월말 납입 조건만 지원합니다."], ["금리가 명목 금리보다 높게 보이는 이유는요?", "선취 비용과 월복리 환산을 반영하기 때문입니다. 공식 공시금리와 정의가 다를 수 있습니다."]], relatedSlugs: ["refinance-break-even", "loan-total-interest"] }),
];

const SALARY: CalculatorDef[] = [
  define({ slug: "salary-purchasing-power", title: "물가 반영 실질 월급 비교", category: "salary", source: "wage",
    intro: "예전 월급과 현재 월급을 같은 구매력 기준으로 비교합니다. 두 시점의 소비자물가지수를 입력하면 현재 월급을 과거 물가 기준으로 바꾸고 명목 월급 증가율과 실질 월급 증가율을 구분해 확인할 수 있습니다.",
    detail: "물가지수는 동일한 기관과 기준 연도를 사용하는 두 값이어야 합니다. 월급도 세전 또는 세후 중 한 기준으로 맞춰야 하며, 평균 소비자물가가 개인의 주거비·교육비 등 실제 생활비 변화를 그대로 나타내는 것은 아닙니다.",
    fields: [won("old", "과거 월급", 3000000), won("next", "현재 월급", 3300000), num("cpi1", "과거 소비자물가지수", 100, "지수", 0.01, 10000, 0.01), num("cpi2", "현재 소비자물가지수", 105, "지수", 0.01, 10000, 0.01)],
    compute: ({ old, next, cpi1, cpi2 }) => old === 0 ? invalid("비교 기준인 과거 월급은 0원보다 커야 합니다.") : result("과거 물가 기준 현재 월급", next * cpi1 / cpi2, [R("실질 월급 변화", (next * cpi1 / cpi2 / old - 1) * 100, "%"), R("명목 월급 변화", (next / old - 1) * 100, "%")]),
    formula: "실질 현재 월급 = 현재 월급×과거 CPI/현재 CPI; 실질 증감률 = 실질 현재 월급/과거 월급−1",
    questions: [["CPI의 기준 연도가 다르면요?", "동일한 기준 연도로 제공된 두 지수를 사용해야 합니다."], ["세전과 세후를 섞어도 되나요?", "세금 변화와 물가 효과가 섞이므로 동일한 기준을 사용하세요."], ["실질 월급이 줄었다는 뜻은요?", "선택한 평균 물가 기준으로 살 수 있는 양이 줄었다는 의미입니다."]], relatedSlugs: ["real-return-quick", "salary-raise-timing"] }),
  define({ slug: "commute-adjusted-offer", title: "통근 비용·시간 포함 이직 비교", category: "career",
    intro: "현재 회사와 새 회사의 세후 월급에서 직접 통근비를 빼고 근로시간과 통근시간을 합쳐 시간당 보상을 비교합니다. 월급 인상만으로는 드러나지 않는 출퇴근 부담을 같은 시간 단위로 평가할 때 사용할 수 있습니다.",
    detail: "월 근로시간과 통근시간은 실제 한 달 합계를 넣고 교통비는 회사 지원금을 뺀 본인 부담액을 사용하세요. 이 결과는 생활시간 관점의 비교값이며 법정 시급·최저임금 판정이나 근로시간 인정 여부를 계산하지 않습니다.",
    fields: [won("a", "현재 세후 월급", 3000000), won("ac", "현재 월 통근비", 100000), num("ah", "현재 월 근로·통근 합계", 180, "시간", 1, 744, 0.5), won("b", "새 회사 세후 월급", 3300000), won("bc", "새 회사 월 통근비", 200000), num("bh", "새 회사 월 근로·통근 합계", 210, "시간", 1, 744, 0.5)],
    compute: ({ a, ac, ah, b, bc, bh }) => result("시간당 보상 변화", (b - bc) / bh - (a - ac) / ah, [R("현재 시간당 보상", (a - ac) / ah), R("새 회사 시간당 보상", (b - bc) / bh), R("월 통근비 차감 수입 변화", b - bc - a + ac)]),
    formula: "시간당 생활 보상 = (세후 월급−본인 통근비)/(월 근로시간+월 통근시간)",
    questions: [["통근시간은 어떻게 입력하나요?", "왕복 통근시간에 출근일수를 곱한 뒤 월 근로시간에 더합니다."], ["법정 시급과 같은가요?", "아닙니다. 통근시간까지 포함한 개인 의사결정용 지표입니다."], ["교통비 지원이 있으면요?", "지원금을 제외하고 실제 본인이 내는 비용만 입력하세요."]], relatedSlugs: ["work-from-home-savings", "flex-time-tradeoff"] }),
  define({ slug: "work-from-home-savings", title: "재택근무 전환 순절감액", category: "career",
    intro: "출근일 일부를 재택근무로 바꾸면 줄어드는 교통비와 식비에서 집에서 추가로 쓰는 비용을 차감합니다. 월 재택일수와 하루 비용을 직접 입력해 월·연 절감액을 확인하고 근무 방식에 따른 생활비 계획을 비교하세요.",
    detail: "하루 식비 절감액에는 밖에서 먹는 비용 전체가 아닌 집에서 먹는 비용과의 차이를 입력하세요. 재택용 장비처럼 한 번 발생하는 지출은 별도로 넣으며 연 절감액은 같은 재택 일정이 12개월 유지되는 가정입니다.",
    fields: [num("days", "매달 재택 전환일", 8, "일", 0, 31), won("transport", "하루 줄어드는 교통비", 6000), won("meal", "하루 식비 차액", 5000), won("home", "재택일 하루 추가 비용", 2000), won("setup", "일회성 재택 준비비", 200000)],
    compute: ({ days, transport, meal, home, setup }) => { const saving = days * (transport + meal - home); return result("첫해 순절감액", saving * 12 - setup, [R("매달 절감액", saving), R("둘째 해 동일 조건 절감", saving * 12)]); },
    formula: "첫해 순절감 = 월 재택일×(교통비 절감+식비 차액−집의 추가 비용)×12−준비비",
    questions: [["식비 전체를 넣어도 되나요?", "집에서도 식비가 들므로 두 장소의 비용 차이를 입력합니다."], ["준비비는 매년 빼나요?", "첫해에 한 번만 차감합니다."], ["음수 결과는 무엇인가요?", "가정한 비용에서는 재택 추가 비용이 절감액보다 크다는 뜻입니다."]], relatedSlugs: ["commute-adjusted-offer", "salary-raise-timing"] }),
  define({ slug: "bonus-versus-raise", title: "일회성 보너스와 기본급 인상 비교", category: "salary",
    intro: "한 번 받는 보너스와 매달 늘어나는 고정급을 같은 비교 기간으로 놓고 누적 금액을 계산합니다. 보너스를 지금 받는 조건과 다음 달부터 급여가 올라가는 조건 중 어느 쪽이 언제부터 더 많은 현금을 주는지 확인하세요.",
    detail: "보너스와 월 인상액은 둘 다 세전 또는 세후 중 같은 기준으로 입력합니다. 인상액은 매달 동일하고 추가 인상·퇴직금·성과급 연동·물가·투자 수익은 제외하므로 기본급 변화가 만드는 모든 효과를 뜻하지는 않습니다.",
    fields: [won("bonus", "지금 받는 일회성 보너스", 3000000), won("raise", "매달 고정급 인상액", 200000), months("months", "비교 기간", 24)],
    compute: ({ bonus, raise, months: n }) => result("기본급 인상의 누적 우위", raise * n - bonus, [R("기간 내 인상 합계", raise * n), R("보너스와 같아지는 시점", raise > 0 ? Math.ceil(bonus / raise) : 0, "개월")], raise === 0 ? "월 인상액이 0원이어서 추월 시점이 없습니다. 0개월은 즉시 회수를 의미하지 않습니다." : "같은 세전·세후 기준의 단순 현금 합계입니다."),
    formula: "누적 우위 = 월 인상액×비교 개월−보너스; 추월 개월 = 올림(보너스/월 인상액)",
    questions: [["보너스는 매년 받는 돈인가요?", "이 계산에서는 지금 한 번만 받습니다."], ["인상으로 퇴직금도 늘어나나요?", "그 효과는 계약과 제도에 따라 달라 이 계산에서 제외합니다."], ["추월 시점이 기간보다 길면요?", "입력한 비교 기간 안에서는 보너스 쪽 누적 금액이 더 클 수 있습니다."]], relatedSlugs: ["salary-raise-timing", "bonus-repayment-reserve"] }),
  define({ slug: "salary-raise-timing", title: "연봉 인상 적용월의 올해 소득", category: "salary",
    intro: "연봉 인상률이 같아도 적용을 시작하는 달에 따라 올해 실제로 받는 급여 합계는 달라집니다. 기존 월 기본급, 인상률과 시작 월을 입력해 올해 추가 급여와 인상 후 월급, 다음 해의 연간 기본급을 계산합니다.",
    detail: "1월부터 12월까지 근무하고 적용 월의 급여부터 전액 인상된다고 가정합니다. 월 중간 인상이나 소급 정산, 상여금 연동은 포함하지 않으며 기존 월 기본급과 인상률은 회사가 안내한 같은 급여 항목 기준을 사용하세요.",
    fields: [won("salary", "인상 전 월 기본급", 3000000), pct("raise", "기본급 인상률", 5), num("start", "인상 적용 시작 월", 7, "월", 1, 12)],
    compute: ({ salary, raise, start }) => { const extra = salary * raise / 100; return result("올해 추가 기본급", extra * (13 - start), [R("올해 기본급 합계", salary * 12 + extra * (13 - start)), R("인상 후 월 기본급", salary + extra), R("다음 해 연간 기본급", (salary + extra) * 12)]); },
    formula: "올해 추가 기본급 = 기존 월 기본급×인상률×(13−적용 시작 월)",
    questions: [["7월 적용이면 몇 달인가요?", "7월부터 12월까지 6개월입니다."], ["소급 지급도 들어가나요?", "별도의 소급 지급은 합산하지 않으므로 실제 추가 수령액에 더해야 합니다."], ["다음 해 추가 인상도 반영하나요?", "아니요. 현재 인상된 급여가 그대로 유지된다고 가정합니다."]], relatedSlugs: ["bonus-versus-raise", "salary-purchasing-power"] }),
  define({ slug: "unpaid-leave-budget", title: "무급휴가 급여 감소 예산", category: "salary",
    intro: "회사에서 안내한 일할 공제 기준으로 무급휴가 기간의 예상 급여 감소와 남는 월 예산을 계산합니다. 월 급여를 나누는 기준 일수를 직접 입력하므로 근무일 기준이나 달력일 기준 등 확인한 계약 조건을 비교할 수 있습니다.",
    detail: "이 도구는 급여 공제에 관한 법적 기준을 결정하지 않습니다. 세후 예산을 비교하려면 회사가 안내한 세후 급여 및 공제 방식에 맞는 값을 사용하고, 보험료·비과세 수당·별도 휴직 급여 변동은 추가로 확인하세요.",
    fields: [won("salary", "비교 기준 월 급여", 3000000), num("basis", "회사 공제 기준 일수", 30, "일", 1, 31), num("leave", "무급 처리 일수", 5, "일", 0, 31), won("bills", "해당 월 예정 지출", 2200000)],
    compute: ({ salary, basis, leave, bills }) => leave > basis ? invalid("무급 일수는 회사의 공제 기준 일수 이하로 입력하세요.") : result("해당 월 예상 잔여 예산", salary * (1 - leave / basis) - bills, [R("급여 감소액", salary * leave / basis), R("감소 후 급여", salary * (1 - leave / basis))]),
    formula: "급여 감소 = 월 급여/계약상 기준 일수×무급 일수; 잔여 예산 = 급여−감소−지출",
    questions: [["일할 기준은 30일로 정해져 있나요?", "아닙니다. 회사와 계약에서 확인한 기준을 직접 입력해야 합니다."], ["무급휴직 급여를 확정하나요?", "예산 비교용 모델이며 회사의 실제 공제 방식을 확정하지 않습니다."], ["남는 예산이 음수면요?", "예상 지출이 해당 월 급여보다 많아 별도 자금이 필요하다는 의미입니다."]], relatedSlugs: ["job-transition-cash-gap", "parental-leave-household-gap"] }),
  define({ slug: "career-training-payback", title: "직무교육 투자 비용 회수", category: "career",
    intro: "직무 전환을 위해 드는 교육비와 교육 기간의 소득 감소를 합산하고 이후 월 소득 증가로 회수하는 기간을 계산합니다. 교육 자체의 비용뿐 아니라 일하는 시간을 줄여 발생하는 기회비용도 함께 보려는 경우에 유용합니다.",
    detail: "월 소득 증가액은 사용자가 설정하는 가정이며 취업이나 임금 상승을 보장하지 않습니다. 회수 기간은 교육 종료 후부터 세고 교육 기간을 합친 전체 기간도 표시합니다. 소득이 늘지 않으면 회수 기간이 생기지 않습니다.",
    fields: [won("tuition", "교육·자격 준비 비용", 3000000), won("lost", "교육 중 매달 소득 감소", 1000000), months("train", "교육 기간", 3), won("gain", "교육 후 가정 월 소득 증가", 500000)],
    compute: ({ tuition, lost, train, gain }) => gain === 0 ? invalid("교육 후 월 소득 증가가 0원이면 금전적 회수 기간을 계산할 수 없습니다.") : result("교육 종료 후 회수 기간", Math.ceil((tuition + lost * train) / gain), [R("교육의 전체 비용", tuition + lost * train), R("교육 시작부터 회수", train + Math.ceil((tuition + lost * train) / gain), "개월")], "소득 증가가 바로 시작되고 계속 유지된다는 가정입니다.", "개월"),
    formula: "전체 투자 = 교육비+교육 중 월 소득 감소×교육 개월; 회수 = 올림(전체 투자/월 소득 증가)",
    questions: [["생활비도 교육비에 넣나요?", "교육 때문에 추가로 늘어난 지출만 넣고 평소 생활비와 중복 계산하지 마세요."], ["교육 중 잃는 소득이 없으면요?", "월 소득 감소액을 0원으로 입력합니다."], ["취업 준비 공백도 반영하려면요?", "그 공백의 비용을 교육·준비 비용에 포함해 별도 시나리오로 비교하세요."]], relatedSlugs: ["job-transition-cash-gap", "bonus-versus-raise"] }),
  define({ slug: "flex-time-tradeoff", title: "근무시간 단축의 시간당 비용", category: "career",
    intro: "근무시간을 줄이며 월 수입이 변하는 경우 되찾는 시간 한 시간당 소득 감소와 남은 생활비 여유를 계산합니다. 현재·변경 후 월 근로시간과 같은 기준의 수입을 넣어 개인적인 시간 활용 결정을 비교하세요.",
    detail: "시간당 비용은 급여 감소를 줄어든 근로시간으로 나눈 개인 비교값입니다. 법정 단축근무 급여나 지원금을 자동 적용하지 않으며 지원이 확정된 경우 변경 후 수입에 실제 수령 예정액을 포함해 계산할 수 있습니다.",
    fields: [won("old", "현재 월 수입", 3000000), won("next", "변경 후 월 수입", 2500000), num("h1", "현재 월 근로시간", 180, "시간", 1, 744, 0.5), num("h2", "변경 후 월 근로시간", 140, "시간", 0, 744, 0.5), won("bills", "월 필수 지출", 2000000)],
    compute: ({ old, next, h1, h2, bills }) => h2 >= h1 ? invalid("변경 후 근로시간은 현재보다 작아야 단축 시간의 비용을 계산합니다.") : result("되찾는 시간당 소득 감소", (old - next) / (h1 - h2), [R("월 확보 시간", h1 - h2, "시간"), R("변경 후 예산 여유", next - bills)]),
    formula: "시간당 소득 감소 = (현재 수입−변경 후 수입)/(현재 시간−변경 후 시간)",
    questions: [["지원금이 있으면 어떻게 넣나요?", "확정된 월 지원금을 변경 후 수입에 더하고 지급 기간을 별도로 확인하세요."], ["수입이 늘면서 시간이 줄면요?", "시간당 소득 감소가 음수로 표시되어 금전적으로도 개선됨을 뜻합니다."], ["법정 급여 산식인가요?", "아니요. 사용자가 입력한 수입과 시간의 개인 예산 비교입니다."]], relatedSlugs: ["commute-adjusted-offer", "unpaid-leave-budget"] }),
  define({ slug: "bonus-repayment-reserve", title: "사이닝보너스 반환 준비액", category: "career",
    intro: "일정 기간 근무를 조건으로 받은 보너스에 월별 비례 반환 조항이 있을 때 남은 계약 기간에 대응하는 금액을 계산합니다. 이미 근무한 개월과 따로 보관한 금액을 입력해 추가로 마련할 반환 준비액을 확인하세요.",
    detail: "계약서가 남은 기간에 비례해 반환하도록 명시된 경우에만 맞는 모델입니다. 전액 반환·특정 날짜 면제·세금 환급 여부는 포함하지 않으며 계약의 효력이나 실제 반환 의무에 관한 법률 판단도 제공하지 않습니다.",
    fields: [won("bonus", "계약상 반환 기준 보너스", 12000000), months("term", "의무 근무 계약 기간", 24), num("served", "완료한 근무 개월", 12, "개월", 0, 600), won("saved", "따로 보관한 반환 준비금", 3000000)],
    compute: ({ bonus, term, served, saved }) => served > term ? invalid("완료 개월은 계약 기간 이하로 입력하세요.") : result("추가로 마련할 준비액", Math.max(0, bonus * (term - served) / term - saved), [R("비례 반환 가정액", bonus * (term - served) / term)], "비례 반환 조항을 가정합니다. 실제 계약의 반환 방식·세무 처리를 확인하세요."),
    formula: "가정 반환액 = 기준 보너스×남은 개월/전체 계약 개월",
    questions: [["모든 사이닝보너스에 이 식을 쓰나요?", "아닙니다. 남은 기간에 비례하는 계약 조건에서만 사용합니다."], ["세전과 세후 중 무엇인가요?", "계약이 반환 기준으로 정한 금액을 사용하세요."], ["법적 반환 의무를 확인해 주나요?", "아니요. 계약 효력이나 의무 판단은 이 계산의 범위가 아닙니다."]], relatedSlugs: ["job-transition-cash-gap", "bonus-versus-raise"] }),
  define({ slug: "split-payday-budget", title: "월 2회 급여의 현금 부족일", category: "salary",
    intro: "월 수입 합계가 충분해도 급여일보다 카드값이나 월세일이 빠르면 잔액이 부족할 수 있습니다. 한 달 두 번의 입금과 두 번의 큰 출금 날짜를 배치해 가장 낮은 잔액과 추가로 필요한 시작 자금을 계산합니다.",
    detail: "1일부터 31일까지의 한 달을 모델링하며 같은 날에는 입금 뒤 출금되는 순서를 가정합니다. 생활비 등 추가 거래는 두 출금 항목에 합산하거나 별도로 여유 자금을 남겨야 하며 실제 은행의 당일 처리 순서는 다를 수 있습니다.",
    fields: [won("start", "1일 시작 잔액", 100000), won("pay1", "첫 급여 입금액", 1500000), num("day1", "첫 급여일", 10, "일", 1, 31), won("pay2", "둘째 급여 입금액", 1500000), num("day2", "둘째 급여일", 25, "일", 1, 31), won("bill1", "첫 지출 금액", 1000000), num("due1", "첫 지출일", 5, "일", 1, 31), won("bill2", "둘째 지출 금액", 1000000), num("due2", "둘째 지출일", 20, "일", 1, 31)],
    compute: ({ start, pay1, day1, pay2, day2, bill1, due1, bill2, due2 }) => { let balance = start, lowest = start, day = 1; for (let d = 1; d <= 31; d++) { if (d === day1) balance += pay1; if (d === day2) balance += pay2; if (d === due1) balance -= bill1; if (d === due2) balance -= bill2; if (balance < lowest) { lowest = balance; day = d; } } return result("추가로 필요한 시작 자금", Math.max(0, -lowest), [R("가장 낮은 잔액", lowest), R("최저 잔액 첫 발생일", day, "일"), R("월말 잔액", balance)], "동일 날짜는 입금 후 출금 순서입니다. 실제 처리 시간은 확인하세요."); },
    formula: "일별 잔액 = 전일 잔액+해당일 입금−출금; 추가 자금 = max(0,−월 최저 잔액)",
    questions: [["월말 잔액이 양수인데 추가 자금이 필요한 이유는요?", "급여 전 지출 때문에 월중 잔액이 음수가 될 수 있습니다."], ["같은 날 거래 순서는요?", "입금을 먼저 계산하므로 출금이 먼저 처리되는 계좌는 더 여유를 두세요."], ["세 번째 큰 지출은 어떻게 하나요?", "이 도구는 두 입금·두 출금만 지원하므로 거래가 많은 달은 별도 현금흐름표로 확인하세요."]], relatedSlugs: ["irregular-income-baseline", "emergency-fund-runway"] }),
  define({ slug: "irregular-income-baseline", title: "불규칙 수입의 생활비 점검", category: "salary",
    intro: "최근 세 달의 실제 수입을 입력해 평균·중앙값·최저 수입을 비교하고 가장 적게 번 달에도 필수 지출이 충당되는지 확인합니다. 성과급이나 일시적 수입 때문에 평균이 높아 보이는 상황에서 지출 기준을 점검하는 도구입니다.",
    detail: "중앙값은 세 수입을 크기순으로 정렬한 가운데 값이며 미래 수입을 예측하는 금액은 아닙니다. 세후 실제 사용 가능한 수입을 사용하고 소득이 계절적으로 바뀐다면 세 달보다 긴 기록을 추가로 살펴보세요.",
    fields: [won("a", "첫 달 사용 가능 수입", 2000000), won("b", "둘째 달 사용 가능 수입", 3000000), won("c", "셋째 달 사용 가능 수입", 5000000), won("bills", "매달 필수 지출", 2500000)],
    compute: ({ a, b, c, bills }) => { const sorted = [a, b, c].sort((x, y) => x - y); return result("최저 수입 월의 지출 부족", Math.max(0, bills - sorted[0]), [R("세 달 중앙값 수입", sorted[1]), R("세 달 평균 수입", (a + b + c) / 3), R("평균 기준 월 여유", (a + b + c) / 3 - bills)]); },
    formula: "부족액 = max(0,필수 지출−최근 3개월 최저 수입); 중앙값 = 정렬한 3개 수입의 가운데",
    questions: [["중앙값을 미래 수입으로 봐도 되나요?", "아니요. 중앙값은 최근 세 달 수입을 크기순으로 늘어놓았을 때 가운데 값으로 과거를 요약한 통계일 뿐 다음 달 수입을 예측하지 않습니다. 기본값에서 중앙값 3,000,000원은 평균 3,333,333원보다 낮은데, 이렇게 평균이 중앙값보다 높으면 한두 달의 큰 수입이 평균을 끌어올린 것이므로 지출 기준은 중앙값이나 최저 수입에 맞추는 편이 안전합니다."], ["매출을 그대로 넣어도 되나요?", "매출이 아니라 세금과 사업비를 뺀 뒤 개인이 생활비로 쓸 수 있는 금액을 넣어야 합니다. 프리랜서 인적용역 소득은 소득세법 제129조에 따라 소득세 3%와 지방소득세를 합한 3.3%가 원천징수된 뒤 입금되고, 다음 해 5월 종합소득세 신고에서 추가 납부나 환급이 생길 수 있으므로 그 몫까지 감안한 세후 금액이 기준입니다."], ["수입이 없는 달은요?", "수입이 없던 달은 0원을 그대로 입력합니다. 그러면 최저 수입이 0원이 되어 필수 지출 전액이 그 달의 부족액으로 잡히고, 세 달 평균과 중앙값도 함께 낮아져 비수기를 포함한 현실적인 기준선을 볼 수 있습니다. 부족액을 메울 현금이 몇 달치인지는 현재 비상금으로 버틸 기간 계산기로 이어서 확인하세요."], ["불규칙 수입은 생활비를 어떻게 정해야 하나요?", "이 계산기의 결과처럼 가장 적게 번 달에도 필수 지출이 충당되는 수준을 기본 생활비로 두고, 평균을 넘는 달의 초과분은 세금 몫과 비상금으로 먼저 떼어 두는 방식이 무난합니다. 기본값에서는 최저 수입 월에 500,000원이 부족하므로 필수 지출을 줄이거나 그만큼의 완충 현금을 미리 마련해 두어야 한다는 뜻입니다."]], relatedSlugs: ["split-payday-budget", "emergency-fund-target"],
    details: "최근 세 달 수입이 들쭉날쭉한 프리랜서·영업직·자영업자가 가장 적게 번 달에도 필수 지출을 감당할 수 있는지 점검하는 계산기입니다. 성과급이나 일시 수입이 낀 달 때문에 평균이 높아 보이는 착시를 걷어내려는 용도이며, 기본값은 세 달 수입이 200만원·300만원·500만원이고 매달 필수 지출이 250만원인 상황입니다.\n\n기본값에서 세 달 평균 수입은 3,333,333원이고 평균 기준 월 여유는 833,333원이지만, 크기순 가운데 값인 중앙값 수입은 3,000,000원이고 가장 적게 번 첫 달 2,000,000원은 필수 지출 2,500,000원에 못 미쳐 최저 수입 월의 지출 부족이 500,000원으로 표시됩니다. 평균만 보면 여유가 있어 보여도 낮은 달에는 부족이 생기는 구조를 그대로 보여 줍니다.\n\n사용 가능 수입은 세후 기준이어야 합니다. 소득세법 제129조(2026년 7월 1일 시행 기준)는 원천징수 대상 사업소득의 원천징수세율을 3%로 정하고 있어 인적용역 프리랜서는 지급액에서 소득세 3%와 지방소득세를 합한 3.3%를 뗀 금액을 받으며, 국세청 종합소득세 모두채움 신고 안내는 3.3% 원천징수된 인적용역 사업소득도 종합소득세 신고 대상이고 2025년 귀속 소득은 2026년 6월 1일까지 신고·납부하도록 안내합니다. 5월 신고 뒤 추가 납부나 환급이 생길 수 있으므로 세 달 수입에서 세금 몫을 따로 떼어 두는 편이 안전합니다.\n\n세 달만 보기 때문에 계절성이 큰 업종은 더 긴 기록으로 다시 봐야 하고, 사업자라면 매출이 아니라 세금과 사업비를 뺀 개인 사용 가능 수입을 넣어야 합니다. 부족한 달을 메울 현금이 몇 달치인지는 현재 비상금으로 버틸 기간 계산기로, 급여일 사이의 현금 부족은 월 2회 급여의 현금 부족일 계산기로, 프리랜서 세금은 도구 메뉴의 프리랜서 세금 계산기로 이어서 확인하세요.",
    caveats: ["세 달 수입은 3.3% 원천징수와 종합소득세 정산까지 반영한 세후 사용 가능 금액으로 넣어야 부족액이 과소평가되지 않습니다.", "중앙값과 최저 수입은 과거 세 달의 요약값일 뿐 다음 달 수입을 예측하지 않으며, 계절 업종은 1년치 기록으로 다시 점검해야 합니다.", "필수 지출에는 월세·대출 원리금·보험료·공과금처럼 수입이 없는 달에도 나가는 항목만 넣고, 줄일 수 있는 소비는 빼야 최저 기준선이 됩니다."], individualCaveats: true,
    sources: [{ title: "국세청 — 종합소득세 모두채움 신고 안내(납부), 2025년 귀속 소득의 2026년 신고", url: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?mi=40483&cntntsId=238978" }, { title: "법제처 국가법령정보센터 — 소득세법 제129조 원천징수세율(2026)", url: "https://www.law.go.kr/법령/소득세법/제129조" }] }),
  define({ slug: "job-transition-cash-gap", title: "이직 급여 공백 준비금", category: "career",
    intro: "마지막 급여와 첫 새 급여 사이에 소득이 비는 동안 필요한 생활비와 한 번 발생하는 비용을 합산합니다. 공백 일수, 하루 필수 생활비, 확정 수입과 사용 가능한 현금을 입력해 추가로 마련할 금액을 계산하세요.",
    detail: "퇴직금이나 정산금은 실제 입금 시점이 공백 기간 안으로 확정된 경우에만 수입에 넣습니다. 일상 비용은 하루 기준, 이사나 준비 비용은 일회성으로 구분하며 확정되지 않은 성과급을 포함하면 필요한 자금을 과소평가할 수 있습니다.",
    fields: [num("days", "급여 공백 기간", 45, "일", 0, 730), won("daily", "하루 필수 생활비", 50000), won("once", "공백 중 일회성 비용", 500000), won("income", "공백 중 확정 입금", 0), won("cash", "사용 가능한 현금", 1000000)],
    compute: ({ days, daily, once, income, cash }) => result("추가 준비가 필요한 금액", Math.max(0, days * daily + once - income - cash), [R("공백 기간 총 필요액", days * daily + once), R("공백 종료 예상 잔액", cash + income - days * daily - once)]),
    formula: "추가 준비금 = max(0,공백 일수×하루 생활비+일회성 비용−확정 입금−사용 가능 현금)",
    questions: [["퇴직금은 넣어도 되나요?", "공백 중 입금이 확정된 금액만 포함하세요."], ["새 회사 급여일을 모르면요?", "급여 마감일과 첫 지급일을 회사에 확인한 뒤 일수를 입력하세요."], ["생활비와 일회성 비용은 어떻게 나누나요?", "매일 발생하는 비용은 하루 생활비, 한 번만 쓰는 비용은 일회성에 넣습니다."]], relatedSlugs: ["career-training-payback", "bonus-repayment-reserve"] }),
];

const SAVINGS: CalculatorDef[] = [
  define({ slug: "savings-required-monthly", title: "목표까지 필요한 월 저축액", category: "investment", source: "saving",
    intro: "정해진 시점에 목표 금액을 마련하려면 매달 얼마를 모아야 하는지 역산합니다. 이미 모은 돈과 목표 기간, 가정 이율을 입력하면 현재 자금의 성장분을 제외한 추가 월 적립액과 직접 납입할 원금 합계를 확인합니다.",
    detail: "월말마다 같은 금액을 넣고 연이율을 12로 나누어 월복리로 적용합니다. 세금과 수수료는 포함하지 않으므로 필요하면 비용을 차감한 가정 수익률로 비교하세요. 현재 자금만으로 목표를 충족하면 필요한 월납입은 0원입니다.",
    fields: [won("goal", "마련할 목표 금액", 30000000), won("p", "이미 모은 돈", 6000000), months("months", "목표까지 남은 기간", 36), rate()],
    compute: ({ goal, p, months: n, rate: a }) => { const m = needMonthly(goal, p, monthly(a), n); return result("필요한 월말 저축액", m, [R("직접 납입할 원금 합계", p + m * n), R("현재 자금만의 예상 미래가치", p * growth(monthly(a), n))]); },
    formula: "월납입 = max(0,(목표−현재금액×(1+r)^n)/(((1+r)^n−1)/r)); r=0이면 부족액/n",
    questions: [["이율을 0으로 넣어도 되나요?", "현재 자금을 뺀 목표 부족액을 개월수로 나눕니다."], ["월초 저축이면 결과가 달라지나요?", "월초에는 한 달 더 이자가 붙으므로 별도 월초·월말 비교 도구를 사용하세요."], ["금액이 이미 목표보다 크면요?", "추가 월 저축 필요액을 0원으로 표시합니다."]], relatedSlugs: ["savings-goal-time", "savings-start-delay"] }),
  define({ slug: "savings-start-delay", title: "저축 시작을 미룬 기회비용", category: "investment", source: "saving",
    intro: "동일한 목표 날짜를 두고 매달 저축을 지금 시작하는 경우와 몇 달 뒤 시작하는 경우의 차이를 계산합니다. 단순히 빠지는 납입 원금뿐 아니라 먼저 넣은 돈에 붙을 수 있었던 가정 수익까지 구분해 보여 줍니다.",
    detail: "초기 자금은 없고 매달 말 같은 금액을 납입하는 조건입니다. 지연 기간 동안 따로 모으는 돈도 없다고 가정하며 목표 날짜를 뒤로 미루지 않습니다. 수익률은 일정한 가정이므로 실제 투자 성과를 예측하는 결과는 아닙니다.",
    fields: [won("save", "월 저축액", 500000), months("months", "목표까지 전체 기간", 60), num("delay", "시작을 미루는 기간", 12, "개월", 0, 600), rate()],
    compute: ({ save, months: n, delay, rate: a }) => { if (delay > n) return invalid("지연 기간은 전체 기간 이하로 입력하세요."); const now = fv(0, save, monthly(a), n), later = fv(0, save, monthly(a), n - delay); return result("목표 날짜의 자금 차이", now - later, [R("빠지는 납입 원금", save * delay), R("가정 수익의 차이", now - later - save * delay), R("미룬 경우 최종 금액", later)]); },
    formula: "자금 차이 = 월납입×연금미래가치계수(n) − 월납입×연금미래가치계수(n−지연)",
    questions: [["목표 날짜도 함께 늦추나요?", "아니요. 두 경우의 최종 날짜는 같게 둡니다."], ["초기 예금도 비교하나요?", "여기서는 앞으로 매달 납입하는 돈만 비교합니다."], ["지연이 0이면요?", "두 계획이 같으므로 자금 차이는 0원입니다."]], relatedSlugs: ["savings-required-monthly", "savings-contribution-pause"] }),
  define({ slug: "savings-contribution-stepup", title: "매년 저축액 증액 시뮬레이션", category: "investment", source: "saving",
    intro: "월 저축액을 매년 일정 비율로 늘리는 계획의 최종 금액과 누적 납입 원금을 계산합니다. 첫해 월납입, 매년 증액률과 기간을 설정해 소득 증가에 맞춰 저축을 늘리는 계획이 고정 납입과 얼마나 다른지 비교하세요.",
    detail: "13개월째부터 첫 증액을 적용하고 이후 매 12개월마다 월납입액을 다시 늘립니다. 이자는 월말 납입 전에 발생하며 증액률과 수익률은 별개입니다. 최대 50년으로 제한하며 비현실적으로 커지는 가정은 줄여서 비교하세요.",
    fields: [won("p", "시작 자금", 0), won("save", "첫해 월 저축액", 500000), pct("step", "매년 납입 증액률", 5), num("years", "저축 기간", 10, "년", 1, 50), rate()],
    compute: ({ p, save, step, years, rate: a }) => { let extra = 0, total = p, last = save; const r = monthly(a); for (let k = 0; k < years * 12; k++) { last = save * (1 + step / 100) ** Math.floor(k / 12); extra = extra * (1 + r) + (last - save); total += last; } return result("증액 계획의 최종 금액", fv(p, save, r, years * 12) + extra, [R("누적 납입 원금", total), R("마지막 해 월 납입액", last), R("고정 납입 대비 증가", extra)]); },
    formula: "k개월 납입 = 첫 월납입×(1+연 증액률)^floor((k−1)/12); 잔액 = 전월잔액×(1+r)+납입",
    questions: [["증액은 언제 처음 적용되나요?", "처음 12개월은 같은 금액이며 13개월째부터 증액합니다."], ["증액률과 이율은 다른가요?", "증액률은 내가 넣는 돈의 증가, 이율은 잔액의 가정 수익입니다."], ["증액률 0은 무엇인가요?", "기간 동안 같은 월납입액을 유지하는 계획입니다."]], relatedSlugs: ["savings-required-monthly", "savings-rate-after-raise"] }),
  define({ slug: "savings-contribution-pause", title: "저축 일시 중단의 목표 차이", category: "investment", source: "saving",
    intro: "저축을 일정 기간 쉬어야 할 때 같은 목표 시점의 금액이 얼마나 줄어드는지 계산합니다. 중단 시작 월과 개월수를 입력하면 빠지는 납입액, 최종 자금 차이와 계속 납입했을 때의 금액을 나란히 확인할 수 있습니다.",
    detail: "납입만 중단하며 이미 계좌에 쌓인 자금은 인출하지 않고 같은 이율로 유지합니다. 중단 뒤에는 기존 월납입액으로 돌아가며 밀린 금액을 추가 납입하지 않습니다. 중단 구간이 전체 계획 안에 들어오도록 설정하세요.",
    fields: [won("p", "시작 자금", 3000000), won("save", "평소 월 저축액", 500000), months("months", "전체 계획 기간", 60), num("start", "중단 시작 월차", 13, "개월째", 1, 600), num("pause", "중단 개월수", 6, "개월", 0, 600), rate()],
    compute: ({ p, save, months: n, start, pause, rate: a }) => { if (start > n || start - 1 + pause > n) return invalid("중단 구간이 전체 계획 기간 안에 들어오도록 입력하세요."); const r = monthly(a), missed = save * factor(r, pause) * growth(r, n - (start - 1 + pause)); return result("일시 중단에 따른 자금 차이", missed, [R("중단 후 최종 금액", fv(p, save, r, n) - missed), R("쉬는 동안 미납 원금", save * pause)]); },
    formula: "잔액 = 전월잔액×(1+r) + (중단 구간이면 0, 아니면 월납입)",
    questions: [["기존 자금도 인출하나요?", "아니요. 납입만 쉬고 기존 잔액은 유지합니다."], ["중단 후 두 배씩 넣나요?", "기존 월납입액으로 복귀하며 보충 납입은 가정하지 않습니다."], ["중단 시점도 영향을 주나요?", "같은 납입액을 쉬어도 이자가 붙을 기간 차이 때문에 영향이 달라질 수 있습니다."]], relatedSlugs: ["savings-start-delay", "savings-required-monthly"] }),
  define({ slug: "savings-beginning-vs-end", title: "월초·월말 적립 시점 비교", category: "investment", source: "saving",
    intro: "매달 같은 금액을 넣더라도 월초에 넣는 경우와 월말에 넣는 경우의 최종 잔액을 비교합니다. 초기 자금과 월납입, 이율과 기간을 동일하게 두고 납입 시점만 한 달 앞당길 때 생기는 가정 이자 차이를 계산하세요.",
    detail: "월초 납입액에는 해당 월 이자가 붙고 월말 납입액에는 다음 달부터 붙는 월복리 모델입니다. 실제 적금은 납입 날짜별 일수나 단리로 계산할 수 있으므로 특정 상품의 만기 이자를 확정하는 용도로 사용하지 않습니다.",
    fields: [won("p", "이미 있는 시작 자금", 0), won("save", "매월 납입액", 500000), months("months", "비교 기간", 36), rate()],
    compute: ({ p, save, months: n, rate: a }) => { const r = monthly(a), end = fv(p, save, r, n), begin = p * growth(r, n) + save * factor(r, n) * (1 + r); return result("월초 적립의 추가 금액", save * factor(r, n) * r, [R("월초 적립 최종 금액", begin), R("월말 적립 최종 금액", end)]); },
    formula: "월초 납입 미래가치 = 월말 납입 미래가치×(1+r); 시작 자금의 성장분은 동일",
    questions: [["납입 횟수도 달라지나요?", "횟수와 원금 합계는 같고 납입 날짜만 달라집니다."], ["무이자라면요?", "납입 시점에 따른 차이는 0원입니다."], ["은행 적금도 월복리인가요?", "상품마다 다르므로 실제 약정 이자 계산 방식을 먼저 확인하세요."]], relatedSlugs: ["savings-required-monthly", "compound-interest-quick"] }),
  define({ slug: "savings-rate-after-raise", title: "월급 인상 후 저축률 계획", category: "investment",
    intro: "월급이 늘었을 때 추가 수입의 얼마를 저축에 배분할지 정하고 변화한 전체 저축률을 확인합니다. 현재 사용 가능 월급과 저축액, 인상 후 늘어나는 실제 수입을 넣어 소비 여유와 저축 증가를 동시에 계산하세요.",
    detail: "저축 배분률은 전체 월급이 아닌 새로 늘어난 월 수입에 적용합니다. 대출 원금 상환을 저축으로 포함할지는 사용자가 일관되게 정해야 하며 미래 이자나 투자 수익은 포함하지 않고 월 현금 배분만 비교합니다.",
    fields: [won("income", "현재 사용 가능 월 수입", 3000000), won("saving", "현재 월 저축액", 600000), won("raise", "인상 후 월 수입 증가", 300000), pct("share", "증가 수입의 저축 배분", 70)],
    compute: ({ income, saving, raise, share }) => income === 0 || saving > income ? invalid("현재 수입은 양수이며 저축액은 현재 수입 이하로 입력하세요.") : result("인상 후 전체 저축률", (saving + raise * share / 100) / (income + raise) * 100, [R("새 월 저축액", saving + raise * share / 100), R("추가 소비 가능액", raise * (1 - share / 100)), R("현재 저축률", saving / income * 100, "%")], undefined, "%"),
    formula: "새 저축률 = (기존 저축+월 수입 증가×증가분 저축 배분률)/(기존 수입+월 수입 증가)",
    questions: [["배분률 70%는 무엇의 비율인가요?", "전체 월급이 아니라 인상으로 새로 늘어난 월 수입 가운데 저축으로 돌리는 비율입니다. 기본값처럼 월 수입이 300,000원 늘고 배분률이 70%이면 210,000원이 저축에 더해지고 90,000원이 추가 소비 가능액이 되며, 기존 저축액 600,000원은 그대로 유지된 채 새 월 저축액이 810,000원이 됩니다."], ["세전 연봉 인상액을 넣나요?", "아니요. 세금과 4대 보험료를 뗀 뒤 실제 월 예산에 쓸 수 있는 월 수입 증가액을 넣어야 합니다. 연봉 인상액을 12로 나눈 세전 월 인상액을 넣으면 분모와 분자가 세전·세후로 섞여 저축률이 왜곡되므로, 인상 후 실수령액에서 인상 전 실수령액을 뺀 차액을 쓰는 것이 맞습니다."], ["기존 저축도 바꾸나요?", "이 계산기는 기존 월 저축액을 그대로 두고 인상분에만 배분률을 적용합니다. 인상을 계기로 기존 저축액까지 늘리거나 줄일 계획이라면 바뀐 금액을 현재 월 저축액 칸에 넣고 다시 계산하면 되고, 대출 원금 상환을 저축으로 볼지는 처음 정한 기준을 계속 유지해야 비교가 맞습니다."], ["저축률은 보통 얼마나 되나요?", "정답이 있는 비율은 아니지만 참고할 통계는 있습니다. 국가데이터처 2026년 2/4분기 가계동향조사에서 가구당 월평균 처분가능소득은 423만 5천원, 흑자액은 130만 2천원, 평균소비성향은 69.2%였습니다. 이 계산기의 저축률은 세후 수입 대비 저축액이므로 같은 기준으로 견주되, 가구원 수와 주거비에 따라 편차가 크다는 점을 감안하세요."]], relatedSlugs: ["salary-raise-timing", "savings-contribution-stepup"],
    details: "월급이 오른 뒤 늘어난 수입 중 얼마를 저축으로 돌릴지 정하면 전체 저축률이 어떻게 바뀌는지 보여 주는 계산기입니다. 연봉 인상이나 이직으로 실수령액이 늘어난 직장인이 생활비를 그대로 키우지 않고 저축 비중을 지키려 할 때 쓰며, 기본값은 월 300만원을 받아 60만원을 저축하던 사람의 월 수입이 30만원 늘고 그중 70%를 저축에 배분하는 상황입니다.\n\n기본값의 현재 저축률은 20.00%이고, 인상분 300,000원의 70%를 더한 새 월 저축액은 810,000원, 남는 추가 소비 가능액은 90,000원입니다. 새 저축액을 인상 후 수입으로 나눈 인상 후 전체 저축률은 24.55%로, 배분률이 현재 저축률보다 높으면 전체 저축률이 올라가고 그보다 낮으면 오히려 내려갑니다.\n\n비교 기준으로 국가데이터처 2026년 2/4분기 가계동향조사 결과(2026년 8월 27일 발표)를 보면 가구당 월평균 소득은 529만 5천원, 비소비지출을 뺀 처분가능소득은 423만 5천원, 소비지출은 399만 3천원, 흑자액은 130만 2천원, 평균소비성향은 69.2%였습니다. 이 계산기의 저축률은 그 통계에서 흑자액을 처분가능소득으로 나누는 것과 같은 구조로 세후 사용 가능 수입 대비 저축액의 비율이며, 금융감독원 e-금융교육센터의 금융체력 키우기 1편(2024년)은 저축 상품을 고를 때 금리만 좇지 말고 본인 상황에 맞는 상품을 고르라고 설명하므로 배분한 저축액을 어디에 둘지는 따로 정해야 합니다.\n\n세전 연봉 인상액이 아니라 실제 월 수입 증가액을 넣어야 맞고, 이자·투자수익·물가상승은 반영하지 않으며 대출 원금 상환을 저축으로 볼지는 처음부터 한 가지 기준으로 정해 두어야 합니다. 인상 적용 월에 따른 올해 총소득은 연봉 인상 적용월의 올해 소득 계산기로, 인상 후 실수령액은 연봉 실수령액 계산기로 먼저 확인한 뒤 이 계산기에 넣고, 해마다 저축액을 늘리는 계획은 매년 저축액 증액 시뮬레이션으로 이어서 보세요.",
    caveats: ["저축률 계산에 쓰는 수입은 세후 실수령 기준이므로 세전 인상액을 넣으면 저축률이 실제보다 낮게 나옵니다.", "인상분의 배분률만 바꾸는 모델이라 기존 저축액이 함께 늘거나 고정 지출이 바뀌는 경우는 새 저축액을 직접 조정해 넣어야 합니다.", "물가 상승으로 같은 생활비의 실질 부담이 커지는 효과는 저축률에 반영되지 않습니다."], individualCaveats: true,
    sources: [{ title: "국가데이터처 — 2026년 2/4분기 가계동향조사 결과(2026)", url: "https://mods.go.kr/board.es?mid=a10301040400&bid=214&act=view&list_no=446633" }, { title: "금융감독원 e-금융교육센터 — 금융체력 키우기 1편 저축은 왜 해야할까(2024)", url: "https://www.fss.or.kr/edu/fec/contMng/view.do?menuNo=300017&contentsSlno=682" }] }),
  define({ slug: "emergency-fund-target", title: "생활비 기준 비상금 부족액", category: "investment",
    intro: "매달 꼭 나가는 생활비와 대출 납입을 기준으로 원하는 개월수만큼의 비상금 목표를 계산합니다. 지금 바로 사용할 수 있는 현금을 차감해 얼마나 더 마련해야 하는지 보고 자신의 상황에 맞는 확보 기간을 설정하세요.",
    detail: "목표 개월수는 정답이나 권장 기준이 아니라 사용자가 선택하는 안전 여유입니다. 당장 인출할 수 없는 연금·보증금이나 가격이 크게 움직일 수 있는 자산은 사용 가능 현금과 구분해 넣어야 실제 부족액을 파악하기 쉽습니다.",
    fields: [won("living", "월 필수 생활비", 1800000), won("debt", "월 필수 대출 납입", 400000), months("months", "확보하고 싶은 기간", 6), won("cash", "바로 사용 가능한 현금", 5000000)],
    compute: ({ living, debt, months: n, cash }) => result("더 마련할 비상금", Math.max(0, (living + debt) * n - cash), [R("선택한 기간의 목표 비상금", (living + debt) * n), R("현재 현금의 충당 기간", living + debt > 0 ? cash / (living + debt) : 0, "개월")], living + debt === 0 ? "필수 지출이 0원이므로 목표는 0원이며 충당 기간은 정의하지 않습니다." : "선택한 기간 동안 수입이 없고 지출이 일정한 가정입니다."),
    formula: "비상금 목표 = (필수 생활비+대출 납입)×목표 개월; 추가 필요 = max(0,목표−현금)",
    questions: [["몇 개월을 골라야 하나요?", "고용 안정성, 가족 수입과 고정 지출을 고려해 직접 비교할 개월수를 정하세요."], ["대출 한도를 현금에 넣어도 되나요?", "이 도구의 현금은 이미 확보한 자금이며 새 차입 한도는 제외합니다."], ["물가 상승도 반영하나요?", "일정한 월 지출 가정이므로 장기 계획은 지출액을 올린 시나리오도 비교하세요."]], relatedSlugs: ["emergency-fund-runway", "savings-required-monthly"] }),
  define({ slug: "emergency-fund-runway", title: "현재 비상금으로 버틸 기간", category: "investment",
    intro: "일시적으로 수입이 줄었을 때 현재 현금으로 매달 부족한 생활비를 몇 개월 충당할 수 있는지 계산합니다. 지출 전체가 아니라 줄어든 뒤에도 들어오는 수입을 차감한 부족분을 기준으로 비상금 소진 속도를 확인합니다.",
    detail: "첫날 지출하는 일회성 비용을 먼저 빼고 남은 현금을 매달 동일하게 사용한다고 가정합니다. 수입이 지출 이상이면 현금이 소진되지 않는다고 안내하며, 이자·물가·예상하지 못한 지출 변화는 반영하지 않습니다.",
    fields: [won("cash", "현재 사용 가능 현금", 12000000), won("income", "감소 후 월 수입", 1000000), won("bills", "월 지출 합계", 2500000), won("once", "시작 시 일회성 지출", 0)],
    compute: ({ cash, income, bills, once }) => { if (once > cash) return invalid("시작 지출이 현재 현금을 초과합니다. 먼저 부족 자금을 마련해야 합니다."); const deficit = bills - income; return deficit <= 0 ? result("매달 남는 금액", -deficit, [R("유지되는 시작 현금", cash - once)], "입력 조건에서는 현금이 소진되지 않아 충당 기간의 상한이 없습니다.") : result("전액 충당 가능한 기간", Math.floor((cash - once) / deficit), [R("매달 부족한 금액", deficit), R("전액 충당 후 남는 현금", (cash - once) % deficit)], "한 달 부족액 전체를 충당할 수 있는 정수 개월수입니다.", "개월"); },
    formula: "기간 = 내림((현재 현금−시작 지출)/(월 지출−월 수입)); 수입≥지출이면 소진 없음",
    questions: [["수입이 조금 있어도 계산하나요?", "네. 월 지출 합계에서 감소 후에도 들어오는 월 수입을 뺀 부족분만 현금으로 충당한다고 보고 기간을 계산합니다. 기본값처럼 월 지출 2,500,000원에 수입 1,000,000원이 남아 있으면 매달 부족한 금액은 1,500,000원이고, 수입을 0원으로 넣으면 지출 전액을 현금으로 메우는 가장 보수적인 기간이 나옵니다."], ["부분 개월도 포함하나요?", "아니요. 결과는 한 달 부족액 전체를 충당할 수 있는 정수 개월수이고, 마지막에 부족액보다 적게 남는 현금은 전액 충당 후 남는 현금으로 따로 보여 줍니다. 기본값에서는 12,000,000원이 1,500,000원씩 정확히 8개월에 나뉘어 남는 현금이 0원이지만, 현금이 조금 더 있으면 그 차액이 남는 현금으로 표시됩니다."], ["지출보다 수입이 많으면요?", "감소 후 월 수입이 월 지출 이상이면 현금이 줄지 않으므로 소진 기간 대신 매달 남는 금액과 유지되는 시작 현금을 표시합니다. 이 경우에도 시작 시 일회성 지출은 현금에서 먼저 빠지며, 수입이 다시 줄어들 가능성이 있다면 수입을 낮춘 시나리오를 한 번 더 계산해 두는 것이 안전합니다."], ["비상금은 몇 개월치가 적당한가요?", "금융감독원 e-금융교육센터의 성인을 위한 실용금융 5편(2023년)은 비상예비자금으로 월평균 생활비의 3~6배를 보통예금·MMF·CMA처럼 바로 찾을 수 있는 단기 상품에 두라고 안내합니다. 고용이 불안정하거나 외벌이라면 넉넉한 쪽을, 맞벌이에 고정 지출이 적다면 적은 쪽을 기준으로 삼고, 이 계산기로 현재 현금이 그 범위에 드는지 확인하세요."]], relatedSlugs: ["emergency-fund-target", "job-transition-cash-gap"],
    details: "수입이 줄어든 동안 지금 가진 현금으로 매달 부족한 생활비를 몇 달 메울 수 있는지 계산합니다. 퇴사·휴직·비수기처럼 수입이 일부 남아 있는 상황을 전제로 하며, 기본값은 현금 1,200만원, 줄어든 월 수입 100만원, 월 지출 250만원, 시작 시 일회성 지출 0원인 경우입니다.\n\n기본값에서 매달 부족한 금액은 월 지출 2,500,000원에서 수입 1,000,000원을 뺀 1,500,000원이고, 현금 12,000,000원으로 이 부족액을 전액 충당할 수 있는 기간은 8개월, 8개월을 채운 뒤 남는 현금은 0원입니다. 시작할 때 일회성 지출을 넣으면 그 금액이 먼저 빠지고 남은 현금으로만 기간을 계산하며, 수입이 지출 이상이면 소진 기간 대신 매달 남는 금액을 보여 줍니다.\n\n금융감독원 e-금융교육센터의 성인을 위한 실용금융 5편(2023년)은 비상예비자금으로 월평균 생활비의 3~6배를 보통예금·MMF·CMA 같은 단기 상품에 두라고 안내합니다. 국가데이터처 2026년 2/4분기 가계동향조사에서 가구당 월평균 소비지출은 399만 3천원, 처분가능소득은 423만 5천원이었으므로 본인 지출이 이 평균과 얼마나 다른지에 따라 필요한 현금 규모도 달라집니다. 이 계산기는 이자·물가 변동을 넣지 않고 매달 같은 부족액이 나간다고 가정하며, 결과는 한 달 부족액 전체를 충당할 수 있는 정수 개월수입니다.\n\n비자발적 이직이라면 고용보험 구직급여가 수입에 더해질 수 있으므로 실업급여 간편 계산기로 월 환산 수급액을 구해 감소 후 월 수입에 넣어 다시 계산하고, 필요한 비상금 목표액은 생활비 기준 비상금 부족액 계산기로, 이직 사이의 급여 공백은 이직 급여 공백 준비금 계산기로 이어서 확인하세요.",
    caveats: ["월 지출 합계에는 대출 원리금과 보험료처럼 수입이 줄어도 계속 나가는 고정 지출을 빠짐없이 넣어야 기간이 과대평가되지 않습니다.", "현금은 바로 인출할 수 있는 예금 기준이며, 해지 손실이 있는 적금·보험이나 가격이 움직이는 투자자산은 현금으로 넣지 않는 편이 안전합니다.", "결과는 정수 개월이라 마지막 달의 일부 충당분은 남는 현금으로만 표시되고, 물가 상승과 예상 밖 지출은 반영되지 않습니다."], individualCaveats: true,
    sources: [{ title: "금융감독원 e-금융교육센터 — 성인을 위한 실용금융 5편, 비상예비자금과 투자위험 관리(2023)", url: "https://www.fss.or.kr/edu/fec/contMng/view.do?contentsSlno=620&menuNo=300017" }, { title: "국가데이터처 — 2026년 2/4분기 가계동향조사 결과(2026)", url: "https://mods.go.kr/board.es?mid=a10301040400&bid=214&act=view&list_no=446633" }] }),
  define({ slug: "sinking-fund-monthly", title: "연간 비정기 지출의 월 적립", category: "investment",
    intro: "매달 나가지는 않지만 정기적으로 돌아오는 지출 세 가지를 월 적립액으로 바꿉니다. 각 비용과 반복 주기를 입력해 지출일에 갑자기 목돈을 꺼내는 대신 평소 예산에서 얼마씩 떼어 둘지 계산할 수 있습니다.",
    detail: "각 항목의 다음 납부일까지도 입력한 주기가 온전히 남아 있고 현재 적립액은 없다는 가정입니다. 납부일이 더 가까우면 실제 남은 개월수로 바꾸어 계산하고, 이미 모은 돈이 있다면 해당 비용에서 먼저 차감해 입력하세요.",
    fields: [won("a", "지출 A의 회당 비용", 1200000), months("na", "지출 A의 반복 주기", 12), won("b", "지출 B의 회당 비용", 600000), months("nb", "지출 B의 반복 주기", 6), won("c", "지출 C의 회당 비용", 300000), months("nc", "지출 C의 반복 주기", 3)],
    compute: ({ a, na, b, nb, c, nc }) => result("매달 별도로 적립할 합계", a / na + b / nb + c / nc, [R("지출 A 월 적립", a / na), R("지출 B 월 적립", b / nb), R("지출 C 월 적립", c / nc)]),
    formula: "월 적립액 = 비용A/주기A + 비용B/주기B + 비용C/주기C",
    questions: [["곧 낼 비용은 주기를 어떻게 쓰나요?", "첫 목표까지 남은 실제 개월수로 바꾸어 첫 납부 준비액을 계산하세요."], ["항목이 두 개뿐이면요?", "사용하지 않는 비용을 0원으로 설정하면 됩니다."], ["적립 이자도 포함하나요?", "이자는 가정하지 않고 필요한 원금만 나누어 적립합니다."]], relatedSlugs: ["family-event-fund", "savings-required-monthly"] }),
  define({ slug: "savings-ladder-cashflow", title: "예금 사다리 만기 유동성", category: "investment", source: "saving",
    intro: "목돈을 만기가 다른 세 예금으로 나누었을 때 특정 월까지 회수할 수 있는 현금을 계산합니다. 예금별 원금·만기와 공통 가정 금리를 입력해 예정 지출일까지 만기가 오는 금액과 아직 묶인 원금을 분리해 확인하세요.",
    detail: "각 예금은 단리로 만기에 원리금을 지급하고 만기 후에는 현금으로 보유한다고 가정합니다. 자동 재예치나 중도해지는 하지 않으며 원금에 대한 이자 차감률은 사용자가 입력한 비율을 적용합니다. 특정 상품의 수익을 보장하지 않습니다.",
    fields: [won("p1", "예금 A 원금", 3000000), months("n1", "예금 A 만기", 3), won("p2", "예금 B 원금", 3000000), months("n2", "예금 B 만기", 6), won("p3", "예금 C 원금", 3000000), months("n3", "예금 C 만기", 12), months("check", "현금 필요 시점", 6), rate(), pct("tax", "이자에서 차감할 비율", 0)],
    compute: ({ p1, n1, p2, n2, p3, n3, check, rate: a, tax }) => { let available = 0, locked = 0; for (const [p, n] of [[p1, n1], [p2, n2], [p3, n3]]) { if (n <= check) available += p * (1 + a / 100 * n / 12 * (1 - tax / 100)); else locked += p; } return result("필요 시점까지 만기 회수액", available, [R("아직 만기가 안 된 원금", locked), R("처음 나눈 원금 합계", p1 + p2 + p3)]); },
    formula: "회수액 = 필요 월 이전 만기 예금들의 [원금+원금×연이율×개월/12×(1−차감률)] 합계",
    questions: [["만기 후 재예치되나요?", "계산에서는 재예치하지 않고 현금으로 남겨 둡니다."], ["만기 전 돈도 쓸 수 있지 않나요?", "중도해지 조건은 제외해 만기 도래 금액만 사용 가능으로 표시합니다."], ["예금마다 금리가 다르면요?", "이 도구는 공통 금리를 사용하므로 개별 상품 수익은 따로 계산해야 합니다."]], relatedSlugs: ["deposit-break-switch", "sinking-fund-monthly"] }),
  define({ slug: "deposit-break-switch", title: "예금 중도해지 후 갈아타기 비교", category: "investment", source: "saving",
    intro: "예금을 유지할 때 만기에 받을 실제 견적 금액과 지금 해지해 새 예금에 넣었을 때 같은 날짜에 받을 금액을 비교합니다. 금융회사가 안내한 해지 수령액을 직접 사용하므로 중도해지 이자 손실을 임의로 추정하지 않습니다.",
    detail: "새 예금은 남은 기간 동안 단리로 계산하고 이자 차감률과 이전 비용을 적용합니다. 기존 만기 수령액과 현재 해지 수령액은 모두 세후 같은 기준으로 입력해야 하며 새 상품의 우대금리 충족 여부도 확인해야 합니다.",
    fields: [won("keep", "유지 시 세후 만기 수령 견적", 10500000), won("now", "오늘 해지 시 세후 수령 견적", 10100000), months("months", "원래 만기까지 남은 기간", 6), rate("rate", "새 예금 가정 연이율", 5), pct("tax", "새 이자의 차감 비율", 0), won("fee", "별도 이전 비용", 0)],
    compute: ({ keep, now, months: n, rate: a, tax, fee }) => { const switched = now * (1 + a / 100 * n / 12 * (1 - tax / 100)) - fee; return result("갈아타기의 순금액 차이", switched - keep, [R("새 예금 예상 수령", switched), R("기존 유지 시 수령", keep)], "양수면 입력 가정에서 갈아타기 수령액이 더 크며, 음수면 유지 쪽이 더 큽니다."); },
    formula: "순차이 = 오늘 해지 수령액×[1+새 연이율×남은 개월/12×(1−차감률)]−이전 비용−유지 수령액",
    questions: [["중도해지 이자율을 넣는 건가요?", "아니요. 금융회사가 안내한 오늘의 실제 세후 해지 수령 견적을 넣습니다."], ["비교 날짜는 같나요?", "원래 예금의 만기 날짜로 두 경우를 맞춥니다."], ["새 예금 만기가 더 길면요?", "같은 날짜에 회수할 수 있는 조건이 아니므로 이 결과만으로 판단하지 마세요."]], relatedSlugs: ["savings-tax-rate-compare", "savings-ladder-cashflow"] }),
  define({ slug: "savings-tax-rate-compare", title: "세후 이자로 예금 조건 비교", category: "investment", source: "saving",
    intro: "표면 금리가 다른 두 저축 조건을 같은 원금과 기간으로 맞추고 각자의 이자 차감 비율을 적용해 비교합니다. 세후 이자와 만기 수령액을 나란히 보여 주어 금리만 비교할 때 놓치기 쉬운 실제 금액 차이를 확인하세요.",
    detail: "세법상 과세 유형을 자동 판정하지 않고 상품 안내에서 확인한 이자 차감 비율을 직접 입력합니다. 두 조건 모두 만기 지급 단리를 가정하며 수수료·금리 우대 미충족·복리 차이는 별도로 비교해야 합니다.",
    fields: [won("p", "동일 비교 원금", 10000000), months("months", "동일 저축 기간", 12), rate("a", "조건 A 연이율", 4), pct("ta", "조건 A 이자 차감률", 0), rate("b", "조건 B 연이율", 5), pct("tb", "조건 B 이자 차감률", 20)],
    compute: ({ p, months: n, a, ta, b, tb }) => { const x = p * a / 100 * n / 12 * (1 - ta / 100), y = p * b / 100 * n / 12 * (1 - tb / 100); return result("B 조건의 세후 이자 우위", y - x, [R("A 세후 이자", x), R("B 세후 이자", y), R("B 만기 수령", p + y)]); },
    formula: "각 세후 이자 = 원금×연이율×개월/12×(1−이자 차감률)",
    questions: [["차감률은 자동으로 정해 주나요?", "상품과 개인 조건에 맞게 확인한 비율을 직접 입력합니다."], ["0% 차감은 무엇인가요?", "이자에서 차감하는 금액이 없다는 가정이며 면세 자격 판정은 아닙니다."], ["적금과 예금을 비교해도 되나요?", "두 조건 모두 원금을 처음 한 번 넣는 예금 형태로 맞추어야 합니다."]], relatedSlugs: ["interest-tax-quick", "deposit-break-switch"] }),
  define({ slug: "portfolio-rebalance-amount", title: "목표 비중으로 리밸런싱 금액", category: "investment", source: "portfolio",
    intro: "이미 보유한 세 자산의 평가금액을 목표 비중과 비교해 각각 얼마를 사고팔아야 하는지 계산합니다. 새 돈을 추가하지 않고 전체 평가금액을 유지하는 조건에서 매수 필요액과 매도 필요액을 분리해 볼 수 있습니다.",
    detail: "목표 비중은 사용자가 정하며 합계가 100%여야 합니다. 매매 비용·세금·최소 주문 단위는 제외하고 평가금액만으로 계산하므로 실제 주문 수량을 결정하기 전 가격과 거래 조건을 확인해야 합니다. 특정 자산 배분을 추천하지 않습니다.",
    fields: [won("a", "자산 A 현재 평가액", 6000000), won("b", "자산 B 현재 평가액", 3000000), won("c", "자산 C 현재 평가액", 1000000), pct("ta", "자산 A 목표 비중", 50), pct("tb", "자산 B 목표 비중", 30), pct("tc", "자산 C 목표 비중", 20)],
    compute: ({ a, b, c, ta, tb, tc }) => { if (Math.abs(ta + tb + tc - 100) > 1e-6) return invalid("목표 비중의 합계를 100%로 맞추세요."); const total = a + b + c, diffs = [total * ta / 100 - a, total * tb / 100 - b, total * tc / 100 - c]; return result("필요한 총 매수 금액", diffs.reduce((sum, d) => sum + Math.max(0, d), 0), diffs.map((d, i) => R(`자산 ${"ABC"[i]} 매수(+)/매도(−)`, d)), "추가 입금 없이 매도 자금으로 매수하며 세금과 거래 비용은 제외합니다."); },
    formula: "자산별 조정액 = 전체 평가금액×목표 비중−현재 해당 자산 평가액",
    questions: [["음수 조정액은 무엇인가요?", "목표 비중보다 많이 보유해 그 금액만큼 매도하는 모델입니다."], ["비중을 추천해 주나요?", "아니요. 사용자가 정한 목표 비중으로 계산합니다."], ["세금이 생기는 매도도 같나요?", "세금과 비용을 빼면 재투자 가능한 금액이 줄어 실제 주문은 조정해야 합니다."]], relatedSlugs: ["portfolio-allocation", "investment-fee-break-even"] }),
  define({ slug: "investment-drawdown-recovery", title: "손실 회복에 필요한 수익률", category: "investment",
    intro: "투자금이 일정 비율 하락한 뒤 원래 금액으로 돌아오려면 현재 잔액 기준으로 몇 퍼센트 올라야 하는지 계산합니다. 하락률과 회복률의 기준 금액이 다르다는 점을 원금·손실 후 잔액·필요 회복액으로 확인하세요.",
    detail: "추가 입금이나 인출 없이 같은 자산이 원래 평가액으로 회복하는 상황을 가정합니다. 하락률은 100% 미만이어야 하며 회복 가능성이나 걸리는 시간을 예측하지 않습니다. 실제 거래 수수료와 세금도 포함하지 않습니다.",
    fields: [won("p", "하락 전 평가금액", 10000000), num("loss", "평가금액 하락률", 20, "%", 0, 99.99, 0.01)],
    compute: ({ p, loss }) => result("원금 회복에 필요한 상승률", loss / (100 - loss) * 100, [R("하락 후 평가금액", p * (1 - loss / 100)), R("되찾아야 할 평가금액", p * loss / 100)], "같은 원금으로 복귀하는 수학적 비율이며 회복을 보장하지 않습니다.", "%"),
    formula: "필요 회복률 = 하락률/(1−하락률)",
    questions: [["20% 하락은 20% 오르면 회복되나요?", "아닙니다. 기본값처럼 10,000,000원이 20% 떨어지면 8,000,000원이 되고, 여기서 20% 오르면 9,600,000원에 그칩니다. 되찾아야 할 2,000,000원을 하락 후 금액 8,000,000원으로 나누면 25.00%가 필요하며, 이렇게 하락률과 회복률의 기준 금액이 다르기 때문에 필요한 상승률은 항상 하락률보다 큽니다."], ["100% 하락을 넣을 수 있나요?", "넣을 수 없습니다. 하락률 입력은 99.99%까지만 허용되며, 평가금액이 0원이 되면 어떤 유한한 상승률로도 원금으로 돌아갈 수 없기 때문입니다. 하락률이 커질수록 필요한 상승률은 급격히 커져, 하락 후 잔액이 작을수록 회복은 산술적으로 훨씬 어려워집니다."], ["추가 매수하면 결과가 같나요?", "다릅니다. 이 계산은 입금과 출금 없이 같은 자산이 원래 평가액으로 돌아오는 경우만 다룹니다. 하락 후 추가 매수를 하면 투입 원금과 평균 매수단가가 바뀌어 손익 기준이 달라지고, 배당·수수료·세금이 있어도 결과가 어긋나므로 실제 계좌 손익은 주식 손익 계산으로 따로 확인해야 합니다."], ["손실 회복까지 얼마나 걸리나요?", "이 계산기는 필요한 상승률만 구하고 기간은 예측하지 않습니다. 금융감독원 e-금융교육센터의 성인을 위한 실용금융 5편(2023년)이 설명하듯 투자 결과는 수익이든 손실이든 투자자 본인에게 귀속되고 회복이 보장되지 않으므로, 상승률 25.00%라는 결과는 그만큼 오를 때까지 기다리면 된다는 뜻이 아니라 회복 조건이 그만큼 까다롭다는 뜻으로 읽어야 합니다."]], relatedSlugs: ["stock-pl-quick", "portfolio-rebalance-amount"],
    details: "투자금이 일정 비율 떨어진 뒤 원래 평가금액으로 돌아오려면 남은 잔액 기준으로 몇 % 올라야 하는지 계산합니다. 손실 중인 계좌를 보며 얼마나 올라야 본전인지 알고 싶은 개인 투자자를 위한 것이며, 기본값은 1,000만원이 20% 하락한 상황입니다.\n\n기본값에서 하락 후 평가금액은 8,000,000원, 되찾아야 할 평가금액은 2,000,000원이고, 이를 하락 후 금액 기준으로 환산한 원금 회복에 필요한 상승률은 25.00%입니다. 하락률과 회복률의 기준 금액이 다르기 때문에 필요한 상승률은 항상 하락률보다 크고, 하락률이 커질수록 그 차이는 급격히 벌어집니다.\n\n금융감독원 e-금융교육센터의 성인을 위한 실용금융 5편(2023년)은 투자 결과는 수익이든 손실이든 투자자 본인에게 귀속되며, 자산 종류와 매수 시점을 나누는 분산투자로 위험을 관리하라고 설명합니다. 금융감독원 파인의 금융꿀팁 신입사원의 금융상품 현명하게 가입하기 투자편(2024년)은 신용융자 등 레버리지 투자는 주가 하락 시 회복하기 어려운 손실을 낼 수 있으므로 소득과 자산에 맞는 투자 규모를 지키라고 안내합니다. 이 계산기의 수치는 수학적 비율일 뿐 회복 가능성이나 회복까지 걸리는 기간을 뜻하지 않습니다.\n\n추가 매수·인출·배당·수수료·세금이 있으면 기준 금액이 바뀌어 이 계산과 달라지므로, 실제 매매 손익은 주식 손익 계산으로, 자산 비중 조정은 목표 비중으로 리밸런싱 금액 계산기로 확인하세요. 회복에 필요한 상승률이 커 보이는 종목이라도 손절과 보유를 이 비율 하나로 판단하지 말고 투자 목적과 기간을 함께 따져야 합니다.",
    caveats: ["하락률 100%에 가까워질수록 필요한 상승률이 급증하며 99.99%까지만 입력할 수 있고, 잔액이 0이면 어떤 수익률로도 회복되지 않습니다.", "레버리지·신용융자 투자는 하락 시 반대매매로 잔액 자체가 줄어 같은 자산을 계속 보유한다는 이 계산의 전제가 깨질 수 있습니다.", "표시된 상승률은 수수료·세금·환율을 뺀 순수 가격 기준이며, 해외 자산은 환율 변동만으로도 필요한 회복률이 달라집니다."], individualCaveats: true,
    sources: [{ title: "금융감독원 파인 — 금융꿀팁 신입사원의 금융상품 현명하게 가입하기 투자편(2024)", url: "https://fine.fss.or.kr/fine/bbs/B0000340/view.do?nttId=136764&menuNo=900014" }, { title: "금융감독원 e-금융교육센터 — 성인을 위한 실용금융 5편, 비상예비자금과 투자위험 관리(2023)", url: "https://www.fss.or.kr/edu/fec/contMng/view.do?contentsSlno=620&menuNo=300017" }] }),
  define({ slug: "investment-fee-break-even", title: "정액·정률 투자 수수료 교차점", category: "investment", source: "fee",
    intro: "매년 고정 금액을 내는 수수료 방식과 자산의 일정 비율을 내는 방식이 같은 비용이 되는 자산 규모를 계산합니다. 현재 자산에서 두 방식의 연간 비용과 차이도 함께 보여 주어 요금 구조를 비교할 수 있습니다.",
    detail: "정액과 정률 수수료만 비교하며 두 서비스의 제공 범위가 같다는 가정입니다. 거래 수수료·성과보수·최소 수수료·구간 할인은 포함하지 않습니다. 자산이 계속 변하는 경우 평균 또는 계약상 부과 기준 자산을 입력하세요.",
    fields: [won("assets", "수수료 기준 자산", 30000000), won("fixed", "정액 방식의 연간 비용", 120000), num("percent", "정률 방식의 연간 비율", 0.5, "%", 0, 20, 0.01)],
    compute: ({ assets, fixed, percent }) => percent === 0 ? invalid("정률이 0%이면 유한한 교차 자산 규모가 없습니다. 정액도 0원이면 모든 규모에서 비용이 같습니다.") : result("두 비용이 같은 자산 규모", fixed / (percent / 100), [R("현재 자산의 정률 비용", assets * percent / 100), R("정률 대비 정액 절감", assets * percent / 100 - fixed)]),
    formula: "교차 자산 = 연 정액 수수료/연 정률; 현재 비용 차이 = 자산×정률−정액",
    questions: [["계약 수수료는 모두 포함되나요?", "정액 또는 자산 비례 비용만 다루며 별도 거래비용 등은 제외합니다."], ["교차점보다 자산이 크면요?", "같은 조건에서는 정액 비용이 정률보다 작아집니다."], ["정률이 0%면요?", "고정비와 같아지는 유한한 자산 규모가 없어 별도로 안내합니다."]], relatedSlugs: ["etf-fee-impact", "portfolio-rebalance-amount"] }),
  define({ slug: "systematic-withdrawal-runway", title: "월 정액 인출의 자금 유지 기간", category: "investment", source: "saving",
    intro: "현재 자산에서 매달 일정 금액을 꺼내 쓸 때 가정 수익률 아래에서 몇 개월 동안 전액 인출할 수 있는지 계산합니다. 월별 이자를 먼저 반영하고 월말에 인출해 계산 기간 끝의 잔액과 충당 기간을 확인하세요.",
    detail: "세금·수수료·시장 손실·인출액 증가를 제외한 일정 수익률 모델입니다. 계산 한도는 600개월이며 그때도 잔액이 남으면 한도 내에서 유지된다고 표시합니다. 마지막에 월 인출액을 전부 채우지 못하는 달은 전액 가능 개월에 포함하지 않습니다.",
    fields: [won("p", "현재 인출용 자산", 12000000), won("withdraw", "매달 인출할 금액", 1000000), rate("rate", "가정 연수익률", 0), months("months", "확인할 최대 기간", 120)],
    compute: ({ p, withdraw, rate: a, months: n }) => { if (withdraw === 0) return invalid("월 인출액을 0원보다 크게 입력하세요. 인출하지 않으면 이 모델에서 자산은 소진되지 않습니다."); let b = p, count = 0; for (let k = 0; k < n; k++) { b *= 1 + monthly(a); if (b + 0.005 < withdraw) break; b = Math.max(0, b - withdraw); count++; } return result("전액 인출 가능한 개월", count, [R("마지막 계산 시점 잔액", b), R("완료한 정액 인출 합계", count * withdraw)], count === n ? "확인한 기간 내에서 인출을 유지했습니다. 이후 기간의 지속을 보장하지 않습니다." : "다음 달에는 예정한 인출액 전부를 충당하지 못합니다.", "개월"); },
    formula: "매월 가용액 = 이전 잔액×(1+월 수익률); 가용액≥인출액인 달만 인출 후 개월 누적",
    questions: [["시장 하락도 계산하나요?", "이 도구는 고정된 비음수 수익률만 가정합니다. 실제 투자 위험은 별개입니다."], ["마지막 일부 인출은 포함하나요?", "아니요. 월 목표액 전부를 충당한 개월만 셉니다."], ["600개월 후에도 남으면 무기한인가요?", "아닙니다. 지정한 한도 안에서 유지됐다는 의미입니다."]], relatedSlugs: ["emergency-fund-runway", "fire-target"] }),
];

const FAMILY: CalculatorDef[] = [
  define({ slug: "couple-expense-income-split", title: "부부 소득 비례 생활비 분담", category: "family",
    intro: "두 사람의 사용 가능 월 수입에 비례해 공동 생활비를 나누고 각자 남는 돈을 계산합니다. 소득이 다른 부부나 동거 가족이 같은 금액을 내는 방식과 비교하기 전에 생활비 부담 비중을 구체적으로 확인할 수 있습니다.",
    detail: "공동 생활비는 두 사람이 함께 부담하기로 합의한 항목만 포함합니다. 소득 비례가 반드시 공정한 정답이라는 의미는 아니며 돌봄·가사 기여나 개인 부채 등은 별도 합의가 필요합니다. 한 사람의 수입이 0이면 다른 사람에게 전액 배분됩니다.",
    fields: [won("a", "A의 사용 가능 월 수입", 3000000), won("b", "B의 사용 가능 월 수입", 2000000), won("cost", "공동 월 생활비", 2500000)],
    compute: ({ a, b, cost }) => a + b === 0 ? invalid("소득 비례 분담에는 두 사람의 합산 수입이 0원보다 커야 합니다.") : result("A의 월 분담액", cost * a / (a + b), [R("B의 월 분담액", cost * b / (a + b)), R("A의 분담 후 잔액", a - cost * a / (a + b)), R("B의 분담 후 잔액", b - cost * b / (a + b))], cost > a + b ? "공동 생활비가 합산 수입보다 큽니다. 계산된 분담액은 현재 수입으로 충당되지 않습니다." : "소득 비례 배분 모델이며 실제 분담은 두 사람의 합의로 정하세요."),
    formula: "A 분담 = 공동 생활비×A 수입/(A 수입+B 수입); B도 동일 방식",
    questions: [["개인 지출도 공동 생활비인가요?", "함께 내기로 합의한 항목만 포함하고 개인 지출은 분리하세요."], ["한 사람이 무소득이면요?", "수입이 있는 사람에게 공동 생활비 전액이 배분되는 단순 모델입니다."], ["공정한 분담액을 확정하나요?", "아닙니다. 가사·돌봄·개인 사정은 별도로 논의해야 합니다."]], relatedSlugs: ["shared-goal-contribution", "single-income-transition-budget"] }),
  define({ slug: "parental-leave-household-gap", title: "육아휴직 가계 부족자금", category: "family",
    intro: "육아휴직 중 실제로 예상하는 가구 수입과 지출을 비교해 매달 부족한 금액과 휴직 기간 전체의 준비금을 계산합니다. 지급기관이 안내한 급여액을 직접 넣기 때문에 가족별로 다른 수령 조건과 회사 지원을 함께 반영할 수 있습니다.",
    detail: "월 휴직 수입은 일정하다고 가정하며 배우자 등 다른 가구 수입과 구분해 입력합니다. 실제 급여가 기간별로 달라지면 각 구간을 따로 계산해 합산하세요. 법정 육아휴직급여나 신청 자격을 자동으로 판단하는 계산기는 아닙니다.",
    fields: [won("leave", "매달 확정·예상 휴직 수입", 1800000), won("other", "다른 가구 월 수입", 2000000), won("bills", "휴직 중 월 지출", 4000000), months("months", "해당 수입이 유지되는 기간", 6), won("cash", "별도 휴직 준비금", 500000)],
    compute: ({ leave, other, bills, months: n, cash }) => { const gap = Math.max(0, bills - leave - other); return result("추가로 마련할 휴직 준비금", Math.max(0, gap * n - cash), [R("매달 부족 금액", gap), R("기간 전체 부족 금액", gap * n), R("매달 가계 수입", leave + other)]); },
    formula: "기간 부족액 = max(0,월 지출−휴직 수입−다른 수입)×개월; 추가 준비 = max(0,부족액−준비금)",
    questions: [["육아휴직급여는 자동 계산되나요?", "아니요. 지급 조건을 확인한 월 수입을 직접 입력합니다."], ["휴직급여가 중간에 바뀌면요?", "금액이 같은 구간별로 나누어 계산한 부족액을 합산하세요."], ["수입이 지출보다 많으면요?", "해당 기간 추가 준비금은 0원이며 남는 돈은 부족액에 누적하지 않습니다."]], relatedSlugs: ["unpaid-leave-budget", "childcare-work-return"] }),
  define({ slug: "childcare-work-return", title: "복직 후 보육비 차감 순수입", category: "family",
    intro: "복직으로 늘어나는 월 수입에서 새 보육비와 통근비, 줄어드는 지원금 등을 빼고 실제 가계에 추가되는 금액을 계산합니다. 보육 서비스를 이용하며 다시 일할 때 월급 전액이 여유 자금이 되는지 확인하는 데 쓰세요.",
    detail: "보육비에는 기존에도 내던 금액을 제외한 복직으로 인한 추가 비용만 넣습니다. 감소 지원금 역시 복직 때문에 실제로 줄어드는 금액만 입력하며, 장기적인 경력 효과와 연금·보험 변화는 이 단순 현금 비교에 포함하지 않습니다.",
    fields: [won("income", "복직으로 증가하는 월 수입", 2500000), won("care", "추가 월 보육비", 700000), won("commute", "추가 월 통근·식비", 200000), won("lost", "복직으로 감소하는 월 지원", 300000), won("setup", "복직 준비 일회성 비용", 500000)],
    compute: ({ income, care, commute, lost, setup }) => { const net = income - care - commute - lost; return result("복직 후 매달 추가되는 돈", net, [R("첫해 추가 현금 합계", net * 12 - setup), R("매달 추가 비용·지원 감소", care + commute + lost)]); },
    formula: "월 순증가 = 복직 추가 수입−추가 보육비−통근·식비−감소 지원금",
    questions: [["보육비 전체를 입력하나요?", "기존 지출과 비교해 복직 때문에 늘어나는 부분만 넣으세요."], ["지원금 감소를 예측해 주나요?", "해당 기관에서 확인한 감소액을 직접 입력합니다."], ["순수입만으로 복직을 결정해야 하나요?", "아닙니다. 시간·돌봄·경력 등 금액 외 조건도 함께 고려할 수 있습니다."]], relatedSlugs: ["parental-leave-household-gap", "commute-adjusted-offer"] }),
  define({ slug: "education-savings-gap", title: "교육비 물가 반영 준비 저축", category: "family", source: "saving",
    intro: "현재 기준의 연간 교육비에 매년 비용 증가를 적용하고 교육 시작 전까지 필요한 월 저축액을 계산합니다. 교육이 시작되는 시점뿐 아니라 전체 교육 기간의 비용을 미리 확보하는 계획으로 현재 저축과의 차이를 확인하세요.",
    detail: "교육 기간 동안의 비용은 각 연도 물가로 올리되 교육 시작 때 모두 현금으로 준비하며 이후 운용 수익은 없다고 가정합니다. 교육비 증가율과 저축 수익률은 사용자가 정하는 가정이며 특정 학교의 등록금이나 투자 성과 예측이 아닙니다.",
    fields: [won("cost", "현재 기준 연간 교육비", 5000000), num("until", "교육 시작까지 기간", 5, "년", 1, 30), num("duration", "준비할 교육 기간", 4, "년", 1, 10), num("inflation", "교육비 연 증가 가정", 3, "%", 0, 20, 0.1), won("p", "현재 교육 준비금", 5000000), rate("rate", "시작 전 저축 연수익률", 3)],
    compute: ({ cost, until, duration, inflation, p, rate: a }) => { let goal = 0; for (let k = 0; k < duration; k++) goal += cost * (1 + inflation / 100) ** (until + k); return result("교육 시작 전 필요한 월 저축", needMonthly(goal, p, monthly(a), until * 12), [R("교육 시작 때 확보할 목표", goal), R("물가 변화 없는 비용 합계", cost * duration)]); },
    formula: "목표 = Σ 현재 연 교육비×(1+증가율)^(시작까지 연수+교육 연차); 목표를 월 적립 공식으로 역산",
    questions: [["교육 중에도 투자하는 가정인가요?", "아니요. 시작 전에 모두 확보하고 교육 중 추가 수익은 가정하지 않습니다."], ["입학 첫해 비용만 올리나요?", "교육 기간의 각 연도까지 비용 증가를 따로 적용합니다."], ["현재 준비금이 충분하면요?", "가정한 성장만으로 목표에 도달하면 추가 월납입은 0원입니다."]], relatedSlugs: ["education-cost-cumulative", "savings-required-monthly"] }),
  define({ slug: "eldercare-family-budget", title: "가족 돌봄 실비 월 예산", category: "family",
    intro: "돌봄 서비스 이용일수와 실제 하루 비용, 고정 부대비를 합산하고 확정 지원액을 차감해 가족의 월 부담을 계산합니다. 서비스 견적과 가족이 마련한 현금을 기준으로 일정 기간 동안 얼마나 더 준비해야 하는지 확인하세요.",
    detail: "돌봄 비용이나 지원 자격을 추정하지 않고 견적서와 지급 안내에 있는 금액을 그대로 사용합니다. 일수는 매달 동일하다고 가정하며 입원·휴일 할증·교통비 등 변동 비용은 포함 여부를 확인한 뒤 고정비에 따로 반영하세요.",
    fields: [won("daily", "확인한 하루 돌봄 비용", 80000), num("days", "월 이용 예정일", 20, "일", 0, 31), won("fixed", "월 고정 부대비", 200000), won("support", "확정 월 지원액", 600000), months("months", "준비할 기간", 6), won("cash", "기존 돌봄 준비금", 2000000)],
    compute: ({ daily, days, fixed, support, months: n, cash }) => { const cost = Math.max(0, daily * days + fixed - support); return result("추가로 준비할 돌봄 자금", Math.max(0, cost * n - cash), [R("월 가족 부담", cost), R("지원 전 월 비용", daily * days + fixed)]); },
    formula: "월 부담 = max(0,하루 비용×이용일+고정비−확정 지원); 준비금 부족 = max(0,월 부담×기간−보유금)",
    questions: [["정부 지원액을 자동 계산하나요?", "아니요. 자격과 지급액을 확인한 지원만 입력합니다."], ["월 이용일이 달라지면요?", "일정이 비슷한 월별로 나눠 계산하거나 실제 평균 일수를 사용하세요."], ["지원액이 비용보다 많으면요?", "가족 부담은 0원으로 표시하며 초과 지원액을 수익으로 계산하지 않습니다."]], relatedSlugs: ["family-medical-budget", "emergency-fund-target"] }),
  define({ slug: "family-medical-budget", title: "가족 의료비 본인부담 예산", category: "family",
    intro: "예정된 진료비·약제비와 확인된 보험 지급액, 확정 지원금 및 미리 모은 돈을 비교해 추가 현금 준비액을 계산합니다. 치료 내용이나 적정 비용을 판단하지 않고 실제 견적과 지급 확인 자료로 가계 예산을 정리하는 도구입니다.",
    detail: "보험 지급이나 지원은 입금이 확인되었거나 해당 지출에 대해 확정된 금액만 넣으세요. 아직 심사 중인 금액은 별도 시나리오로 비교할 수 있습니다. 세액공제와 실손 약관, 의료적 필요성은 자동 판단하지 않습니다.",
    fields: [won("bill", "예정 진료·약제비 합계", 3000000), won("insurance", "확인한 보험 수령액", 1000000), won("support", "확정 외부 지원액", 500000), won("cash", "별도 의료비 준비금", 500000)],
    compute: ({ bill, insurance, support, cash }) => result("추가로 준비할 현금", Math.max(0, bill - insurance - support - cash), [R("보험·지원 차감 후 부담", Math.max(0, bill - insurance - support)), R("확보 자금 합계", insurance + support + cash)], "지급 시점이 지출보다 늦다면 그 사이 필요한 선지출 자금은 별도로 확보하세요."),
    formula: "추가 준비 = max(0,예정 의료비−확인 보험금−확정 지원금−기존 준비금)",
    questions: [["예상 보험금도 넣어도 되나요?", "확정 전 금액을 넣으면 부족액이 작아 보일 수 있으므로 구분해 비교하세요."], ["세액공제가 차감되나요?", "아니요. 이 계산은 해당 지출을 낼 현금 준비만 다룹니다."], ["보험금이 나중에 들어오면요?", "지출 시점의 선지급 자금이 더 필요할 수 있습니다."]], relatedSlugs: ["medical-expense-coverage", "emergency-fund-runway"] }),
  define({ slug: "allowance-growth-plan", title: "자녀 용돈 증액·저축 계획", category: "family",
    intro: "자녀에게 주는 월 용돈을 매년 일정 비율로 늘릴 때 가족의 누적 지출과 자녀가 따로 모을 원금을 계산합니다. 첫해 월 용돈, 증액률과 저축 비율을 정해 마지막 해 월 용돈까지 미리 확인할 수 있습니다.",
    detail: "처음 12개월 이후 매년 같은 비율로 증액하며 용돈의 일정 비율을 저축한다고 가정합니다. 이자와 투자 수익, 일시적 선물은 포함하지 않습니다. 연령별 적정 용돈을 추천하는 기능이 아니라 가족이 합의한 계획을 계산합니다.",
    fields: [won("allowance", "첫해 월 용돈", 50000), pct("increase", "매년 용돈 증액률", 10), num("years", "계획 기간", 5, "년", 1, 20), pct("save", "용돈 중 저축 비율", 30)],
    compute: ({ allowance, increase, years, save }) => { let total = 0, last = allowance; for (let y = 0; y < years; y++) { last = allowance * (1 + increase / 100) ** y; total += last * 12; } return result("기간 전체 용돈 합계", total, [R("자녀가 모으는 원금", total * save / 100), R("마지막 해 월 용돈", last), R("용돈 중 사용 가능한 합계", total * (1 - save / 100))]); },
    formula: "총 용돈 = Σ 첫해 월 용돈×(1+증액률)^연차×12; 저축 원금 = 총 용돈×저축 비율",
    questions: [["아이 나이에 맞는 권장액인가요?", "아닙니다. 가족이 정한 첫 용돈과 증액률을 사용하는 계획입니다."], ["모은 돈의 이자가 포함되나요?", "납입 원금만 계산하고 이자는 제외합니다."], ["저축 비율 100%이면요?", "받은 용돈 전액을 모으며 사용할 용돈 합계는 0원이 됩니다."]], relatedSlugs: ["education-savings-gap", "savings-contribution-stepup"] }),
  define({ slug: "family-event-fund", title: "가족 행사 부족자금 월 적립", category: "family",
    intro: "가족 행사를 준비하며 확인한 비용에 직접 정한 예비비를 더하고 이미 모은 돈과 확정 분담금을 차감합니다. 행사까지 남은 개월 동안 얼마나 적립해야 하는지 계산해 행사비 지출이 평소 생활비와 섞이지 않도록 계획하세요.",
    detail: "축의금이나 선물처럼 아직 들어올지 모르는 돈은 확정 분담금에 포함하지 않는 편이 계획을 명확하게 합니다. 예비비 비율은 사용자가 정하며 이자나 행사 비용의 물가 변화는 가정하지 않습니다. 인원별 단가를 추정하지 않고 총 견적을 사용합니다.",
    fields: [won("cost", "확인한 행사 비용 합계", 5000000), pct("buffer", "별도로 잡을 예비비", 10), won("saved", "이미 모은 행사 자금", 1000000), won("shared", "확정된 가족 분담금", 1000000), months("months", "행사까지 남은 기간", 6)],
    compute: ({ cost, buffer, saved, shared, months: n }) => { const target = cost * (1 + buffer / 100), gap = Math.max(0, target - saved - shared); return result("매달 모을 행사 자금", gap / n, [R("예비비 포함 목표", target), R("현재 부족 자금", gap)]); },
    formula: "월 적립 = max(0,견적×(1+예비비율)−보유금−확정 분담금)/남은 개월",
    questions: [["예상 축의금도 넣나요?", "확정되지 않은 돈은 별도로 구분해 보수적인 조건과 함께 비교하세요."], ["예비비는 정해진 비율인가요?", "고정 기준이 아니라 사용자가 선택하는 추가 예산입니다."], ["이미 목표를 모았다면요?", "추가 부족금과 월 적립액은 0원으로 표시합니다."]], relatedSlugs: ["wedding-cost-quick", "sinking-fund-monthly"] }),
  define({ slug: "shared-goal-contribution", title: "가구 여유자금별 공동 저축 분담", category: "family",
    intro: "두 사람이 각자 필수 지출을 내고 남는 여유 자금에 비례해 공동 목표 저축액을 나눕니다. 단순 소득 비례와 달리 개인별 고정 부담을 먼저 반영하므로 공동 저축을 시작한 뒤 각자 쓸 수 있는 돈도 확인할 수 있습니다.",
    detail: "개인 필수 지출에는 공동 생활비에서 이미 낸 자기 몫도 포함해 중복되지 않도록 정리하세요. 목표 저축액이 두 사람의 여유 자금 합계보다 크면 현재 조건에서 부족한 금액을 안내합니다. 이 계산은 분담 합의를 대신하지 않습니다.",
    fields: [won("a", "A 월 수입", 3000000), won("ac", "A 필수 지출 합계", 2000000), won("b", "B 월 수입", 2000000), won("bc", "B 필수 지출 합계", 1500000), won("goal", "공동 월 저축 목표", 900000)],
    compute: ({ a, ac, b, bc, goal }) => { const x = Math.max(0, a - ac), y = Math.max(0, b - bc); if (x + y === 0) return invalid("두 사람의 필수 지출 후 여유 자금이 없습니다."); if (goal > x + y) return result("월 목표 저축의 부족액", goal - x - y, [R("A의 최대 가능액", x), R("B의 최대 가능액", y)], "현재 여유 자금으로 목표를 채울 수 없습니다. 목표나 지출을 조정하세요."); const aa = goal * x / (x + y), bb = goal - aa; return result("A의 공동 월 저축액", aa, [R("B의 공동 월 저축액", bb), R("A에게 남는 여유", x - aa), R("B에게 남는 여유", y - bb)]); },
    formula: "개인 여유 = max(0,수입−필수 지출); A 분담 = 공동 목표×A 여유/합산 여유",
    questions: [["소득 비례 생활비와 무엇이 다른가요?", "필수 개인 지출을 먼저 빼고 실제 여유 자금에 비례해 저축을 배분합니다."], ["목표가 여유 합계보다 크면요?", "분담액 대신 부족액과 각자의 최대 가능액을 표시합니다."], ["공동 생활비를 또 넣어도 되나요?", "개인 필수 지출에 이미 포함된 비용은 한 번만 반영하세요."]], relatedSlugs: ["couple-expense-income-split", "savings-required-monthly"] }),
  define({ slug: "single-income-transition-budget", title: "외벌이 전환 후 가계 여유", category: "family",
    intro: "맞벌이에서 한 사람의 수입이 사라질 때 줄어드는 출근 관련 비용과 새로 생기는 비용을 함께 반영합니다. 유지되는 수입만으로 월 지출과 목표 저축을 채울 수 있는지, 기존 가계 여유와 얼마나 차이 나는지 확인하세요.",
    detail: "그만두는 사람의 소득은 전액 없어지고 다른 가구 수입은 유지된다고 가정합니다. 출근 비용 절감에는 실제 사라지는 금액만 넣고 새 돌봄·생활 비용은 별도로 입력합니다. 지원금과 고용·보험 변동은 확인한 금액을 수입이나 지출에 직접 반영하세요.",
    fields: [won("stay", "계속 유지되는 월 수입", 3500000), won("leave", "사라지는 월 수입", 2500000), won("bills", "현재 가구 월 지출", 4000000), won("savedCost", "전환 후 줄어드는 월 비용", 500000), won("newCost", "전환 후 추가 월 비용", 200000), won("saving", "유지할 월 목표 저축", 500000)],
    compute: ({ stay, leave, bills, savedCost, newCost, saving }) => { if (savedCost > bills) return invalid("줄어드는 비용은 현재 가구 지출 이하로 입력하세요."); const next = bills - savedCost + newCost, after = stay - next - saving; return result("전환 후 저축까지 뺀 월 여유", after, [R("변경 후 월 지출", next), R("기존 대비 월 여유 변화", after - (stay + leave - bills - saving)), R("현재 조건의 월 부족액", Math.max(0, -after))]); },
    formula: "새 월 여유 = 유지 수입−(기존 지출−사라지는 비용+추가 비용)−목표 저축",
    questions: [["퇴직금으로 매달 부족을 메우나요?", "이 도구는 월 수입·지출 구조만 보며 보유 자금 소진은 별도 도구에서 비교합니다."], ["출근비 절감은 전체 교통비인가요?", "전환 후 실제로 없어지는 비용만 넣으세요."], ["목표 저축을 0으로 두면요?", "저축 없이 생활비만 충당했을 때의 월 여유를 계산합니다."]], relatedSlugs: ["emergency-fund-runway", "couple-expense-income-split"] }),
  define({ slug: "family-insurance-premium-share", title: "가족 보험료의 수입 비중", category: "family",
    intro: "가족 구성원의 월납 보험료와 별도로 내는 연납 보험료를 합쳐 월평균 부담과 가구 수입 대비 비중을 계산합니다. 보장 금액을 추정하는 대신 실제 납입 내역을 모아 고정 지출의 크기를 확인하는 예산 도구입니다.",
    detail: "연납 항목은 12로 나누어 월평균으로 표시하므로 실제 결제월의 현금 지출은 다릅니다. 보험의 적정성이나 해지 여부를 추천하지 않으며 저축성 보험의 만기 환급금, 보장 공백 및 계약 변경 비용은 별도로 확인해야 합니다.",
    fields: [won("a", "가족 A 월납 보험료 합계", 150000), won("b", "가족 B 월납 보험료 합계", 120000), won("annual", "가구 연납 보험료 합계", 1200000), won("income", "가구 사용 가능 월 수입", 5000000)],
    compute: ({ a, b, annual, income }) => income === 0 ? invalid("보험료 비중을 계산할 가구 월 수입은 0원보다 커야 합니다.") : result("수입 대비 보험료 비중", (a + b + annual / 12) / income * 100, [R("보험료 월평균 부담", a + b + annual / 12), R("전체 연간 납입 합계", (a + b) * 12 + annual)], "비중만 계산하며 적정 비율이나 상품 해지를 권고하지 않습니다.", "%"),
    formula: "월평균 보험료 = 월납 합계+연납 합계/12; 수입 비중 = 월평균 보험료/가구 월 수입",
    questions: [["몇 퍼센트가 적정한가요?", "이 계산은 적정 비율을 정하지 않고 실제 가계 부담을 보여 줍니다."], ["연납도 매달 지출인가요?", "월평균 비교를 위해 나누어 표시하며 실제 결제월에는 목돈이 나갑니다."], ["비중이 높으면 해지해야 하나요?", "이 결과만으로 결정하지 말고 보장·환급·재가입 조건을 따로 확인하세요."]], relatedSlugs: ["sinking-fund-monthly", "family-medical-budget"] }),
];

export const expandedFinanceCalculators: CalculatorDef[] = [...LOANS, ...SALARY, ...SAVINGS, ...FAMILY];
