import type { CalculatorDef, CalculatorField, CalculatorResult } from "./types";

// Scenario estimates: no live prices, statutory rates, medical judgments or tax rules.
// Field bounds keep arithmetic finite; invalid inputs remain visibly invalid, not a zero quote.
type Row = [label: string, value: number, suffix?: string];
type Spec = Omit<CalculatorDef, "categoryLabel" | "explanation" | "faqs" | "publishedAt"> & {
  guidance: string;
  questions: [string, string][];
  integerFields?: string[];
};
const labels: Partial<Record<CalculatorDef["category"], string>> = {
  business: "사업 운영", "real-estate": "주거·부동산", life: "생활 비용", currency: "환전·해외 결제",
};
const source = {
  breakeven: { title: "미국 SBA — 고정비·변동비와 손익분기점", url: "https://legacy.sba.gov/business-guide/plan-your-business/calculate-your-startup-costs/break-even-point" },
  inventory: { title: "OpenStax — 재고회전과 평균재고", url: "https://openstax.org/books/principles-financial-accounting/pages/10-5-examine-the-efficiency-of-inventory-management-using-financial-ratios" },
  workingCapital: { title: "ACCA — 현금전환주기와 운전자본", url: "https://www.accaglobal.com/gb/en/student/exam-support-resources/fundamentals-exams-study-resources/f9/technical-articles/wcm.html" },
  eoq: { title: "UMPSA 공개강의 — 재고관리와 경제적 발주량", url: "https://ocw.ump.edu.my/pluginfile.php/2468/mod_resource/content/1/Chap%207%20inventory%20management.pdf" },
  energy: { title: "Virginia Tech — 소비전력으로 전력 사용량 계산", url: "https://ext.vt.edu/content/pubs_ext_vt_edu/en/2901/2901-9014/2901-9014.html" },
  transfer: { title: "CFPB — 해외송금의 환율·수수료·수취액 확인", url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-remittance-transfer-and-what-are-my-rights-en-1161/" },
};
const money = (name: string, label: string, defaultValue: number, hint = "같은 기간의 원화 금액을 입력하세요. 세금 포함 기준을 통일합니다."): CalculatorField =>
  ({ name, label, defaultValue, suffix: "원", min: 0, max: 1e12, step: 100, hint });
const unitMoney = (name: string, label: string, defaultValue: number, suffix: string, hint: string): CalculatorField =>
  ({ ...money(name, label, defaultValue, hint), suffix, step: 0.01 });
const number = (name: string, label: string, defaultValue: number, suffix: string, max = 1e6, hint = "계산에 사용할 수량이나 기간입니다. 0 이상으로 입력하세요.", step = 1): CalculatorField =>
  ({ name, label, defaultValue, suffix, min: 0, max, step, hint });
const percent = (name: string, label: string, defaultValue: number, hint = "계약서·견적 또는 직접 정한 가정의 비율입니다. 0~100% 범위입니다."): CalculatorField =>
  ({ name, label, defaultValue, suffix: "%", min: 0, max: 100, step: 0.1, hint });
const rate = (name: string, label: string, defaultValue: number): CalculatorField =>
  number(name, label, defaultValue, "원/외화 1단위", 1e7, "조회한 실제 적용환율을 입력하세요. 100단위 고시 환율은 100으로 나눕니다.", 0.01);
// Decimal quantities such as 2.1 / 0.3 must not buy an eighth unit because
// IEEE-754 evaluates the quotient as 7.000000000000001. Snap only roundoff.
const snapInteger = (value: number) => {
  const nearest = Math.round(value);
  if (nearest === 0) return value;
  return Math.abs(value - nearest) <= Number.EPSILON * Math.max(1, Math.abs(value)) * 8 ? nearest : value;
};
const ceilUnits = (value: number) => Math.ceil(snapInteger(value));
const floorUnits = (value: number) => Math.floor(snapInteger(value));
const positiveDifference = (left: number, right: number) => {
  const difference = left - right;
  return difference > Number.EPSILON * Math.max(1, Math.abs(left), Math.abs(right)) * 8 ? difference : 0;
};
const invalid = (note: string): CalculatorResult => ({ status: "invalid", primary: { label: "계산 조건 확인", value: 0, suffix: "" }, note });
const out = (label: string, value: number, suffix = "원", rows: Row[] = [], note = "입력한 조건에 따른 예상값입니다. 실제 청구·정산 자료와 대조하세요."): CalculatorResult => ({
  primary: { label, value, suffix }, secondary: rows.map(([label, value, suffix = "원"]) => ({ label, value, suffix })), note,
});
function define(spec: Spec): CalculatorDef {
  const { guidance, questions, compute, integerFields = [], ...rest } = spec;
  const description = `${spec.description} 입력값은 예시이므로 실제 견적과 같은 기간·단위로 바꿔 비교하세요.`;
  return {
    ...rest, description, categoryLabel: labels[spec.category]!, publishedAt: "2026-09-10",
    fields: spec.fields.map(field => integerFields.includes(field.name)
      ? { ...field, hint: `${field.hint ?? ""} 인원·건수는 정수로 입력하세요.` } : field),
    explanation: `${description}\n\n${guidance}`,
    faqs: questions.map(([q, a]) => ({ q, a })),
    caveats: [...(spec.caveats ?? []), "기본 입력값은 시장 평균이나 추천값이 아닌 계산 예시입니다."],
    compute(inputs) {
      for (const field of spec.fields) {
        const value = inputs[field.name];
        if (!Number.isFinite(value) || value < (field.min ?? 0) || value > (field.max ?? 1e12)) {
          return invalid(`${field.label}을(를) ${field.min ?? 0}~${field.max ?? 1e12}${field.suffix ?? ""} 범위의 유한한 숫자로 입력하세요.`);
        }
        if (integerFields.includes(field.name) && !Number.isInteger(value)) {
          return invalid(`${field.label}은(는) 정수로 입력하세요. 인원·건수를 소수로 나누어 계산하지 않습니다.`);
        }
      }
      const result = compute(inputs);
      return [result.primary, ...(result.secondary ?? [])].every(row => Number.isFinite(row.value))
        ? result : invalid("계산 가능한 범위를 벗어났습니다. 단가·수량·기간과 분모가 되는 입력값을 확인하세요.");
    },
  };
}

export const expandedPracticalCalculators: CalculatorDef[] = [
  define({
    slug: "operating-cashflow-plan", title: "영업현금흐름 운영예산 계산기", category: "business",
    description: "매출 장부가 아닌 실제 입금과 지급 예정액으로 한 달 운영현금 증감을 계산합니다. 재료비·인건비·임차료를 나누어 입력하고 월초 잔액으로 월말 자금 부족 여부까지 확인합니다.",
    guidance: "외상매출은 이번 달 들어올 부분만 입금에 넣고, 외상매입도 실제 결제 예정액만 지출에 넣습니다. 설비 매입이나 차입금 상환은 영업비용과 성격이 다르므로 이 계산에 섞기보다 별도 자금표로 관리하세요.",
    keywords: ["영업현금흐름", "운영예산", "월말 잔액"],
    fields: [money("opening", "월초 현금 잔액", 20000000), money("receipts", "이번 달 영업 입금", 30000000), money("suppliers", "재료·거래처 지급", 12000000), money("wages", "인건비 지급", 8000000), money("rent", "임차료 지급", 2000000), money("other", "기타 영업 현금지출", 3000000)],
    compute: v => { const paid = v.suppliers + v.wages + v.rent + v.other; const flow = v.receipts - paid; return out("월말 운영현금", v.opening + flow, "원", [["영업현금 증감", flow], ["영업 지급 합계", paid]], v.opening + flow < 0 ? "월말 잔액이 음수입니다. 입금 시점 조정이나 별도 자금 조달을 검토할 금액입니다." : "현금 기준 예상표이며 회계상 영업이익·현금흐름표를 대신하지 않습니다."); },
    formula: "영업현금 증감 = 실제 입금 − 영업 지급 합계; 월말 현금 = 월초 현금 + 증감",
    questions: [["미수 매출도 입금에 넣나요?", "이번 기간에 실제 받을 것으로 예상하는 금액만 넣습니다."], ["감가상각비는 어디에 넣나요?", "현금이 나가지 않는 감가상각비는 넣지 않습니다."], ["잔액이 플러스면 흑자인가요?", "현금 잔액과 회계이익은 다릅니다. 미수·미지급과 자산 거래도 따로 확인합니다."]],
    caveats: ["투자·재무 현금흐름, 지급일별 일시 부족과 세금 납기 계산은 포함하지 않습니다."], relatedSlugs: ["business-cashflow-runway", "cash-conversion-cycle"],
  }),
  define({
    slug: "inventory-turnover-days", title: "재고회전율·평균 보유일수 계산기", category: "business",
    description: "기간 매출원가와 기초·기말 재고 원가를 연결해 재고가 몇 번 순환했는지 확인합니다. 분석 일수를 직접 지정하여 연간뿐 아니라 분기·월간 재고 보유기간도 같은 기준으로 비교합니다.",
    guidance: "재고는 판매가가 아니라 매출원가와 일관된 원가로 입력합니다. 기초·기말 단순평균은 기간 중 큰 재고 변동을 놓칠 수 있으므로 행사나 계절성이 큰 사업은 월별 자료도 함께 확인하세요.",
    keywords: ["재고회전율", "재고보유일수", "평균재고"], sources: [source.inventory],
    fields: [money("cogs", "기간 매출원가", 120000000), money("opening", "기초 재고 원가", 10000000), money("closing", "기말 재고 원가", 20000000), number("days", "분석 기간", 365, "일", 3660)],
    compute: v => { const average = (v.opening + v.closing) / 2; if (!average || !v.cogs || !v.days) return invalid("평균재고·매출원가·분석 일수가 모두 0보다 커야 회전과 보유기간을 함께 계산할 수 있습니다."); return out("평균 재고 보유기간", v.days * average / v.cogs, "일", [["재고회전율", v.cogs / average, "회"], ["평균 재고 원가", average]]); },
    formula: "평균재고 = (기초 + 기말) ÷ 2; 회전율 = 매출원가 ÷ 평균재고; 보유일수 = 분석 일수 ÷ 회전율",
    questions: [["매출액을 입력해도 되나요?", "판매가에는 마진이 포함되므로 매출원가를 사용해야 재고 원가와 비교됩니다."], ["재고가 0이면 어떻게 되나요?", "분모가 없어 회전율을 정의할 수 없다는 안내를 표시합니다."], ["보유일수가 짧을수록 좋나요?", "재고 부족 위험도 있으므로 업종·납기·품절 기록과 함께 해석합니다."]],
    caveats: ["평균 보유기간이며 개별 품목의 실제 보관일을 추적하지 않습니다."], relatedSlugs: ["stock-reorder-point", "inventory-order-quantity"],
  }),
  define({
    slug: "cash-conversion-cycle", title: "현금전환주기·운전자금 계산기", category: "business",
    description: "재고 보유기간과 매출채권 회수기간에서 매입대금 지급 유예기간을 빼 현금이 묶이는 시간을 봅니다. 하루 현금지출 가정을 더해 영업 사이클에 필요한 운영자금 규모를 비교합니다.",
    guidance: "세 기간은 같은 회계기간과 같은 사업 범위에서 산출한 값으로 맞춥니다. 현금전환주기가 음수이면 고객 입금이 공급자 지급보다 먼저인 구조일 수 있으며, 필요자금을 음수로 표시하지 않고 기간의 음수 자체를 보존합니다.",
    keywords: ["현금전환주기", "운전자금", "매출채권 회수"], sources: [source.workingCapital],
    fields: [number("inventoryDays", "재고 보유기간", 40, "일", 3660), number("receivableDays", "외상대금 회수기간", 30, "일", 3660), number("payableDays", "매입대금 지급기간", 25, "일", 3660), money("dailyCash", "하루 운영 현금지출", 500000)],
    compute: v => { const cycle = v.inventoryDays + v.receivableDays - v.payableDays; return out("현금전환주기", cycle, "일", [["주기 대응 운영자금", Math.max(0, cycle) * v.dailyCash]], cycle < 0 ? "음수 주기입니다. 현금이 먼저 회수되는 가정이며 비상자금이 필요 없다는 뜻은 아닙니다." : "주기 동안 지출이 일정하다는 단순 운영자금 추정입니다."); },
    formula: "현금전환주기 = 재고일수 + 회수일수 − 지급일수; 운영자금 = max(주기, 0) × 하루 지출",
    questions: [["주기가 음수여도 되나요?", "선결제 판매 등에서는 가능합니다. 기간은 음수 그대로 보여줍니다."], ["하루 지출은 매출액인가요?", "매출액이 아니라 유지에 필요한 실제 현금 지급액입니다."], ["이 금액만 보유하면 되나요?", "계절성과 예기치 않은 지급은 포함되지 않으므로 별도 여유자금이 필요할 수 있습니다."]],
    caveats: ["여신 한도나 적정 대출액 판정이 아닙니다."], relatedSlugs: ["operating-cashflow-plan", "inventory-turnover-days"],
  }),
  define({
    slug: "advertising-profit-roas", title: "광고 공헌이익·손익분기 ROAS 계산기", category: "business",
    description: "광고로 발생한 매출에서 광고 전 공헌이익률과 광고비를 반영하여 캠페인의 손익을 봅니다. 매출 대비 광고효율만 보지 않고 변동원가를 부담한 뒤 남는 금액과 필요한 매출을 확인합니다.",
    guidance: "공헌이익률에는 상품 원가·배송·결제수수료 등 매출에 따라 늘어나는 비용을 먼저 반영합니다. 플랫폼별 전환 집계가 중복되거나 반품이 발생하면 광고 귀속 매출을 조정해야 하며, 고정비 배부 전의 이익이라는 점을 구분하세요.",
    keywords: ["손익분기 ROAS", "광고 공헌이익", "광고비 손익"], sources: [source.breakeven],
    fields: [money("spend", "광고비", 1000000), money("revenue", "광고 귀속 순매출", 4000000), percent("margin", "광고 전 공헌이익률", 35)],
    compute: v => { if (!v.spend || !v.margin) return invalid("광고비와 광고 전 공헌이익률이 0보다 커야 ROAS와 손익분기점을 계산할 수 있습니다."); return out("광고비 차감 공헌이익", v.revenue * v.margin / 100 - v.spend, "원", [["매출 ROAS", v.revenue / v.spend * 100, "%"], ["손익분기 ROAS", 10000 / v.margin, "%"], ["손익분기 순매출", v.spend * 100 / v.margin]]); },
    formula: "광고 공헌이익 = 순매출 × 공헌이익률 − 광고비; 손익분기 ROAS(%) = 10000 ÷ 공헌이익률(%)",
    questions: [["ROAS가 100%면 본전인가요?", "상품 원가가 있으므로 보통 공헌이익률을 반영한 더 높은 ROAS가 필요합니다."], ["광고 전 마진에 광고비도 넣나요?", "광고비는 별도로 차감하므로 공헌이익률에 중복 반영하지 않습니다."], ["이 결과가 순이익인가요?", "임차료 등 고정비와 세금 차감 전 캠페인 공헌이익입니다."]],
    caveats: ["광고 귀속 정확도나 향후 매출을 보장하지 않습니다."], relatedSlugs: ["customer-acquisition-payback", "online-order-profit"],
  }),
  define({
    slug: "customer-acquisition-payback", title: "고객획득비 회수기간 계산기", category: "business",
    integerFields: ["customers"],
    description: "캠페인 지출과 신규 유료고객 수로 고객 한 명을 확보하는 비용을 구합니다. 고객당 월 매출에서 서비스 변동비를 뺀 공헌이익으로 획득비를 회수하는 데 걸리는 기간을 계산합니다.",
    guidance: "문의나 무료가입 대신 실제 유료 전환 고객 수를 입력합니다. 고객이 매달 같은 공헌이익을 낸다는 가정이므로 해지나 휴면이 많은 서비스는 이 기간 동안 고객이 유지되는지도 별도로 확인해야 합니다.",
    keywords: ["고객획득비", "CAC 회수", "유료고객 비용"],
    fields: [money("campaign", "고객획득 지출 합계", 6000000), number("customers", "신규 유료고객", 120, "명"), money("revenue", "고객당 월 매출", 30000), money("cost", "고객당 월 변동비", 10000)],
    compute: v => { if (!v.customers || v.revenue <= v.cost) return invalid("유료고객이 1명 이상이고 월 매출이 월 변동비보다 커야 회수기간이 존재합니다."); const cac = v.campaign / v.customers; return out("획득비 회수기간", cac / (v.revenue - v.cost), "개월", [["고객 1명 획득비", cac], ["고객당 월 공헌이익", v.revenue - v.cost]]); },
    formula: "CAC = 획득 지출 ÷ 유료고객 수; 회수개월 = CAC ÷ (월 매출 − 월 변동비)",
    questions: [["가입자 수를 써도 되나요?", "유료고객 회수기간이므로 무료회원은 제외합니다."], ["해지율은 반영되나요?", "반영하지 않습니다. 산출된 기간보다 실제 유지기간이 짧을 수 있습니다."], ["광고비가 0이면요?", "획득비와 회수기간은 0이지만 인력 등 누락된 획득비가 있는지 확인합니다."]],
    caveats: ["LTV 추정이나 고객 유지율 예측은 포함하지 않습니다."], relatedSlugs: ["advertising-profit-roas", "business-margin-quick"],
  }),
  define({
    slug: "online-order-profit", title: "온라인 주문 건별 공헌이익 계산기", category: "business",
    integerFields: ["quantity"],
    description: "주문 한 건에 여러 상품이 담겼을 때 판매대금에서 상품원가·결제수수료·포장비·배송 부담을 차감합니다. 주문수만 늘어나는 상황에서 실제로 얼마가 남는지 단가별로 비교합니다.",
    guidance: "배송비는 판매자가 최종 부담하는 금액을 입력하고, 고객이 별도로 낸 배송비가 있다면 이를 상계하세요. 수수료는 상품 판매대금을 기준으로 적용하며 광고비·반품비·고정비는 이 주문 모델에 자동 포함되지 않습니다.",
    keywords: ["주문 손익", "쇼핑몰 공헌이익", "배송비 마진"],
    fields: [money("price", "상품 판매단가", 30000), number("quantity", "주문당 상품 수", 2, "개"), money("cost", "상품 원가 단가", 15000), percent("fee", "상품대금 수수료율", 5), money("packing", "주문당 포장비", 1000), money("shipping", "주문당 판매자 배송 부담", 3000)],
    compute: v => { if (!v.quantity) return invalid("주문에 포함된 상품 수를 0보다 크게 입력하세요."); const revenue = v.price * v.quantity; const fee = revenue * v.fee / 100; return out("주문 1건 공헌이익", revenue - v.cost * v.quantity - fee - v.packing - v.shipping, "원", [["주문 상품대금", revenue], ["판매 수수료", fee], ["변동비 합계", v.cost * v.quantity + fee + v.packing + v.shipping]]); },
    formula: "주문 공헌이익 = 단가 × 수량 × (1 − 수수료율) − 원가 × 수량 − 포장비 − 배송 부담",
    questions: [["배송비는 상품 수만큼 곱하나요?", "한 주문 단위 배송비이므로 한 번만 차감합니다."], ["광고비는 포함되나요?", "포함하지 않습니다. 주문당 광고비가 있으면 결과에서 별도 차감하세요."], ["음수가 나오는 이유는요?", "그 주문의 변동비가 판매대금보다 크다는 의미입니다."]],
    caveats: ["수수료에 세금·배송비가 포함되는 계약은 입력 기준을 조정해야 합니다."], relatedSlugs: ["break-even-order-count", "product-return-cost"],
  }),
  define({
    slug: "break-even-order-count", title: "월 고정비 손익분기 주문수 계산기", category: "business",
    integerFields: ["orders"],
    description: "월 고정비를 주문 한 건에서 남는 공헌이익으로 나누어 손익분기 주문수를 계산합니다. 상품 판매가와 주문별 변동비를 구분하고 정수 주문수 및 목표 주문수에서의 예상 영업손익을 확인합니다.",
    guidance: "변동비에는 주문이 하나 늘어날 때 추가되는 원가·결제·포장·배송 비용을 넣습니다. 임대료와 기본 인건비처럼 주문수와 무관한 비용은 고정비로 모으고, 손익분기 주문수는 부족하지 않도록 올림합니다.",
    keywords: ["손익분기 주문수", "고정비 회수", "BEP"], sources: [source.breakeven],
    fields: [money("fixed", "월 고정비", 3000000), money("price", "주문당 매출", 40000), money("variable", "주문당 변동비", 25000), number("orders", "예상 월 주문수", 250, "건")],
    compute: v => { const contribution = v.price - v.variable; if (contribution <= 0) return invalid("주문당 매출이 변동비보다 커야 고정비를 회수할 수 있습니다."); return out("손익분기 주문수", ceilUnits(v.fixed / contribution), "건", [["주문당 공헌이익", contribution], ["예상 주문수에서 손익", v.orders * contribution - v.fixed]]); },
    formula: "손익분기 주문수 = 올림(고정비 ÷ (주문 매출 − 변동비)); 영업손익 = 주문수 × 공헌이익 − 고정비",
    questions: [["왜 소수점 주문을 올리나요?", "주문을 쪼개어 받을 수 없으므로 고정비를 모두 회수하는 최소 정수 건수를 표시합니다."], ["인건비는 어디에 넣나요?", "매월 일정한 급여는 고정비, 주문마다 추가되는 작업비는 변동비로 구분합니다."], ["손익분기 이후 매출은 전부 이익인가요?", "추가 주문에도 변동비가 발생하므로 공헌이익 부분만 남습니다."]],
    caveats: ["물량 증가에 따른 단계별 인력·설비 증설 비용은 별도 반영해야 합니다."], relatedSlugs: ["online-order-profit", "wholesale-price-target"],
  }),
  define({
    slug: "wholesale-price-target", title: "목표마진 도매 견적단가 계산기", category: "business",
    integerFields: ["quantity"],
    description: "생산원가와 납품 포장비, 한 번에 발생하는 주문 준비비를 바탕으로 필요한 견적단가를 역산합니다. 매출 기준 목표마진과 판매 수수료를 분리해 원가 가산율과 혼동하지 않고 가격을 정리합니다.",
    guidance: "목표마진은 판매가에서 남기려는 비율이며 원가에 몇 퍼센트를 더하는 가산율과 다릅니다. 주문 준비비는 납품 수량으로 나누어 단가에 배분하고, 동일한 세금 포함 기준으로 원가와 견적을 비교하세요.",
    keywords: ["도매 견적", "목표마진 가격", "판매단가 역산"],
    fields: [money("cost", "개당 생산원가", 10000), money("packing", "개당 포장비", 1000), money("setup", "주문 준비비 합계", 100000), number("quantity", "납품 수량", 100, "개"), percent("margin", "판매가 대비 목표마진", 20), percent("fee", "판매가 대비 수수료", 5)],
    compute: v => { if (!v.quantity || v.margin + v.fee >= 100) return invalid("납품 수량은 0보다 크고 목표마진과 수수료 합계는 100% 미만이어야 합니다."); const unit = v.cost + v.packing + v.setup / v.quantity; const price = unit / (1 - (v.margin + v.fee) / 100); return out("목표 견적단가", ceilUnits(price), "원", [["준비비 포함 원가 단가", unit], ["올림 견적 총액", ceilUnits(price) * v.quantity]]); },
    formula: "견적단가 = (생산원가 + 포장비 + 준비비 ÷ 수량) ÷ (1 − 목표마진율 − 수수료율), 원 단위 올림",
    questions: [["원가에 20%를 더하면 마진 20%인가요?", "아닙니다. 이 계산기는 매출에서 차지하는 이익 비율을 사용합니다."], ["수량을 늘리면 왜 단가가 내려가나요?", "고정된 주문 준비비가 더 많은 수량에 나누어지기 때문입니다."], ["마진과 수수료 합이 100%면요?", "원가를 충당할 몫이 없어 유한한 견적단가를 구할 수 없습니다."]],
    caveats: ["시장 판매 가능 가격이나 적정마진을 추천하는 계산이 아닙니다."], relatedSlugs: ["business-margin-quick", "discount-volume-target"],
  }),
  define({
    slug: "discount-volume-target", title: "할인 후 이익 유지 판매량 계산기", category: "business",
    integerFields: ["quantity"],
    description: "현재 단가와 변동원가로 얻는 공헌이익을 할인 판매에서도 유지하려면 몇 개를 더 팔아야 하는지 계산합니다. 할인율만큼 판매량을 늘리면 된다는 착각을 줄이고 필요한 증량을 확인합니다.",
    guidance: "할인 전후 상품 원가와 주문 처리비가 동일하다는 가정입니다. 할인 행사로 광고비나 물류 고정비가 늘면 추가 비용이 생기므로 이 결과보다 더 많은 판매가 필요할 수 있으며, 판매 가능성 자체를 예측하지는 않습니다.",
    keywords: ["할인 판매량", "할인 손익", "이익 유지 수량"],
    fields: [money("price", "기존 판매단가", 20000), money("cost", "개당 변동비", 12000), number("quantity", "기존 판매수량", 100, "개"), percent("discount", "할인율", 10)],
    compute: v => { const price = v.price * (1 - v.discount / 100); if (v.price <= v.cost || price <= v.cost) return invalid("할인 전후 판매가가 모두 변동비보다 커야 같은 양의 공헌이익을 유지하는 수량을 구할 수 있습니다."); const required = ceilUnits(v.quantity * (v.price - v.cost) / (price - v.cost)); return out("필요 할인 판매수량", required, "개", [["추가 판매수량", required - v.quantity, "개"], ["할인 판매단가", price], ["기존 총 공헌이익", v.quantity * (v.price - v.cost)]]); },
    formula: "필요수량 = 올림(기존 수량 × (기존 단가 − 변동비) ÷ (할인 단가 − 변동비))",
    questions: [["할인율이 0이면요?", "기존 수량과 같은 공헌이익이므로 기존 수량을 그대로 유지합니다."], ["할인가가 원가 이하라면요?", "판매를 늘려도 양의 공헌이익을 회복할 수 없어 계산 조건 안내를 표시합니다."], ["고정비는 반영되나요?", "전후 고정비가 같다고 가정하며 행사 추가비용은 따로 검토합니다."]],
    caveats: ["할인에 따른 수요 증가율은 예측하지 않습니다."], relatedSlugs: ["wholesale-price-target", "break-even-order-count"],
  }),
  define({
    slug: "product-return-cost", title: "상품 반품 처리비용 계산기", category: "business",
    integerFields: ["orders"],
    description: "판매 건수와 예상 반품률을 입력하여 회수 배송·검수·폐기 손실의 운영비를 추정합니다. 환불되는 판매대금과 반품 처리비를 구분해 반품이 주문당 수익성에 미치는 부담을 확인합니다.",
    guidance: "폐기 손실률은 반품된 상품 중 원가를 회수하지 못하는 비중입니다. 재판매 가능한 반품은 원가 전액을 다시 손실로 잡지 않으며, 역배송비와 처리비는 반품 한 건당 평균 실제 비용으로 입력합니다.",
    keywords: ["반품비용", "쇼핑몰 반품률", "반품 폐기 손실"],
    fields: [number("orders", "판매 건수", 1000, "건"), percent("returns", "예상 반품률", 5), money("shipping", "반품당 회수 배송비", 3000), money("handling", "반품당 검수·처리비", 2000), money("cost", "상품 원가", 20000), percent("loss", "반품 중 원가 손실률", 10)],
    compute: v => { const count = v.orders * v.returns / 100; const unit = v.shipping + v.handling + v.cost * v.loss / 100; return out("예상 반품 처리부담", count * unit, "원", [["기대 반품 건수", count, "건"], ["반품 1건 평균 부담", unit], ["전체 주문 1건당 부담", v.orders ? count * unit / v.orders : 0]], "건수의 소수점은 통계적 기대값입니다. 고객에게 돌려주는 매출 환불액은 별도입니다."); },
    formula: "반품 부담 = 판매 건수 × 반품률 × (회수비 + 처리비 + 상품 원가 × 손실률)",
    questions: [["환불액도 반품비용에 포함되나요?", "매출 환입과 중복 계산하지 않도록 환불 판매대금은 제외합니다."], ["반품률이 0이면요?", "예상 반품 처리부담은 0입니다."], ["반품 건수가 소수점인 이유는요?", "예산 수립용 기대 건수이며 실제 반품 개수를 단정하지 않습니다."]],
    caveats: ["재판매 할인, 최초 배송비 환불, 플랫폼 반품 수수료는 입력 비용에 별도로 반영하세요."], relatedSlugs: ["online-order-profit", "advertising-profit-roas"],
  }),
  define({
    slug: "invoice-early-payment", title: "조기결제 할인과 자금비용 비교 계산기", category: "business",
    description: "거래처가 대금을 일찍 지급하는 대신 요구하는 할인액을 자금 조달 비용과 비교합니다. 당겨 받는 일수와 회사가 직접 입력한 연 자금비용률로 조기 입금 선택의 비용 차이를 정리합니다.",
    guidance: "비교 기준은 할인 후 지금 받을 수 있는 현금입니다. 같은 금액을 정상 결제일까지 차입한다고 가정한 단리 비용과 포기하는 할인액을 비교하며, 연환산 비율은 반복 거래나 복리 수익률 예측이 아닙니다.",
    keywords: ["조기결제 할인", "매출채권 할인", "자금비용 비교"],
    fields: [money("invoice", "정상 청구금액", 10000000), percent("discount", "조기결제 할인율", 2), number("days", "입금이 빨라지는 기간", 30, "일", 3660), percent("funding", "비교 연 자금비용률", 8)],
    compute: v => { const discount = v.invoice * v.discount / 100; const cash = v.invoice - discount; if (!cash || !v.days) return invalid("할인 후 수취액과 당겨 받는 일수가 0보다 커야 자금비용을 비교할 수 있습니다."); const funding = cash * v.funding / 100 * v.days / 365; return out("조기할인의 추가 비용", discount - funding, "원", [["포기하는 할인액", discount], ["비교 단리 자금비용", funding], ["할인비용 단순 연환산", discount / cash * 365 / v.days * 100, "%"]], "양수는 조기할인이 비교 자금조달보다 비싼 가정, 음수는 더 저렴한 가정입니다."); },
    formula: "추가비용 = 청구액 × 할인율 − 할인후 수취액 × 연 자금비용률 × 당겨 받는 일수 ÷ 365",
    questions: [["연환산 비율이 큰 이유는요?", "짧은 기간의 할인비용을 365일 기준으로 단순 환산하기 때문입니다."], ["결제 위험도 반영하나요?", "거래처 부도 위험이나 채권 추심비는 포함하지 않습니다."], ["결제일이 같으면요?", "당겨 받는 기간이 없어 자금비용 비교가 성립하지 않습니다."]],
    caveats: ["실제 대출 계약의 일수 기준과 수수료는 다를 수 있습니다."], relatedSlugs: ["cash-conversion-cycle", "receivables-aging-loss"],
  }),
  define({
    slug: "receivables-aging-loss", title: "미수금 구간별 회수손실 시나리오", category: "business",
    description: "기한 내 채권과 연체 채권에 각각 예상 손실률을 적용해 미수금 회수 가능액을 계산합니다. 채권 총액만 보고 운영자금을 계획하기보다 회수 불확실성을 분리한 시나리오를 만들 수 있습니다.",
    guidance: "손실률은 업종 평균을 자동 적용하지 않으므로 거래처별 회수 기록과 담당자의 가정을 넣습니다. 여기서 구한 손실 예상액은 회계기준에 따른 대손충당금이나 세법상 손금 인정액과 동일하지 않습니다.",
    keywords: ["미수금 손실", "연체채권 회수", "채권 회수 시나리오"],
    fields: [money("current", "기한 내 미수금", 20000000), percent("currentLoss", "기한 내 예상 손실률", 1), money("overdue", "연체 미수금", 5000000), percent("overdueLoss", "연체 예상 손실률", 20)],
    compute: v => { const loss = v.current * v.currentLoss / 100 + v.overdue * v.overdueLoss / 100; return out("예상 회수 가능액", v.current + v.overdue - loss, "원", [["손실 예상액", loss], ["미수금 합계", v.current + v.overdue]]); },
    formula: "예상 회수액 = 기한 내 채권 × (1 − 손실률) + 연체채권 × (1 − 손실률)",
    questions: [["기본 손실률은 공식 기준인가요?", "아닙니다. 사용법을 보여주는 예시이며 직접 정해야 합니다."], ["손실률 100%는 무엇인가요?", "그 구간의 채권을 전혀 회수하지 못하는 시나리오입니다."], ["회수 시점도 계산하나요?", "금액만 계산합니다. 입금 시점은 별도 현금계획에 반영하세요."]],
    caveats: ["회계상 충당금 산정이나 세무 신고 용도로 확정 사용할 수 없습니다."], relatedSlugs: ["operating-cashflow-plan", "invoice-early-payment"],
  }),
  define({
    slug: "stock-reorder-point", title: "재주문 시점·재고 여유 계산기", category: "business",
    description: "하루 판매량과 납품 리드타임, 직접 정한 안전재고로 발주해야 할 재고 수준을 계산합니다. 현재고가 그 기준보다 얼마나 남았는지와 판매가 일정할 때 기준에 도달하기까지의 시간을 확인합니다.",
    guidance: "현재고에는 사용 가능한 수량만 입력하며 이미 주문한 입고 예정분을 반영하려면 다른 재고와 중복되지 않도록 조정합니다. 안전재고는 자동 통계 추정이 아니므로 수요와 납기 변동을 보고 사용자가 직접 결정하세요.",
    keywords: ["재주문 시점", "안전재고", "리드타임 재고"],
    fields: [number("daily", "하루 평균 출고", 20, "개/일"), number("lead", "납품 소요기간", 7, "일", 3660), number("safety", "추가 안전재고", 50, "개"), number("stock", "현재 사용 가능 재고", 250, "개")],
    compute: v => { const point = v.daily * v.lead + v.safety; return out("재주문 기준 재고", point, "개", [["기준 대비 재고 여유", v.stock - point, "개"], ...(v.daily > 0 ? [["기준 도달까지", Math.max(0, (v.stock - point) / v.daily), "일"]] as Row[] : [])], v.daily === 0 ? "출고가 0이라 기준 도달 시점은 계산하지 않습니다." : v.stock <= point ? "현재고가 재주문 기준 이하입니다. 미입고 주문과 실제 납기를 확인하세요." : "하루 출고량과 납기가 일정한 경우의 기준입니다."); },
    formula: "재주문 기준 = 하루 출고 × 납품 일수 + 안전재고; 도달일 = max(현재고 − 기준, 0) ÷ 하루 출고",
    questions: [["안전재고가 자동 추천되나요?", "아닙니다. 운영자가 직접 정한 수량을 입력합니다."], ["이미 발주한 물량은요?", "실제 도착 가능한 물량을 고려해 현재고 기준을 조정하세요."], ["판매량이 0이면요?", "재주문 기준은 안전재고가 되고 도달일은 표시하지 않습니다."]],
    caveats: ["계절 변동·불량·운송 지연을 확률적으로 예측하지 않습니다."], relatedSlugs: ["inventory-order-quantity", "inventory-turnover-days"],
  }),
  define({
    slug: "inventory-order-quantity", title: "경제적 발주량 EOQ 계산기", category: "business",
    description: "연간 수요와 한 번 발주할 때 드는 고정 비용, 상품 한 개를 일 년 보관하는 비용으로 경제적 발주량을 계산합니다. 주문을 자주 하는 비용과 재고를 많이 보관하는 비용의 균형을 확인합니다.",
    guidance: "수요가 일정하고 주문하면 재고가 한 번에 보충되는 기본 EOQ 모델입니다. 개당 보관비에는 창고·보험·손실 등의 연간 금액을 넣고, 결과는 연속 수량의 이론값이므로 실제 발주는 포장단위와 최소주문량에 맞추어 비교하세요.",
    keywords: ["EOQ", "경제적 발주량", "재고 주문량"], sources: [source.eoq],
    fields: [number("demand", "연간 수요", 12000, "개/년", 1e9), money("orderCost", "1회 발주 고정비", 50000), money("holding", "개당 연간 보관비", 3000)],
    compute: v => { if (!v.demand) return out("이론 경제적 발주량", 0, "개", [["연 발주·보관 비용", 0]], "연간 수요가 없으므로 발주할 필요가 없는 가정입니다."); if (!v.orderCost || !v.holding) return invalid("발주 고정비와 개당 연간 보관비가 모두 0보다 커야 유한한 EOQ를 구할 수 있습니다."); const q = Math.sqrt(2 * v.demand * v.orderCost / v.holding); return out("이론 경제적 발주량", q, "개", [["연간 이론 발주 횟수", v.demand / q, "회"], ["연 발주·보관 비용", v.demand / q * v.orderCost + q / 2 * v.holding]], "구매 원가 총액은 수량과 무관한 항목으로 비용 비교에서 제외합니다. 실제 발주는 정수·포장단위를 검토하세요."); },
    formula: "EOQ = √(2 × 연간수요 × 1회 발주비 ÷ 개당 연간보관비); 관련비용 = 수요 ÷ EOQ × 발주비 + EOQ ÷ 2 × 보관비",
    questions: [["왜 상품 매입가는 입력하지 않나요?", "개당 매입가가 수량에 따라 변하지 않으면 최적 주문량 계산에서 상쇄됩니다."], ["수량 할인이 있으면요?", "기본 EOQ에 포함되지 않으므로 할인구간별 총비용을 별도 비교해야 합니다."], ["보관비가 0이면요?", "유한한 최적 균형점이 없어 계산 조건 안내를 표시합니다."]],
    caveats: ["품절·납기 변동·수량할인·창고 최대용량은 포함하지 않습니다."], relatedSlugs: ["stock-reorder-point", "inventory-turnover-days"],
  }),
  define({
    slug: "marketplace-settlement", title: "마켓 판매대금 정산 예상액 계산기", category: "business",
    description: "판매대금에서 취소·환불을 빼고 순판매액에 적용되는 수수료와 정산 공제액을 반영합니다. 주문 발생 매출과 통장에 입금되는 정산금의 차이를 같은 기간 기준으로 확인할 수 있습니다.",
    guidance: "수수료는 취소가 반영된 순판매액을 기준으로 계산하는 단순 계약을 가정합니다. 플랫폼이 배송료에도 수수료를 매기거나 환불 수수료를 돌려주지 않는다면 별도 공제에 넣고, 보류금은 비용이 아닌 미수 정산금으로 구분하세요.",
    keywords: ["마켓 정산금", "판매대금 정산", "정산 보류금"],
    fields: [money("sales", "정산 대상 판매대금", 15000000), money("refund", "취소·환불 대금", 1000000), percent("fee", "순판매액 수수료율", 8), money("deduction", "기타 정산 공제", 200000), money("hold", "이번 정산 보류액", 500000)],
    compute: v => { if (v.refund > v.sales) return invalid("취소·환불 대금은 이 계산에 입력한 판매대금을 넘을 수 없습니다. 과거 판매 환불은 별도 공제에 반영하세요."); const net = v.sales - v.refund; const fee = net * v.fee / 100; return out("이번 예상 입금액", net - fee - v.deduction - v.hold, "원", [["취소 반영 순판매액", net], ["판매 수수료", fee], ["추후 확인할 보류액", v.hold]], "입금액이 음수이면 추가 공제·차기 이월이 필요한 가정입니다. 플랫폼 정산 방식과 대조하세요."); },
    formula: "입금액 = (판매대금 − 취소환불) × (1 − 수수료율) − 기타 공제 − 보류액",
    questions: [["보류액도 손실인가요?", "반드시 손실은 아닙니다. 추후 정산 가능 여부를 별도 확인합니다."], ["원가는 왜 빼지 않나요?", "이 계산은 정산 입금액을 구하며 사업 이익을 구하는 계산은 아닙니다."], ["이전 달 환불은 어떻게 넣나요?", "이번 판매대금 범위 밖의 환불은 기타 공제로 구분할 수 있습니다."]],
    caveats: ["정산 주기·수수료 환급·세금계산서 처리 규칙은 자동 적용하지 않습니다."], relatedSlugs: ["online-order-profit", "operating-cashflow-plan"],
  }),
  define({
    slug: "meeting-cost", title: "회의 시간·참석 인건비 계산기", category: "business",
    integerFields: ["people", "meetings"],
    description: "회의 참석자 수와 평균 시간당 비용에 회의·개인 준비시간을 반영해 사용한 인력 자원을 금액으로 봅니다. 한 번의 회의와 월 반복 회의의 비용을 나누어 운영 방식 변경을 검토합니다.",
    guidance: "시간당 비용은 회사가 직접 정한 급여·간접비 기준으로 입력하고 참석자별 차이가 크면 가중평균을 사용합니다. 준비시간은 참석자 한 명당 시간이며, 이 금액은 회의를 줄이면 곧바로 절약되는 현금이 아니라 투입 자원 추정입니다.",
    keywords: ["회의 비용", "회의 인건비", "업무시간 비용"],
    fields: [number("people", "참석자 수", 6, "명", 10000), money("hourly", "평균 시간당 인력비", 30000), number("minutes", "회의 시간", 60, "분", 1440), number("preparation", "1인당 준비시간", 15, "분", 1440), number("meetings", "월 회의 횟수", 4, "회", 1000)],
    compute: v => { const hours = v.people * (v.minutes + v.preparation) / 60; const cost = hours * v.hourly; return out("월 회의 자원비용", cost * v.meetings, "원", [["1회 비용", cost], ["1회 총 인력시간", hours, "인·시간"]], "투입시간의 평가액입니다. 생산성 손실이나 실제 감축 가능한 현금비용을 확정하지 않습니다."); },
    formula: "1회 비용 = 참석자 × (회의분 + 1인 준비분) ÷ 60 × 시간당 비용; 월 비용 = 1회 비용 × 횟수",
    questions: [["회의 준비시간도 모든 참석자에게 적용되나요?", "입력한 준비시간을 각 참석자에게 동일하게 적용합니다."], ["회의실 임대료도 포함되나요?", "인력비만 계산하며 시설·장비 비용은 별도입니다."], ["회의를 없애면 전액 절약되나요?", "고정 급여는 그대로일 수 있으므로 자원 재배치 관점에서 해석하세요."]],
    caveats: ["회의의 의사결정 가치나 결과 품질은 금액으로 평가하지 않습니다."], relatedSlugs: ["project-budget-variance", "hourly-billing-rate"],
  }),
  define({
    slug: "project-budget-variance", title: "프로젝트 완료예산·초과액 계산기", category: "business",
    description: "현재까지 실제 사용한 비용과 남은 업무의 새 견적을 합쳐 완료 시점 총예산을 계산합니다. 최초 승인예산과 비교하여 남은 예산, 예상 초과액, 예산 소진율을 함께 확인할 수 있습니다.",
    guidance: "남은 업무비에는 아직 지급하지 않았지만 확정된 발주와 추가 작업비를 포함합니다. 이미 사용한 비용과 중복되지 않도록 구분하며, 진행률로 남은 비용을 자동 추정하지 않고 현장의 최신 견적을 직접 사용합니다.",
    keywords: ["프로젝트 예산", "예산 초과", "완료예상비용"],
    fields: [money("budget", "승인 총예산", 30000000), money("actual", "현재까지 실제비용", 18000000), money("remaining", "남은 업무 예상비용", 15000000)],
    compute: v => { const total = v.actual + v.remaining; return out("완료 시 예상 예산 초과액", total - v.budget, "원", [["완료 예상 총비용", total], ["현재 남은 승인예산", v.budget - v.actual], ...(v.budget ? [["현재 예산 소진율", v.actual / v.budget * 100, "%"]] as Row[] : [])], v.budget ? "양수는 예상 초과, 음수는 승인예산 내 잔여 여유입니다." : "승인예산이 0이라 소진율은 표시하지 않습니다. 예상비용 전액이 미확보 예산입니다."); },
    formula: "완료예상비용 = 실제비용 + 남은업무비; 초과액 = 완료예상비용 − 승인예산",
    questions: [["초과액이 음수라면요?", "현재 견적 기준으로 예산이 남는다는 뜻입니다."], ["아직 지급 안 한 발주도 넣나요?", "이미 실제비용에 반영하지 않았다면 남은 업무비에 포함합니다."], ["진행률로 비용을 예측하나요?", "진행률이 아닌 남은 업무의 직접 견적을 사용합니다."]],
    caveats: ["일정 지연·물가 변동·예비비는 남은 업무 예상비용에 직접 반영하세요."], relatedSlugs: ["operating-cashflow-plan", "meeting-cost"],
  }),
  define({
    slug: "equipment-lease-buy", title: "장비 임대·매입 총비용 비교 계산기", category: "business",
    description: "사용기간 동안 장비를 소유할 때의 매입대금·유지비·잔존가치와 임대료·설치비를 비교합니다. 초기 지출만 보지 않고 사용 후 처분대금까지 반영하여 두 방식의 총비용 차이를 확인합니다.",
    guidance: "매입 유지비와 임대 유지비 포함 범위가 다르면 견적의 차이를 먼저 맞춥니다. 잔존가치는 확정 매입보장액 또는 직접 정한 예상값이며, 돈의 시간가치·세금·리스 회계 처리는 이 단순 비용비교에 포함하지 않습니다.",
    keywords: ["장비 임대 매입", "리스 구매 비교", "장비 총비용"],
    fields: [money("purchase", "장비 매입대금", 12000000), money("resale", "사용 후 처분 예상액", 3000000), money("maintenance", "매입 시 월 유지비", 100000), money("rent", "월 임대료", 400000), money("setup", "임대 초기비용", 500000), number("months", "사용기간", 36, "개월", 1200)],
    compute: v => { if (!v.months) return invalid("사용기간을 0보다 크게 입력하세요."); const buy = v.purchase - v.resale + v.maintenance * v.months; const lease = v.rent * v.months + v.setup; return out("임대 비용 − 매입 비용", lease - buy, "원", [["매입 총비용", buy], ["임대 총비용", lease]], "양수는 매입이 저렴한 가정입니다. 처분액이 매입액을 넘으면 매입 비용은 음수가 될 수 있습니다."); },
    formula: "매입비용 = 매입가 − 처분액 + 월 유지비 × 기간; 임대비용 = 월 임대료 × 기간 + 초기비용",
    questions: [["임대 유지보수비는요?", "별도 청구된다면 월 임대료에 더해 같은 비용 범위로 맞춥니다."], ["이자 비용도 들어가나요?", "아닙니다. 자금 조달 비용과 현재가치 할인은 별도입니다."], ["잔존가치는 어떻게 정하나요?", "계약 보장액이나 중고 처분 견적을 사용하고 불확실하면 여러 값을 비교합니다."]],
    caveats: ["해지 위약금·소유권 이전·세무상 비용 처리 차이는 반영하지 않습니다."], relatedSlugs: ["project-budget-variance", "business-cashflow-runway"],
  }),
  define({
    slug: "relocation-payback", title: "이사 초기비용 회수기간 계산기", category: "real-estate",
    description: "더 저렴한 집으로 옮길 때 줄어드는 월 주거비와 달라지는 교통비를 함께 비교합니다. 실제 이사·중개·정리 비용을 입력하여 초기 지출을 매달의 절감액으로 회수하는 기간을 계산합니다.",
    guidance: "주거비는 월세와 관리비처럼 되돌려 받지 않는 지출을 같은 범위로 입력합니다. 반환되는 보증금은 이사비용에 더하지 말고 별도 자금 계획으로 구분하며, 계약 만료 전 위약금이 있으면 초기비용에 포함하세요.",
    keywords: ["이사 손익분기", "이사비 회수", "월세 절약 이사"],
    fields: [money("upfront", "이사 관련 초기비용 합계", 2000000), money("oldHousing", "현재 월 주거비", 900000), money("newHousing", "새집 월 주거비", 700000), money("oldTravel", "현재 월 교통비", 100000), money("newTravel", "새집 월 교통비", 150000)],
    compute: v => { const saving = v.oldHousing + v.oldTravel - v.newHousing - v.newTravel; if (saving <= 0) return out("월 비용 절감액", saving, "원", [], "월 절감액이 0 이하라 초기 이사비를 비용 절감으로 회수하는 기간은 존재하지 않습니다."); return out("이사비 회수기간", v.upfront / saving, "개월", [["월 비용 절감액", saving], ["첫 1년 순절감액", saving * 12 - v.upfront]]); },
    formula: "월 절감액 = 현재 주거·교통비 − 새집 주거·교통비; 회수기간 = 초기비용 ÷ 월 절감액",
    questions: [["보증금도 이사비에 넣나요?", "반환받을 보증금은 비용과 구분하며 이 계산에 넣지 않습니다."], ["교통비가 늘어도 반영되나요?", "현재와 새집 교통비를 비교하므로 증가분이 주거비 절감을 줄입니다."], ["회수기간이 없다고 나오면요?", "매달 비용이 줄지 않는 조건이라 비용절감만으로 초기 지출을 회수할 수 없습니다."]],
    caveats: ["보증금 기회비용과 통근시간의 개인적 가치는 제외합니다."], relatedSlugs: ["moving-cost-quick", "commute-time-value"],
  }),
  define({
    slug: "rent-free-effective-cost", title: "렌트프리 실질 월 임대비용 계산기", category: "real-estate",
    description: "임대료 면제 기간이 있는 상가나 사무실 계약을 전체 계약기간의 월평균 비용으로 비교합니다. 면제되지 않는 관리비와 초기 설치비까지 나누어 명목 월세와 실제 부담의 차이를 확인합니다.",
    guidance: "렌트프리 기간에도 관리비는 매월 낸다는 가정입니다. 설치비는 반환되지 않는 금액만 넣고, 중도 퇴거하면 면제 혜택을 반환하는 계약인지 확인하여 실제 유지할 계약기간을 기준으로 비교하세요.",
    keywords: ["렌트프리", "실질 임대료", "사무실 임대비용"],
    fields: [money("rent", "월 임대료", 2000000), money("management", "월 관리비", 300000), number("months", "전체 계약기간", 24, "개월", 1200), number("free", "임대료 면제기간", 3, "개월", 1200), money("setup", "반환되지 않는 초기비용", 6000000)],
    compute: v => { if (!v.months || v.free > v.months) return invalid("계약기간은 0보다 크고 면제기간은 계약기간 이하여야 합니다."); const total = v.rent * (v.months - v.free) + v.management * v.months + v.setup; return out("실질 월평균 임대비용", total / v.months, "원", [["기간 총비용", total], ["임대료 면제액", v.rent * v.free]]); },
    formula: "실질 월비용 = [월세 × (계약개월 − 면제개월) + 관리비 × 계약개월 + 초기비용] ÷ 계약개월",
    questions: [["관리비도 면제되나요?", "이 모델은 관리비는 면제되지 않는 조건입니다. 실제 계약에 맞게 관리비를 조정하세요."], ["초기비용은 왜 나누나요?", "서로 다른 계약을 전체 사용기간의 월평균 비용으로 비교하기 위해서입니다."], ["보증금이 포함되나요?", "반환되는 보증금은 포함하지 않으며 별도 자금 부담을 확인합니다."]],
    caveats: ["임대료 인상·중도해지·렌트프리 반환 조항은 자동 반영하지 않습니다."], relatedSlugs: ["vacancy-carrying-cost", "rental-prorated-rent"],
  }),
  define({
    slug: "vacancy-carrying-cost", title: "공실 유지비·놓친 임대료 계산기", category: "real-estate",
    description: "공실 기간에도 나가는 관리비·금융비용·기타 보유비와 받지 못한 임대료를 나누어 계산합니다. 실제 현금 유출과 기회수입을 구분하여 임차인 모집기간이 길어질 때의 영향을 확인합니다.",
    guidance: "금융비용에는 해당 기간에 실제 부담할 이자 등 비용을 넣습니다. 원금 상환을 넣으면 현금 부담 분석이 되지만 자산 감소와 비용이 섞이므로 해석을 바꾸어야 하며, 예상 임대료는 확정 수익이 아닙니다.",
    keywords: ["공실 비용", "임대 공실 유지비", "공실 손실"],
    fields: [number("months", "공실 예상기간", 3, "개월", 1200), money("management", "월 관리·유지비", 200000), money("financing", "월 금융비용", 600000), money("other", "월 기타 보유비", 100000), money("rent", "월 예상 임대료", 1200000)],
    compute: v => { const cash = (v.management + v.financing + v.other) * v.months; const missed = v.rent * v.months; return out("공실기간 현금 유지비", cash, "원", [["받지 못한 예상 임대료", missed], ["유지비와 놓친 수입 합계", cash + missed]], "놓친 임대료는 실제로 지급한 돈이 아닙니다. 현금 유지비와 별도로 구분하세요."); },
    formula: "현금 유지비 = (관리비 + 금융비 + 기타 보유비) × 공실개월; 놓친 임대료 = 예상 월세 × 공실개월",
    questions: [["놓친 임대료도 현금지출인가요?", "아닙니다. 얻을 수 있었던 예상 수입으로 별도 표시합니다."], ["재산세는 어떻게 넣나요?", "직접 확인한 연 부담액을 12로 나누어 기타 월 보유비에 넣을 수 있습니다."], ["공실이 0개월이면요?", "해당 공실기간의 유지비와 놓친 임대료는 모두 0입니다."]],
    caveats: ["임대료 시세나 예상 공실 확률을 자동 제공하지 않습니다."], relatedSlugs: ["rental-yield", "rent-free-effective-cost"],
  }),
  define({
    slug: "home-maintenance-reserve", title: "집수리 준비 월 적립액 계산기", category: "real-estate",
    description: "예정된 집수리 견적과 이미 확보한 금액을 비교해 남은 준비기간 동안 매달 모을 금액을 계산합니다. 공사비 예비비와 적립 원금을 분리하여 수리 시점의 현금 부족을 미리 확인합니다.",
    guidance: "견적은 같은 공사 범위와 세금 포함 기준으로 맞추고, 예비비율은 현장 불확실성을 보고 직접 정합니다. 적립금에 이자가 붙지 않는 보수적인 합산이며, 집수리비가 실제로 오르는 상황은 새 견적으로 다시 계산하세요.",
    keywords: ["집수리 적립", "수선비 준비", "수리 예산"],
    fields: [money("quote", "수리 공사 견적", 6000000), percent("buffer", "추가 예비비율", 10), money("saved", "이미 준비한 금액", 1800000), number("months", "남은 준비기간", 12, "개월", 1200)],
    compute: v => { if (!v.months) return invalid("남은 준비기간을 0보다 크게 입력하세요. 즉시 필요한 금액은 총목표에서 준비액을 뺀 금액입니다."); const target = v.quote * (1 + v.buffer / 100); const gap = Math.max(0, target - v.saved); return out("매달 필요한 적립액", gap / v.months, "원", [["예비비 포함 수리 목표", target], ["남은 준비금", gap], ["목표 초과 확보금", Math.max(0, v.saved - target)]]); },
    formula: "목표 = 수리견적 × (1 + 예비비율); 월 적립 = max(목표 − 준비액, 0) ÷ 남은개월",
    questions: [["예비비율은 권장치인가요?", "기본값은 예시이며 실제 공사 범위와 견적 불확실성에 따라 정합니다."], ["이미 목표보다 많이 모았다면요?", "추가 월 적립액은 0이고 초과 확보금을 따로 보여줍니다."], ["적립 이자도 반영되나요?", "이 계산은 이자 없는 원금 준비계획입니다."]],
    caveats: ["공동주택 법정 장기수선충당금 부과액 계산이 아닙니다."], relatedSlugs: ["renovation-budget-buffer", "savings-goal-time"],
  }),
  define({
    slug: "renovation-budget-buffer", title: "리모델링 예비비·추가공사 예산 계산기", category: "real-estate",
    description: "기본 공사 견적과 이미 확정된 추가공사를 구분하고 예비비를 더해 리모델링 예산을 정리합니다. 준비한 예산이 총예상액을 충당하는지 확인하여 계약 변경 때 필요한 금액을 비교합니다.",
    guidance: "예비비는 기본 공사와 확정 추가공사 합계에 적용합니다. 철거·폐기물·운반·부가세처럼 견적서에서 빠지기 쉬운 항목은 실제 포함 여부를 확인한 뒤 추가공사에 반영하고, 예비비와 확정비를 중복으로 넣지 마세요.",
    keywords: ["리모델링 예산", "추가공사 예비비", "인테리어 부족예산"],
    fields: [money("base", "기본 공사 견적", 20000000), money("extra", "확정 추가공사", 3000000), percent("buffer", "예비비율", 10), money("budget", "확보한 공사예산", 25000000)],
    compute: v => { const subtotal = v.base + v.extra; const buffer = subtotal * v.buffer / 100; return out("예비비 포함 총공사예산", subtotal + buffer, "원", [["추가 예비비", buffer], ["확보 예산 대비 부족액", Math.max(0, subtotal + buffer - v.budget)], ["남는 확보예산", Math.max(0, v.budget - subtotal - buffer)]]); },
    formula: "총예산 = (기본견적 + 추가공사) × (1 + 예비비율); 부족액 = max(총예산 − 확보예산, 0)",
    questions: [["예비비를 기본견적에만 적용하나요?", "기본견적과 확정 추가공사 합계에 적용합니다."], ["세금은 자동으로 붙나요?", "세율을 자동 적용하지 않으므로 같은 세금 포함 기준의 견적을 입력합니다."], ["실제 공사비를 예측하나요?", "입력한 견적과 예비비를 합산할 뿐 지역별 공사 단가를 추정하지 않습니다."]],
    caveats: ["계약상 변경 승인·보증·하자보수 범위는 별도 확인하세요."], relatedSlugs: ["home-maintenance-reserve", "project-budget-variance"],
  }),
  define({
    slug: "roommate-utility-share", title: "동거 공과금 체류일수 분담 계산기", category: "real-estate",
    integerFields: ["people"],
    description: "동거 공과금 중 기본요금은 동일하게 나누고 사용량 요금은 각자의 체류일수 비중으로 나누어 계산합니다. 출장이나 입퇴거로 거주기간이 다른 달에도 사전에 합의한 기준으로 한 사람의 부담을 확인합니다.",
    guidance: "모든 사람의 체류일수 합계는 사람 수를 곱한 인일 단위입니다. 예를 들어 두 사람이 각각 30일 살면 60인일이며, 사용량이 체류일에 비례한다는 합의용 모델이므로 실제 계량 기록이 있다면 그 기록이 더 적합할 수 있습니다.",
    keywords: ["룸메이트 공과금", "동거 비용 분담", "체류일 정산"],
    fields: [money("fixed", "공동 기본요금", 30000), money("usage", "사용량 관련 요금", 90000), number("people", "기본요금 분담 인원", 3, "명", 1000), number("myDays", "내 체류일수", 20, "일", 366), number("totalDays", "모두의 체류일수 합계", 75, "인일", 366000)],
    compute: v => { if (!v.people || !v.totalDays || v.myDays > v.totalDays) return invalid("분담 인원과 총 체류일수는 0보다 커야 하며 내 체류일수는 총합을 넘을 수 없습니다."); return out("내 공과금 분담액", v.fixed / v.people + v.usage * v.myDays / v.totalDays, "원", [["균등 기본요금 몫", v.fixed / v.people], ["체류 비율 사용요금 몫", v.usage * v.myDays / v.totalDays]]); },
    formula: "내 분담액 = 기본요금 ÷ 인원 + 사용량 요금 × 내 체류일 ÷ 전체 체류일 합계",
    questions: [["집을 비운 날은 어떻게 하나요?", "체류일수에서 제외할지 포함할지 동거인끼리 먼저 합의하세요."], ["0일 거주해도 기본요금이 있나요?", "이 모델에서는 기본요금은 동일 분담하므로 부담이 남습니다."], ["각자 계산하면 총액이 맞나요?", "같은 기본요금·인원·총 체류일수를 쓰면 반올림 전 합계는 청구액과 같습니다."]],
    caveats: ["법정 분담기준이 아니며 공동생활 합의용 단순 모델입니다."], relatedSlugs: ["rental-prorated-rent", "split-bill"],
  }),
  define({
    slug: "rental-prorated-rent", title: "월세·관리비 일할 정산 계산기", category: "real-estate",
    description: "중도 입주나 퇴거 시 한 달 월세와 관리비를 합의한 기준 일수로 나누어 사용기간의 금액을 계산합니다. 이미 납부한 금액을 차감하여 추가 납부와 환급 방향을 함께 확인할 수 있습니다.",
    guidance: "달력상의 실제 일수인지 계약서가 정한 일수인지 확인한 뒤 분모를 직접 입력합니다. 입주일·퇴거일을 포함하는 방식도 계약 당사자가 정한 사용일수에 반영하며, 보증금 반환이나 별도 정산항목은 포함하지 않습니다.",
    keywords: ["월세 일할계산", "중도입주 정산", "관리비 일할"],
    fields: [money("rent", "한 달 월세", 900000), money("management", "일할 대상 월 관리비", 100000), number("period", "한 달 계산 기준일수", 30, "일", 366), number("used", "청구 대상 사용일수", 12, "일", 366), money("paid", "이미 납부한 금액", 300000)],
    compute: v => { if (!v.period || v.used > v.period) return invalid("기준 일수는 0보다 크고 사용일수는 기준 일수 이하여야 합니다."); const due = (v.rent + v.management) * v.used / v.period; return out("추가 납부액·환급 차액", due - v.paid, "원", [["일할 청구액", due], ["하루 기준 부담", (v.rent + v.management) / v.period]], "차액이 양수면 추가 납부, 음수면 이미 낸 금액 중 환급 방향입니다. 실제 정산은 계약을 확인하세요."); },
    formula: "청구액 = (월세 + 일할 대상 관리비) × 사용일 ÷ 기준일; 차액 = 청구액 − 납부액",
    questions: [["모든 계약이 30일 기준인가요?", "아닙니다. 계약상 기준 또는 당사자 합의 일수를 직접 넣습니다."], ["고정 관리비도 나누나요?", "일할 대상인 관리비만 입력하고 고정 청구액은 별도 처리합니다."], ["환급액은 어떻게 읽나요?", "결과가 음수이면 절댓값만큼 이미 낸 돈이 청구액보다 많습니다."]],
    caveats: ["법적 반환 의무나 계약 분쟁을 판정하지 않습니다."], relatedSlugs: ["roommate-utility-share", "rent-free-effective-cost"],
  }),
  define({
    slug: "storage-unit-cost", title: "보관창고 칸수·임대예산 계산기", category: "real-estate",
    description: "보관할 짐의 부피와 창고 한 칸에서 실제 사용할 수 있는 부피를 비교하여 필요한 임대 칸수를 계산합니다. 이용 개월과 반입·반출 운송비를 더해 이사 사이 보관의 총예산을 확인합니다.",
    guidance: "창고 부피는 통로·적재불가 공간을 뺀 실사용 용량을 입력합니다. 총부피만 같아도 긴 가구가 들어가지 않을 수 있으므로 가로·세로·높이를 별도로 확인하고, 필요한 칸수는 올림하여 부족하지 않게 계산합니다.",
    keywords: ["짐 보관 비용", "창고 칸수", "셀프스토리지 예산"],
    fields: [number("volume", "보관 짐 부피", 12, "㎥", 1e6, "가구와 포장박스의 실제 보관 부피 합계입니다.", 0.1), number("capacity", "한 칸 실사용 용량", 5, "㎥", 1e6, "통로를 제외하고 짐을 넣을 수 있는 용량입니다.", 0.1), money("rent", "한 칸 월 임대료", 120000), number("months", "보관기간", 3, "개월", 1200), money("transport", "반입·반출 운송비 합계", 300000)],
    compute: v => { if (!v.capacity || !v.months) return invalid("한 칸 용량과 보관기간을 0보다 크게 입력하세요."); const units = ceilUnits(v.volume / v.capacity); return out("총 보관 예산", units * v.rent * v.months + v.transport, "원", [["필요 창고 칸수", units, "칸"], ["계약 용량 여유", units * v.capacity - v.volume, "㎥"], ["월 임대료 합계", units * v.rent]]); },
    formula: "필요 칸수 = 올림(짐 부피 ÷ 칸당 용량); 총비용 = 칸수 × 월 임대료 × 개월 + 운송비",
    questions: [["부피가 맞으면 반드시 들어가나요?", "아닙니다. 가구 크기와 출입구, 적재 형태를 현장에서 확인해야 합니다."], ["입고비와 출고비는요?", "왕복 합계로 운송비에 넣습니다."], ["월 중 일부만 쓰면요?", "월 단위 청구를 가정하므로 실제 청구 개월수로 입력합니다."]],
    caveats: ["보험·보증금·온습도 관리 추가요금은 필요한 항목에 직접 반영하세요."], relatedSlugs: ["relocation-payback", "moving-cost-quick"],
  }),
  define({
    slug: "annual-plan-break-even", title: "연간 구독권 손익분기 이용기간 계산기", category: "life",
    description: "연간 선납 구독권과 월별 결제를 비교하여 몇 개월 사용할 때 연간권 비용에 도달하는지 확인합니다. 실제 이용 예정 개월수를 입력해 중도에 사용을 멈추는 경우의 비용 차이도 계산합니다.",
    guidance: "연간권은 중도 환급이 없고 월 결제는 사용하는 달에만 낸다는 비교입니다. 가입비나 프로모션이 있으면 같은 서비스 범위의 실결제 가격으로 맞추고, 손익분기 기간이 12개월을 넘으면 한 해 내에 유리해지지 않는 조건입니다.",
    keywords: ["연간구독 월결제", "구독권 손익분기", "선납 구독 비교"],
    fields: [money("monthly", "월 결제 가격", 15000), money("annual", "연간 선납 가격", 120000), number("months", "예상 이용기간", 10, "개월", 12)],
    compute: v => { if (!v.monthly) return invalid("월 결제 가격이 0이면 무료 월 결제 대비 유한한 손익분기 기간을 구할 수 없습니다."); return out("연간권과 비용이 같아지는 기간", v.annual / v.monthly, "개월", [["예정기간 월결제 합계", v.monthly * v.months], ["연간권 선택 시 절감액", v.monthly * v.months - v.annual]], v.annual > v.monthly * 12 ? "계산 기준이 12개월을 넘습니다. 연간권 유효기간 1년 안에는 비용을 회수할 수 없는 조건입니다." : "절감액이 음수면 이용 예정기간에는 월 결제가 더 저렴합니다. 같은 금액에 도달하는 시점과 실제 청구 개월은 구분하세요."); },
    formula: "손익분기 개월 = 연간가격 ÷ 월가격; 연간권 절감 = 월가격 × 이용개월 − 연간가격",
    questions: [["연간권 환불이 되면요?", "환불 없는 선납 기준이므로 환불액을 반영한 별도 비교가 필요합니다."], ["손익분기가 정확히 8개월이면요?", "8개월은 같은 비용이며 더 오래 사용해야 연간권이 저렴해집니다."], ["무료 체험기간도 사용개월인가요?", "월 결제에서 실제 돈을 낼 개월만 입력하세요."]],
    caveats: ["자동갱신·할인 종료·서비스 해지 조건은 별도 확인하세요."], relatedSlugs: ["subscription-monthly", "prepaid-pass-usage"],
  }),
  define({
    slug: "appliance-energy-replacement", title: "가전 교체 전력절감·회수기간 계산기", category: "life",
    description: "기존 가전과 새 가전의 평균 소비전력 차이에 사용시간과 직접 입력한 전력 단가를 적용합니다. 교체에 추가로 드는 비용을 전력비 절감으로 회수할 수 있는 기간과 연간 절감액을 확인합니다.",
    guidance: "최대 정격전력과 평균 작동전력은 다를 수 있으므로 같은 사용조건에서 측정한 값을 넣는 것이 좋습니다. 누진요금 전체를 재현하지 않으며 변하는 사용량에 적용할 한계 단가를 입력해 다른 가전 사용량과 구분하세요.",
    keywords: ["가전 교체 절감", "전력 소비 비교", "에너지 회수기간"], sources: [source.energy],
    fields: [number("oldWatts", "기존 평균 소비전력", 500, "W", 1e7), number("newWatts", "새 평균 소비전력", 300, "W", 1e7), number("hours", "하루 작동시간", 5, "시간", 24, "같은 기능을 사용하는 하루 실제 시간입니다.", 0.1), number("days", "한 달 작동일수", 30, "일", 31), unitMoney("unitRate", "사용량에 적용할 전력 단가", 200, "원/kWh", "원/kWh 단가를 직접 입력합니다. 누진제 전체 청구액을 계산하지 않습니다."), money("upgrade", "교체 추가비용", 360000)],
    compute: v => { const kwh = (v.oldWatts - v.newWatts) * v.hours * v.days / 1000; const saving = kwh * v.unitRate; return out("월 전력비 절감액", saving, "원", [["월 전력량 감소", kwh, "kWh"], ["동일 사용 12개월 절감액", saving * 12], ...(saving > 0 ? [["교체비 회수기간", v.upgrade / saving, "개월"]] as Row[] : [])], saving > 0 ? "소비전력과 단가가 유지되는 단순 비교이며 기본요금과 누진구간 변화는 제외합니다." : "전력비가 줄지 않는 조건이므로 전력 절감으로 교체비를 회수하는 기간은 없습니다."); },
    formula: "월 절감 kWh = (기존W − 새W) × 하루시간 × 월일수 ÷ 1000; 절감액 = kWh × 단가",
    questions: [["한국전력 청구금액과 같은가요?", "아닙니다. 사용자가 입력한 단가로 두 기기의 차이만 계산합니다."], ["새 가전 소비전력이 더 높으면요?", "절감액이 음수로 표시되어 전기비용 증가를 보여줍니다."], ["냉장고 정격전력을 24시간 곱해도 되나요?", "주기적으로 작동하는 기기는 평균 실측 전력이나 동등 조건의 사용량을 확인하세요."]],
    caveats: ["계절별 사용과 효율 변화, 수리·폐기비용은 교체비에 별도 반영하세요."], relatedSlugs: ["electricity-bill", "reusable-item-payback"],
  }),
  define({
    slug: "event-budget-headcount", title: "예산별 행사 수용인원 계산기", category: "life",
    integerFields: ["invited"],
    description: "전체 행사예산에서 대관·장비 같은 고정비를 빼고 식사와 개인 물품비로 가능한 인원수를 계산합니다. 초대 예정 인원에서의 총예산과 부족액을 함께 보며 행사 규모를 조정할 수 있습니다.",
    guidance: "참가자가 늘 때 실제로 추가되는 비용만 1인 비용에 넣습니다. 인원 구간에 따라 대관료나 인력이 추가되는 계약이면 각 구간을 따로 계산하고, 소수점 인원을 버려 현재 예산에서 초과하지 않는 정수 인원을 표시합니다.",
    keywords: ["행사 예산 인원", "모임 비용", "행사 수용인원"],
    fields: [money("budget", "확보한 총예산", 3000000), money("fixed", "행사 고정비", 1000000), money("meal", "1인 식음료", 30000), money("kit", "1인 물품·추가비", 10000), number("invited", "초대 예정 인원", 60, "명", 1e6)],
    compute: v => { const unit = v.meal + v.kit; if (!unit) return invalid("1인당 추가 비용이 0이면 비용 기준 최대 인원을 계산할 수 없습니다. 장소 정원을 별도 확인하세요."); const total = v.fixed + unit * v.invited; return out("현재 예산으로 가능한 인원", floorUnits(Math.max(0, v.budget - v.fixed) / unit), "명", [["초대인원 예상 총비용", total], ["초대인원 기준 부족예산", Math.max(0, total - v.budget)]], v.budget < v.fixed ? "인원과 무관한 고정비부터 예산을 초과합니다." : "예산 기준 인원이며 장소 안전 정원과는 별개입니다."); },
    formula: "가능인원 = 버림(max(예산 − 고정비, 0) ÷ (식비 + 개인 추가비)); 총비용 = 고정비 + 예정인원 × 1인비",
    questions: [["예비비는 어디에 넣나요?", "사용 가능한 예산에서 먼저 따로 확보하거나 고정비에 포함하세요."], ["장소 정원도 계산하나요?", "비용으로 가능한 인원만 계산하며 실제 장소 정원은 별도로 확인합니다."], ["최소 보증인원이 있다면요?", "최소 보증 비용을 고정비로 분리하여 중복 없이 입력합니다."]],
    caveats: ["인원 구간별 할인·최소 주문량·취소수수료는 자동 적용하지 않습니다."], relatedSlugs: ["split-bill", "travel-shared-budget"],
  }),
  define({
    slug: "car-total-ownership", title: "차량 총보유비·월평균 비용 계산기", category: "life",
    description: "차량 구입가격에서 예상 처분대금을 빼고 보유기간의 보험·세금·정비·연료비를 합산합니다. 할부금만으로 판단하기 어려운 차량의 총보유비와 월평균 부담을 같은 조건으로 비교합니다.",
    guidance: "연간 고정비는 실제 보험 견적·직접 확인한 세금·정비 예산의 합계로 입력합니다. 구입가에는 실제 초기비용을 포함하고 연료비는 주행거리와 연비로 계산하며, 대출 원금은 구입가와 중복 합산하지 마세요.",
    keywords: ["자동차 TCO", "차량 총보유비", "자동차 월 비용"],
    fields: [money("purchase", "초기 구입 총비용", 35000000), money("resale", "보유 종료 처분액", 15000000), number("years", "보유기간", 5, "년", 100), money("fixed", "연 보험·세금·정비 합계", 2000000), number("km", "연간 주행거리", 15000, "km", 1e7), number("efficiency", "실제 평균 연비", 12, "km/L", 1000, "같은 주행 환경의 연비를 입력하세요.", 0.1), unitMoney("fuel", "연료 단가", 1700, "원/L", "직접 확인한 원/L 단가입니다.")],
    compute: v => { if (!v.years || !v.efficiency) return invalid("보유기간과 연비가 0보다 커야 총보유비를 계산할 수 있습니다."); const fuel = v.km / v.efficiency * v.fuel * v.years; const total = v.purchase - v.resale + v.fixed * v.years + fuel; return out("보유기간 총비용", total, "원", [["월평균 보유비", total / (v.years * 12)], ["기간 연료비", fuel], ["구입·처분 차액", v.purchase - v.resale]]); },
    formula: "총보유비 = 구입비 − 처분액 + 연 고정비 × 년수 + 연 주행거리 ÷ 연비 × 연료단가 × 년수",
    questions: [["할부 원금도 더하나요?", "이미 구입비에 포함되므로 중복해서 더하지 않습니다. 이자는 별도 비용입니다."], ["주차비와 통행료는요?", "반영하려면 연 고정비 합계에 함께 넣습니다."], ["처분가격이 확실하지 않다면요?", "서로 다른 처분액을 넣어 비용 범위를 비교하세요."]],
    caveats: ["금융이자와 투자 기회비용, 미래 차량가격은 자동 추정하지 않습니다."], relatedSlugs: ["fuel-cost-trip", "ev-charge-vs-fuel"],
  }),
  define({
    slug: "ev-charge-vs-fuel", title: "전기차·내연차 월 에너지비 비교 계산기", category: "life",
    description: "같은 주행거리에서 내연차의 연비와 전기차의 전비, 직접 확인한 주유·충전 단가를 비교합니다. 전기차 충전 월정액 등 고정 에너지 비용까지 반영해 한 달 에너지 지출 차이를 계산합니다.",
    guidance: "전비는 차량 표기값과 충전기에서 결제한 전력량 기준이 다를 수 있으므로 충전 손실을 반영한 실제 전비를 쓰는 것이 좋습니다. 이 비교는 에너지 비용만 보며 차량가격·보험·세금·유지비 차이는 총보유비에서 별도로 계산하세요.",
    keywords: ["전기차 충전비 비교", "전비 연비", "월 연료비"],
    fields: [number("km", "월 주행거리", 1000, "km", 1e7), number("fuelEfficiency", "내연차 실제 연비", 10, "km/L", 1000, "실제 사용환경의 연비입니다.", 0.1), unitMoney("fuelPrice", "연료 단가", 1700, "원/L", "직접 확인한 원/L 가격입니다."), number("electricEfficiency", "전기차 실제 전비", 5, "km/kWh", 1000, "충전 손실까지 반영한 실사용 전비를 권장합니다.", 0.1), unitMoney("electricPrice", "충전 단가", 300, "원/kWh", "직접 확인한 원/kWh 가격입니다."), money("fixed", "월 충전 고정요금", 5000)],
    compute: v => { if (!v.fuelEfficiency || !v.electricEfficiency) return invalid("연비와 전비를 각각 0보다 크게 입력하세요."); const fuel = v.km / v.fuelEfficiency * v.fuelPrice; const charge = v.km / v.electricEfficiency * v.electricPrice + v.fixed; return out("전기차 월 에너지비 절감", fuel - charge, "원", [["내연차 월 연료비", fuel], ["전기차 월 충전비", charge]], "양수는 전기차 에너지비가 더 적은 가정이며 음수는 더 많은 가정입니다."); },
    formula: "내연차 = km ÷ km/L × 원/L; 전기차 = km ÷ km/kWh × 원/kWh + 월 고정요금",
    questions: [["차량 구매비용도 포함되나요?", "에너지비만 비교합니다. 구입비는 총보유비 계산에서 따로 비교하세요."], ["무료 충전이면 0원을 넣나요?", "실제 무료인 범위라면 단가 0을 사용할 수 있습니다."], ["주행하지 않아도 전기차 비용이 나오나요?", "입력한 월 고정요금이 있다면 주행거리와 무관하게 더해집니다."]],
    caveats: ["계절별 전비와 급속·완속 충전 비중은 입력 단가·전비에 직접 반영하세요."], relatedSlugs: ["car-total-ownership", "appliance-energy-replacement"],
  }),
  define({
    slug: "commute-time-value", title: "출퇴근 수단 시간·비용 비교 계산기", category: "life",
    description: "두 출퇴근 수단의 하루 왕복 요금과 소요시간을 같은 출근일수로 비교합니다. 개인이 정한 시간의 가치를 적용해 현금비용이 적은 방법과 시간을 아끼는 방법의 월 환산 차이를 확인합니다.",
    guidance: "버스·철도·차량 등 두 선택지의 요금은 주차·통행료를 포함한 하루 왕복 실비로 맞춥니다. 시간 가치는 실제 임금이나 회사 보상이 아닌 개인 판단값이며, 현금 지출 차이와 시간 평가액을 별도로 보여줍니다.",
    keywords: ["출퇴근 교통수단 비교", "통근시간 비용", "시간 가치"],
    fields: [money("fareA", "A 하루 왕복 비용", 6000), number("minutesA", "A 하루 왕복 시간", 100, "분", 1440), money("fareB", "B 하루 왕복 비용", 12000), number("minutesB", "B 하루 왕복 시간", 60, "분", 1440), number("days", "월 출근일수", 20, "일", 31), unitMoney("timeValue", "개인 시간 가치", 15000, "원/시간", "1시간을 줄이는 것에 부여하는 원화 가치입니다. 임금 계산이 아닙니다.")],
    compute: v => { const cash = (v.fareA - v.fareB) * v.days; const hours = (v.minutesA - v.minutesB) * v.days / 60; return out("B 선택 시 월 환산 절감", cash + hours * v.timeValue, "원", [["월 현금비용 절감", cash], ["월 절약 시간", hours, "시간"], ["절약 시간 평가액", hours * v.timeValue]], "양수는 B의 환산 부담이 적다는 뜻입니다. 시간 평가액은 실제로 받는 돈이 아닙니다."); },
    formula: "B 선택 절감 = (A요금 − B요금) × 출근일 + (A분 − B분) ÷ 60 × 출근일 × 시간가치",
    questions: [["시간 가치를 0으로 두면요?", "교통요금의 현금 차이만 비교합니다."], ["편도 시간인가요?", "왕복 시간과 왕복 요금을 입력합니다."], ["이 결과가 임금 차이인가요?", "개인 시간 선호를 금액으로 표현한 비교이며 임금 계산이 아닙니다."]],
    caveats: ["혼잡·환승 불편·안전·유연근무 가치는 자동 반영하지 않습니다."], relatedSlugs: ["parking-pass-break-even", "car-total-ownership"],
  }),
  define({
    slug: "parking-pass-break-even", title: "주차 정기권 손익분기 이용일 계산기", category: "life",
    description: "하루 실제 주차요금과 월 정기권 가격을 비교해 정기권과 비용이 같아지는 이용일수를 계산합니다. 예정 주차일수에서 두 방식의 월 부담을 함께 표시하여 출근 빈도에 맞는 결제를 검토합니다.",
    guidance: "하루 요금은 주차장 시간요율을 단순히 곱하기보다 할인과 일 최대요금을 반영한 실제 하루 결제액으로 입력합니다. 정기권이 출입시간이나 지정면을 제한한다면 두 상품의 사용 가능 조건도 함께 비교해야 합니다.",
    keywords: ["주차 정기권", "주차비 손익분기", "월주차 비교"],
    fields: [money("daily", "하루 실제 주차요금", 10000), money("pass", "월 정기권 가격", 150000), number("days", "월 예정 주차일수", 20, "일", 31)],
    compute: v => { if (!v.daily) return invalid("하루 주차요금이 무료이면 유료 정기권의 유한한 손익분기일을 계산할 수 없습니다."); return out("정기권 손익분기 이용일", v.pass / v.daily, "일", [["일 결제 월 합계", v.daily * v.days], ["정기권 선택 절감액", v.daily * v.days - v.pass]], v.pass > v.daily * 31 ? "손익분기 기준이 31일을 넘으므로 한 달 안에 비용을 회수할 수 없는 조건입니다." : "손익분기일은 같은 비용이 되는 기준입니다. 그보다 더 이용해야 정기권이 저렴해집니다."); },
    formula: "손익분기일 = 정기권 가격 ÷ 하루요금; 절감액 = 하루요금 × 이용일 − 정기권 가격",
    questions: [["시간요금은 어떻게 입력하나요?", "일 최대요금과 할인까지 반영한 하루 실제 금액을 입력합니다."], ["손익분기가 31일보다 길면요?", "입력한 한 달 이용 범위에서는 정기권이 유리하지 않을 수 있습니다."], ["출장으로 이용일이 줄면요?", "예정 이용일을 줄여 선납 비용의 영향을 다시 비교하세요."]],
    caveats: ["차량별 할인·시간 제한·주차 가능 보장은 실제 상품 안내를 확인하세요."], relatedSlugs: ["commute-time-value", "annual-plan-break-even"],
  }),
  define({
    slug: "travel-shared-budget", title: "여행 공동경비·개인 예산 계산기", category: "life",
    integerFields: ["people"],
    description: "숙박과 차량처럼 일행이 함께 부담하는 비용과 식비·입장료처럼 각자 쓰는 비용을 나누어 여행 예산을 계산합니다. 여행 일수와 인원, 공동 예비비를 반영하여 한 사람이 준비할 금액을 확인합니다.",
    guidance: "숙박비는 객실 전체의 여행기간 합계, 공동 교통비는 차량 대여 등 합계로 입력합니다. 개인별 항공료가 서로 다르면 공통 비용에 넣지 말고 산출된 개인 예산에 각자의 항공료를 더하며, 공동비는 동일하게 나누는 가정입니다.",
    keywords: ["여행 공동경비", "여행 예산 분담", "일행 여행비"],
    fields: [number("people", "함께 분담할 인원", 4, "명", 10000), number("days", "여행 일수", 3, "일", 3660), money("hotel", "전체 숙박비 합계", 600000), money("transport", "공동 교통비 합계", 240000), money("daily", "1인 하루 개인지출", 50000), percent("buffer", "공동경비 예비비율", 10)],
    compute: v => { if (!v.people || !v.days) return invalid("분담 인원과 여행 일수를 0보다 크게 입력하세요."); const shared = (v.hotel + v.transport) * (1 + v.buffer / 100); const personal = v.daily * v.days; return out("1인 준비 예산", shared / v.people + personal, "원", [["1인 공동경비 몫", shared / v.people], ["1인 개인경비", personal], ["일행 전체 예산", shared + personal * v.people]]); },
    formula: "1인 예산 = (숙박 + 공동교통) × (1 + 공동예비비율) ÷ 인원 + 개인 하루지출 × 일수",
    questions: [["숙박비는 1인 금액인가요?", "일행 전체가 사용할 객실의 여행기간 총액을 입력합니다."], ["예비비가 개인 식비에도 붙나요?", "이 모델에서는 숙박·공동교통 합계에만 예비비를 붙입니다."], ["일행마다 머무는 기간이 다르면요?", "동일 분담 모델이므로 기간별 그룹을 나누어 계산하는 편이 적합합니다."]],
    caveats: ["환율·보험·개인별 항공료·쇼핑비는 필요한 항목에 직접 반영하세요."], relatedSlugs: ["travel-luggage-shipping", "exchange-spread-cost"],
  }),
  define({
    slug: "travel-luggage-shipping", title: "추가 수하물·짐 배송 비용 비교 계산기", category: "life",
    integerFields: ["flights"],
    description: "항공편마다 내는 추가 수하물 요금과 짐을 별도로 보내는 배송 견적을 비교합니다. 배송 무게가 요금 단위를 넘을 때의 올림과 기본요금을 반영하여 같은 구간의 운반 비용 차이를 확인합니다.",
    guidance: "수하물 요금은 항공사에서 확인한 실제 추가 금액을 입력하고 배송은 한 번의 발송 기준으로 비교합니다. 부피무게가 적용되는 업체라면 실중량 대신 청구 중량을 쓰고, 왕복이라면 각 방향을 나누어 합산하세요.",
    keywords: ["추가수하물 배송 비교", "여행 짐 운송", "수하물 비용"],
    fields: [money("bagFee", "편도 항공편당 추가 수하물료", 40000), number("flights", "비교할 항공편 수", 2, "편", 1000), number("weight", "배송 청구 중량", 12, "kg", 1e6, "부피무게가 있으면 실제 청구되는 중량을 입력합니다.", 0.1), number("block", "배송 요금 1단위 중량", 5, "kg", 1e6, "예: 5kg마다 한 단위 요금이 붙으면 5를 입력합니다.", 0.1), money("unitFee", "중량 단위당 배송료", 10000), money("base", "배송 기본·접수료", 5000)],
    compute: v => { if (!v.block) return invalid("배송 요금 단위 중량을 0보다 크게 입력하세요."); const airline = v.bagFee * v.flights; const delivery = ceilUnits(v.weight / v.block) * v.unitFee + v.base; return out("별도 배송 선택 시 절감액", airline - delivery, "원", [["추가 수하물 총요금", airline], ["별도 배송 총요금", delivery], ["청구 중량 단위 수", ceilUnits(v.weight / v.block), "단위"]]); },
    formula: "수하물비 = 편당 요금 × 편수; 배송비 = 올림(청구kg ÷ 단위kg) × 단위요금 + 기본료",
    questions: [["왕복 배송도 포함되나요?", "배송은 1회 기준이므로 왕복 운반은 각 방향을 별도로 계산합니다."], ["부피가 큰 짐은요?", "택배 업체가 적용할 부피무게를 청구 중량에 넣습니다."], ["배송이 싸면 항상 유리한가요?", "소요일·수취 가능 여부·금지품목·분실 보상도 따로 확인해야 합니다."]],
    caveats: ["통관·도서산간·취급제한 추가요금은 기본료 등에 직접 반영하세요."], relatedSlugs: ["travel-shared-budget", "storage-unit-cost"],
  }),
  define({
    slug: "prepaid-pass-usage", title: "횟수권 필요한 이용횟수 계산기", category: "life",
    integerFields: ["visits", "planned"],
    description: "횟수권 가격과 낱회 이용료를 비교하여 얼마만큼 이용해야 선납한 비용에 도달하는지 확인합니다. 유효기간 동안 실제로 쓸 예상 횟수와 제공 횟수 한도를 함께 반영해 미사용 비용을 살펴봅니다.",
    guidance: "예상 이용횟수는 횟수권 제공 횟수를 넘지 않도록 입력합니다. 유효기간 종료 후 남은 횟수를 환불하지 않는 가정이며, 이미 구매한 권리의 사용 여부 판단과 새로 구매할지 결정하는 비용 비교는 구분해서 읽으세요.",
    keywords: ["횟수권 손익분기", "이용권 단가", "선불권 미사용"],
    fields: [money("pass", "횟수권 구입가격", 200000), number("visits", "제공 이용횟수", 10, "회", 1e6), money("single", "낱회 이용가격", 30000), number("planned", "기간 내 예상 이용횟수", 8, "회", 1e6)],
    compute: v => { if (!v.visits || !v.single || v.planned > v.visits) return invalid("제공횟수와 낱회가격은 0보다 커야 하고 예상 사용횟수는 제공횟수 이하여야 합니다."); const needed = ceilUnits(v.pass / v.single); return out("낱회 결제액을 충당하는 횟수", needed, "회", [["예상 사용 기준 절감액", v.planned * v.single - v.pass], ["미사용 권리의 배분원가", (v.visits - v.planned) * v.pass / v.visits]], needed > v.visits ? "제공 횟수를 모두 사용해도 낱회 결제보다 저렴해지지 않는 조건입니다." : "정수 횟수 기준이며 같은 금액이 되는 경계에서는 절감이 0일 수 있습니다."); },
    formula: "필요횟수 = 올림(횟수권가격 ÷ 낱회가격); 예정 절감 = 예정횟수 × 낱회가격 − 횟수권가격",
    questions: [["미사용 배분원가는 환불액인가요?", "아닙니다. 구입가격을 횟수에 나눈 참고값이며 환불 규정과 무관합니다."], ["예상횟수가 0이면요?", "사용하지 않는 선납비 전액만큼 비용 차이가 불리하게 표시됩니다."], ["기한을 넘겨 쓸 수 있다면요?", "실제로 사용 가능한 전체 기간에 맞춰 예상횟수를 다시 입력합니다."]],
    caveats: ["해지·양도·환불 약관과 예약 가능 여부는 별도 확인하세요."], relatedSlugs: ["annual-plan-break-even", "discount-percent"],
  }),
  define({
    slug: "bulk-unit-price-waste", title: "폐기율 반영 대용량 상품 단가 비교", category: "life",
    description: "대용량 묶음 가격이 저렴해 보여도 남아서 버리는 양을 반영하면 실제 단가가 달라집니다. 큰 포장과 작은 포장의 사용 가능한 수량 기준 단가를 비교해 같은 사용량에서의 지출 차이를 확인합니다.",
    guidance: "두 상품의 수량은 개·g·mL 등 같은 단위로 맞추고 배송료도 각 가격에 포함합니다. 폐기율은 소비 경험으로 직접 정한 가정이며, 큰 상품을 전부 쓸 수 있다면 0으로 바꾸어 순수 구매단가와 비교하세요.",
    keywords: ["대용량 단가", "폐기율 비용", "묶음구매 비교"],
    fields: [money("largePrice", "대용량 가격", 20000), number("largeQty", "대용량 수량", 20, "동일 단위", 1e9, "두 포장을 모두 같은 단위로 입력합니다.", 0.1), percent("waste", "대용량 예상 폐기율", 25), money("smallPrice", "소포장 가격", 6000), number("smallQty", "소포장 수량", 5, "동일 단위", 1e9, "소포장은 모두 사용한다고 가정합니다.", 0.1)],
    compute: v => { const usable = v.largeQty * (1 - v.waste / 100); if (!usable || !v.smallQty) return invalid("실제로 사용할 대용량 수량과 소포장 수량이 0보다 커야 단가를 비교할 수 있습니다."); const large = v.largePrice / usable; const small = v.smallPrice / v.smallQty; return out("대용량 − 소포장 실사용 단가", large - small, "원/단위", [["대용량 실사용 단가", large, "원/단위"], ["소포장 단가", small, "원/단위"], ["대용량 사용 가능 수량", usable, "단위"]], "음수면 대용량의 실사용 단가가 저렴합니다. 보관공간과 구매 시점 현금지출은 별도입니다."); },
    formula: "대용량 단가 = 가격 ÷ [수량 × (1 − 폐기율)]; 소포장 단가 = 가격 ÷ 수량",
    questions: [["서로 단위가 다르면요?", "kg와 g, L와 mL 등을 같은 단위로 먼저 맞춰야 합니다."], ["폐기율 100%는요?", "사용할 양이 없어 실사용 단가를 정의할 수 없습니다."], ["소포장도 버리는 부분이 있다면요?", "소포장 수량에 실제로 사용할 수량을 넣습니다."]],
    caveats: ["품질·유통기한·보관 전력비 차이는 자동 평가하지 않습니다."], relatedSlugs: ["free-shipping-threshold", "discount-percent"],
  }),
  define({
    slug: "free-shipping-threshold", title: "무료배송 추가구매 비용 비교 계산기", category: "life",
    description: "배송비를 내는 주문과 무료배송 기준을 맞추려고 상품을 더 담는 주문의 현금 지출을 비교합니다. 필요한 최소 추가구매액과 배송비 절감액을 구분하여 무료배송이 실제 지출 절감인지 확인합니다.",
    guidance: "무료배송 기준은 쿠폰 적용 후 상품대금처럼 판매자가 정한 판정 기준으로 맞춥니다. 추가 상품의 실제 필요성은 계산하지 않으며, 최소 금액만큼 정확히 구매할 수 있다는 이론 비교이므로 상품 단위로 금액이 늘 수 있습니다.",
    keywords: ["무료배송 손익", "배송비 추가구매", "무료배송 문턱"],
    fields: [money("cart", "현재 무료배송 판정 상품금액", 23000), money("threshold", "무료배송 기준금액", 30000), money("shipping", "기준 미달 배송비", 3000)],
    compute: v => { const extra = Math.max(0, v.threshold - v.cart); const fee = extra > 0 ? v.shipping : 0; return out("무료배송 맞추기 추가 지출", extra - fee, "원", [["최소 추가구매 상품금액", extra], ["추가구매 없이 주문 총액", v.cart + fee], ["기준 맞춘 최소 주문총액", v.cart + extra]], extra === 0 ? "이미 무료배송 기준을 충족합니다." : "양수는 배송비를 내는 편보다 현금이 더 나가는 금액입니다. 추가 상품이 필요한지도 따로 판단하세요."); },
    formula: "최소 추가구매 = max(무료배송 기준 − 장바구니, 0); 추가 지출 = 추가구매 − 절약 배송비",
    questions: [["결과가 음수이면요?", "기준에 맞출 최소 추가상품 금액이 배송비보다 작은 조건입니다."], ["추가 상품이 필요하다면요?", "이 계산은 현금 차이만 보여주므로 상품의 필요성은 별도로 판단합니다."], ["이미 기준을 넘으면요?", "추가구매와 배송비가 모두 0인 것으로 처리합니다."]],
    caveats: ["지역별 배송비·쿠폰 판정·묶음배송 불가 조건은 실제 주문서로 확인하세요."], relatedSlugs: ["coupon-stack-savings", "bulk-unit-price-waste"],
  }),
  define({
    slug: "coupon-stack-savings", title: "정액·정률 쿠폰 적용순서 비교 계산기", category: "life",
    description: "같은 장바구니에 정액쿠폰과 정률쿠폰을 적용할 때 순서에 따라 달라지는 최종 결제액을 계산합니다. 정률 할인한도와 결제액 하한 0원을 반영하여 두 쿠폰 순서의 실제 차이를 확인합니다.",
    guidance: "두 쿠폰을 함께 쓸 수 있고 최소 주문금액 조건이 충족된 상황을 가정합니다. 할인한도 0은 정률 할인이 허용되지 않는 뜻이며 무제한이라면 상품금액 이상의 한도를 입력하고, 적용 순서가 고정된 상점에는 선택 비교를 그대로 적용하지 마세요.",
    keywords: ["중복쿠폰 순서", "쿠폰 할인한도", "정액 정률 할인"],
    fields: [money("price", "쿠폰 대상 상품금액", 100000), money("fixed", "정액 할인액", 10000), percent("discount", "정률 할인율", 20), money("cap", "정률 할인 최대금액", 30000)],
    compute: v => { const afterFixed = Math.max(0, v.price - v.fixed); const fixedFirst = afterFixed - Math.min(afterFixed * v.discount / 100, v.cap); const rateFirst = Math.max(0, v.price - Math.min(v.price * v.discount / 100, v.cap) - v.fixed); return out("두 순서 중 낮은 결제액", Math.min(fixedFirst, rateFirst), "원", [["정액 후 정률 결제액", fixedFirst], ["정률 후 정액 결제액", rateFirst], ["순서에 따른 차이", Math.abs(fixedFirst - rateFirst)]]); },
    formula: "정액먼저 = max(가격 − 정액, 0) − min(잔액 × 할인율, 한도); 정률먼저 = max(가격 − min(가격 × 할인율, 한도) − 정액, 0)",
    questions: [["두 쿠폰이 중복 가능한가요?", "가능한 조건을 비교하는 도구이며 실제 상점 약관은 따로 확인해야 합니다."], ["한도 0은 무제한인가요?", "아닙니다. 할인 상한이 0원입니다. 무제한이면 대상금액 이상의 수를 넣습니다."], ["쿠폰 합이 가격보다 크면요?", "결제액을 0원 아래로 내려가지 않도록 처리합니다."]],
    caveats: ["최소 주문액·상품 제외·적립금·배송료 할인은 포함하지 않습니다."], relatedSlugs: ["free-shipping-threshold", "discount-percent"],
  }),
  define({
    slug: "return-or-exchange-cost", title: "반품 후 교환·재구매 추가비용 계산기", category: "life",
    description: "기존 상품을 반품하고 다른 상품으로 다시 구매할 때 환급받을 금액과 새 결제금액을 나누어 계산합니다. 반품 배송료와 공제액을 포함하여 이미 낸 돈 외에 추가로 필요한 현금을 확인합니다.",
    guidance: "반품 허용 여부와 환불액은 판매자에게 먼저 확인합니다. 여기서는 최초 결제액에서 반품 배송비·환불 공제액을 빼는 구조이며, 즉시 교환 수수료 방식이 아니라 환불 후 재구매 방식의 자금 차이를 비교합니다.",
    keywords: ["반품 재구매 비용", "교환 추가금", "환불 배송비"],
    fields: [money("paid", "최초 결제액", 100000), money("returnShipping", "반품 배송비", 6000), money("deduction", "환불 기타 공제액", 4000), money("replacement", "새 상품 가격", 110000), money("delivery", "새 상품 배송비", 3000)],
    compute: v => { if (v.returnShipping + v.deduction > v.paid) return invalid("반품 배송비와 공제 합계가 최초 결제액을 넘습니다. 별도 추가청구 방식인지 확인하세요."); const refund = v.paid - v.returnShipping - v.deduction; const newCost = v.replacement + v.delivery; return out("반품·재구매 추가 현금", newCost - refund, "원", [["기존 상품 예상 환급액", refund], ["새 주문 결제액", newCost], ["반품 후 최종 총지출", v.paid + newCost - refund]], "음수는 환급액이 새 결제액보다 큰 조건입니다. 환급 시점이 늦으면 새 결제액을 먼저 준비해야 할 수 있습니다."); },
    formula: "환급액 = 최초결제 − 반품배송 − 기타공제; 추가현금 = 새상품 + 새배송 − 환급액",
    questions: [["실제 환불 권리를 판단하나요?", "아닙니다. 판매자가 승인한 환불 조건을 입력하는 비용 계산입니다."], ["환불 전에 새 상품을 사면요?", "총차액과 별개로 새 결제액 전부를 먼저 준비할 수 있어야 합니다."], ["다른 카드로 결제하면요?", "현금 차이 원리는 같지만 카드별 취소·청구 시점은 별도 확인합니다."]],
    caveats: ["쿠폰 복원·적립금 회수·결제 취소 일정은 자동 반영하지 않습니다."], relatedSlugs: ["coupon-stack-savings", "free-shipping-threshold"],
  }),
  define({
    slug: "reusable-item-payback", title: "다회용품 비용 회수 이용횟수 계산기", category: "life",
    integerFields: ["uses"],
    description: "다회용품 초기 구입비와 매번 세척·소모품에 드는 비용을 일회용품 사용비와 비교합니다. 몇 번 사용해야 비용이 같아지는지와 예상 사용횟수에서의 총지출 차이를 확인할 수 있습니다.",
    guidance: "세척비는 물·전력·세제 등 사용자가 고려할 실제 비용을 합산합니다. 초기 구매금은 한 제품 가격으로 넣고 예상 횟수는 제품 수명 이내로 정하며, 환경영향이나 위생 수준을 금액으로 판정하는 도구는 아닙니다.",
    keywords: ["다회용품 손익분기", "일회용 비교", "재사용 비용"],
    fields: [money("purchase", "다회용품 구입비", 20000), money("wash", "1회 세척·소모품 비용", 100), money("disposable", "일회용 1회 비용", 500), number("uses", "예상 사용횟수", 100, "회", 1e9)],
    compute: v => { const saving = v.disposable - v.wash; const reusable = v.purchase + v.wash * v.uses; if (saving <= 0) return out("예상횟수 다회용 추가비용", reusable - v.disposable * v.uses, "원", [], "1회 반복비용이 일회용보다 낮지 않아 비용절감으로 초기 구매비를 회수할 수 없습니다."); return out("구입비 회수에 필요한 횟수", ceilUnits(v.purchase / saving), "회", [["예상횟수 절감액", v.disposable * v.uses - reusable], ["다회용 총지출", reusable], ["일회용 총지출", v.disposable * v.uses]]); },
    formula: "회수횟수 = 올림(구입비 ÷ (일회용 단가 − 반복비용)); 절감 = 일회용 단가 × 횟수 − 구입비 − 반복비용 × 횟수",
    questions: [["환경적으로 더 좋은지도 알려주나요?", "아닙니다. 입력한 금전 비용만 비교합니다."], ["세척비가 더 높으면요?", "반복 사용으로 비용을 절약하지 못하므로 회수횟수를 제시하지 않습니다."], ["제품을 여러 번 다시 사야 한다면요?", "제품 하나의 수명별로 나누어 계산하거나 구입비를 전체 교체비로 조정하세요."]],
    caveats: ["파손·분실·위생·환경영향은 별도 고려해야 합니다."], relatedSlugs: ["bulk-unit-price-waste", "appliance-energy-replacement"],
  }),
  define({
    slug: "diy-service-time-cost", title: "직접 작업·전문가 의뢰 비용 비교 계산기", category: "life",
    description: "직접 수리하거나 제작할 때 드는 재료·도구 비용과 자신의 시간을 전문가 의뢰 견적과 비교합니다. 실제 현금절약과 개인 시간가치를 반영한 절약액을 구분하여 작업 방식 선택을 돕습니다.",
    guidance: "도구는 이번 작업 때문에 새로 부담할 비용만 넣고 이미 가진 도구 가격은 중복하지 않습니다. 시간 가치는 개인 판단값이며, 전문 자격이나 안전이 필요한 작업을 비용만으로 직접 수행하라고 권하는 계산은 아닙니다.",
    keywords: ["DIY 비용", "외주 시간비용", "직접수리 비교"],
    fields: [money("materials", "직접 작업 재료비", 50000), money("tools", "새로 필요한 도구비", 30000), number("hours", "직접 작업 총시간", 5, "시간", 100000, "준비·구매·정리 시간을 포함한 예상시간입니다.", 0.1), unitMoney("value", "개인 시간 가치", 15000, "원/시간", "시간 1시간의 개인 평가액이며 실제 임금이 아닙니다."), money("quote", "전문가 의뢰 총견적", 200000)],
    compute: v => { const cash = v.materials + v.tools; const time = v.hours * v.value; return out("직접 작업 환산 절감액", v.quote - cash - time, "원", [["직접 작업 현금지출", cash], ["현금만 비교한 절감액", v.quote - cash], ["작업시간 평가액", time]]); },
    formula: "환산 절감 = 의뢰견적 − 재료비 − 도구비 − 작업시간 × 시간가치",
    questions: [["이미 가진 도구도 비용인가요?", "이번 의사결정의 추가 지출을 보려면 새로 필요한 도구비만 넣습니다."], ["직접 작업의 실패 가능성은요?", "재작업·실패비용을 자동 추정하지 않으므로 추가 비용으로 고려하세요."], ["시간 가치를 0으로 하면요?", "재료와 도구의 현금지출만 비교합니다."]],
    caveats: ["안전·자격·작업 보증이 필요한 업무는 전문 서비스 조건을 우선 확인하세요."], relatedSlugs: ["home-maintenance-reserve", "meeting-cost"],
  }),
  define({
    slug: "data-plan-overage", title: "데이터 초과요금·요금제 변경 비교 계산기", category: "life",
    description: "기본 제공량을 넘긴 데이터가 일정 단위로 추가 청구되는 요금제의 월 부담을 계산합니다. 필요한 사용량을 충분히 제공하는 대안 요금제와 비교하여 초과요금 때문에 늘어나는 지출을 확인합니다.",
    guidance: "통신사 실제 계약에서 초과량을 단위별로 올림 청구하는지 확인하고 해당 단위를 입력합니다. 속도제한 무제한 상품처럼 추가요금이 없는 상품에는 이 모델을 적용하지 않으며, 대안은 사용량을 모두 포함하는 가격이어야 합니다.",
    keywords: ["데이터 초과요금", "요금제 변경 비교", "추가 데이터 비용"],
    fields: [money("base", "현재 월 기본요금", 30000), number("included", "현재 제공량", 10, "GB", 1e6, "동일한 GB 단위로 사용량과 맞춥니다.", 0.1), number("usage", "예상 월 사용량", 13.2, "GB", 1e6, "실제 사용 기록을 참고한 예상량입니다.", 0.1), number("block", "추가 청구 단위", 1, "GB", 1e6, "이 단위마다 추가요금 한 번이 붙는다고 가정합니다.", 0.1), money("blockFee", "추가 단위당 요금", 5000), money("alternative", "사용량을 모두 포함한 대안 월요금", 45000)],
    compute: v => { if (!v.block) return invalid("추가 청구 단위를 0보다 크게 입력하세요."); const blocks = ceilUnits(positiveDifference(v.usage, v.included) / v.block); const extra = Math.max(0, blocks) * v.blockFee; return out("대안 요금제로 바꿀 때 절감", v.base + extra - v.alternative, "원", [["현재 예상 월 청구", v.base + extra], ["추가 데이터 요금", extra], ["추가 청구 단위 수", Math.max(0, blocks), "단위"]]); },
    formula: "추가단위 = 올림(max(사용량 − 제공량, 0) ÷ 단위량); 현재요금 = 기본료 + 추가단위 × 단가",
    questions: [["초과분이 조금이어도 단위 요금을 내나요?", "이 모델은 단위 올림 청구 계약을 가정합니다. 실제 계약 방식을 확인하세요."], ["무제한 속도제한 요금제에도 쓰나요?", "추가 청구가 없다면 추가 단가를 0으로 하거나 기본요금만 비교합니다."], ["약정 위약금은 포함되나요?", "월 반복비용만 비교하며 변경 위약금과 사은품 반환은 별도입니다."]],
    caveats: ["통화·문자·결합할인·테더링 한도 등 상품 차이는 자동 반영하지 않습니다."], relatedSlugs: ["subscription-monthly", "annual-plan-break-even"],
  }),
  define({
    slug: "cloud-storage-growth", title: "클라우드 저장량 증가·초과비용 계산기", category: "life",
    description: "현재 사용 중인 저장공간과 매달 늘어나는 파일 크기로 앞으로의 용량과 추가 저장비를 계산합니다. 기본 포함 용량을 넘긴 월말 저장량에만 단가를 적용해 프로젝트 기간의 초과비 예산을 확인합니다.",
    guidance: "월말 사용량 전체에서 기본 포함량을 뺀 만큼 매달 과금하는 가정입니다. 실제 서비스가 일평균 저장량이나 요금제 단계로 청구한다면 결과가 다르며, 전송량·요청수·백업 복제와 기존 기본요금은 별도 비용입니다.",
    keywords: ["클라우드 용량 예산", "저장공간 증가", "스토리지 초과비용"],
    fields: [number("used", "현재 저장량", 80, "GB", 1e9, "삭제 없이 계속 보관할 현재 파일 크기입니다.", 0.1), number("included", "기본 포함 용량", 100, "GB", 1e9, "요금에 포함된 저장량입니다.", 0.1), number("growth", "월 순증가량", 10, "GB/월", 1e9, "신규 생성량에서 삭제량을 뺀 증가량입니다.", 0.1), unitMoney("unit", "초과 GB당 월 단가", 100, "원/GB·월", "원/GB·월 기준 실제 계약 단가를 입력합니다."), number("months", "예산 기간", 6, "개월", 1200)],
    compute: v => {
      if (!Number.isInteger(v.months) || !v.months) return invalid("예산 기간은 1~1200 사이의 정수 개월로 입력하세요.");
      let total = 0;
      let first: number | null = positiveDifference(v.used, v.included) > 0 ? 0 : null;
      for (let month = 1; month <= v.months; month++) {
        const excess = positiveDifference(v.used + v.growth * month, v.included);
        total += excess * v.unit;
        if (excess > 0 && first === null) first = month;
      }
      return out("기간 누적 저장 초과비용", total, "원", [["마지막 달 예상 저장량", v.used + v.growth * v.months, "GB"], ["마지막 달 초과비용", positiveDifference(v.used + v.growth * v.months, v.included) * v.unit], ...(first !== null ? [["용량 초과 시작 시점", first, "개월 후"]] as Row[] : [])], first === 0 ? "현재 이미 기본 용량을 초과합니다. 비용 합계는 앞으로의 월말 과금만 포함합니다." : first === null ? "예산 기간에는 포함 용량을 초과하지 않습니다. 기본요금은 별도입니다." : "월말 저장량 과금 가정입니다. 포함 용량과 정확히 같으면 그 달은 초과비가 없습니다.");
    },
    formula: "m월 초과비 = max(현재GB + 순증가GB × m − 포함GB, 0) × 단가; 기간비용 = 각 월 초과비 합계",
    questions: [["용량과 정확히 같으면 과금되나요?", "초과분만 과금하는 가정이므로 포함량과 같으면 추가비가 없습니다."], ["삭제할 파일이 있다면요?", "월 순증가량에서 예상 삭제량을 차감하고 현재량도 정리 후 기준으로 맞춥니다."], ["전송요금도 들어가나요?", "아닙니다. 저장공간 초과비만 계산합니다."]],
    caveats: ["서비스별 과금 단위·무료한도·부가세·통화 변환은 직접 확인하세요."], relatedSlugs: ["data-plan-overage", "subscription-monthly"],
  }),
  define({
    slug: "exchange-spread-cost", title: "환전 우대율·수수료 비용 계산기", category: "currency",
    description: "매매기준율에 붙는 환전 스프레드와 우대율을 나누어 적용하여 외화를 살 때 필요한 원화를 계산합니다. 우대가 없는 조건과 비교해 절약되는 비용을 확인하며 별도 고정 수수료도 반영합니다.",
    guidance: "스프레드는 기준환율 대비 가산 비율이고 우대율은 그 가산 비용 중 면제되는 비율입니다. 이미 우대가 반영된 현찰 매도환율을 기준환율에 넣으면 수수료가 중복되므로 각 입력의 의미를 은행 안내에서 확인하세요.",
    keywords: ["환전 우대율", "환전 스프레드", "환전 수수료"],
    fields: [number("foreign", "구입할 외화", 1000, "외화 단위", 1e9, "USD·EUR 등 선택한 한 통화의 금액입니다.", 0.01), rate("baseRate", "외화 1단위 매매기준율", 1300), percent("spread", "기준율 대비 가산 스프레드", 2), percent("waiver", "스프레드 우대율", 90), money("fee", "별도 고정 수수료", 0)],
    compute: v => { if (!v.baseRate) return invalid("기준환율을 0보다 크게 입력하세요."); const base = v.foreign * v.baseRate; const full = base * v.spread / 100; const charged = full * (1 - v.waiver / 100); return out("외화 구입에 필요한 원화", base + charged + v.fee, "원", [["우대 후 스프레드 비용", charged], ["우대로 절약한 비용", full - charged], ["우대 적용환율", v.baseRate * (1 + v.spread / 100 * (1 - v.waiver / 100)), "원/외화"]]); },
    formula: "원화 = 외화 × 기준율 × [1 + 스프레드율 × (1 − 우대율)] + 고정료",
    questions: [["우대율 90%면 환율이 90% 할인되나요?", "환율 원금이 아니라 스프레드 비용의 90%를 면제하는 뜻입니다."], ["100엔 고시 환율은 어떻게 넣나요?", "100으로 나누어 1엔당 원화 환율로 맞춥니다."], ["실시간 환율인가요?", "환율을 자동 조회하지 않으며 사용자가 입력한 가정으로 계산합니다."]],
    caveats: ["외화 구입 방향의 단순 스프레드 모델이며 통화별 실제 고시 구조를 확인하세요."], relatedSlugs: ["currency-converter", "leftover-currency-roundtrip"],
  }),
  define({
    slug: "overseas-card-cost", title: "해외 카드 결제 수수료 계산기", category: "currency",
    description: "해외 현지통화 결제액에 직접 확인한 청구환율과 국제브랜드·카드사 수수료를 적용해 원화 부담을 계산합니다. 환율 환산 원금과 추가 수수료를 나누어 다른 결제수단 견적과 비교할 수 있습니다.",
    guidance: "두 비율 수수료가 같은 원화 환산원금을 기준으로 부과되는 단순 계약을 가정합니다. 실제 카드가 다른 기준이나 순서를 사용한다면 계산 결과가 달라지며, 현지에서 원화결제를 선택한 DCC 가격은 별도 결제금액으로 비교해야 합니다.",
    keywords: ["해외카드 수수료", "카드 원화청구", "국제브랜드 수수료"],
    fields: [number("foreign", "현지통화 결제액", 500, "외화 단위", 1e9, "해당 통화 1단위 환율과 맞춘 결제금액입니다.", 0.01), rate("exchange", "예상 청구환율", 1300), percent("network", "환산원금 기준 브랜드 수수료", 1), percent("issuer", "환산원금 기준 카드사 수수료", 0.2), money("fixed", "건당 고정 수수료", 0)],
    compute: v => { if (!v.exchange) return invalid("청구환율을 0보다 크게 입력하세요."); const principal = v.foreign * v.exchange; const network = principal * v.network / 100; const issuer = principal * v.issuer / 100; return out("예상 원화 청구액", principal + network + issuer + v.fixed, "원", [["환율 환산원금", principal], ["비율 수수료 합계", network + issuer], ["고정 수수료", v.fixed]]); },
    formula: "청구액 = 외화결제 × 환율 × (1 + 브랜드율 + 카드사율) + 고정료",
    questions: [["수수료율이 고정되어 있나요?", "기본값은 예시입니다. 카드 약관과 안내에 적힌 실제 비율을 입력합니다."], ["구매일 환율이 적용되나요?", "카드별 적용일이 다를 수 있으므로 예상 청구환율을 직접 확인하세요."], ["원화결제 DCC도 포함되나요?", "DCC 가산액은 자동 추정하지 않으므로 별도 제시가격과 비교해야 합니다."]],
    caveats: ["현금서비스·할부이자·환급·DCC 추가비용은 포함하지 않습니다."], relatedSlugs: ["exchange-spread-cost", "foreign-atm-cost"],
  }),
  define({
    slug: "remittance-received", title: "해외송금 예산별 실제 수취액 계산기", category: "currency",
    description: "원화 송금 예산에서 송금기관의 고정 수수료를 먼저 빼고 환전한 뒤 수취 측 공제액을 반영합니다. 수수료가 어느 통화로 차감되는지 구분하여 같은 원화 예산으로 도착할 외화를 비교합니다.",
    guidance: "보내는 쪽 비용은 원화, 받는 쪽 비용은 수취통화 단위로 입력합니다. 중개은행 공제액이 확정되지 않았다면 몇 가지 시나리오를 비교하고, 환율에 이미 포함된 비용을 별도 수수료에 다시 넣지 마세요.",
    keywords: ["해외송금 수취액", "송금 수수료", "해외송금 예산"], sources: [source.transfer],
    fields: [money("budget", "총 원화 지출 예산", 1310000), money("senderFee", "원화 송금 수수료", 10000), rate("exchange", "송금 적용환율", 1300), number("recipientFee", "수취·중개 측 외화 공제", 10, "외화 단위", 1e9, "받는 통화 기준 수수료 합계입니다.", 0.01)],
    compute: v => { if (!v.exchange || v.senderFee > v.budget) return invalid("환율은 0보다 크고 원화 수수료는 전체 예산 이하여야 합니다."); const sent = (v.budget - v.senderFee) / v.exchange; if (v.recipientFee > sent) return invalid("수취 측 수수료가 송금 외화보다 큽니다. 실제 최소 송금액과 수수료를 확인하세요."); return out("예상 외화 수취액", sent - v.recipientFee, "외화 단위", [["수취 공제 전 송금액", sent, "외화 단위"], ["수수료 원화 환산 합계", v.senderFee + v.recipientFee * v.exchange]]); },
    formula: "수취외화 = (원화예산 − 원화 송금료) ÷ 적용환율 − 수취통화 공제액",
    questions: [["환율은 어느 방향인가요?", "외화 1단위당 필요한 원화 금액을 입력합니다."], ["수수료는 모두 원화인가요?", "송금료는 원화, 수취·중개 수수료는 받는 통화로 구분합니다."], ["공제액을 모르면요?", "0으로 두면 미반영 결과이므로 송금기관에 확인하거나 여러 공제액을 비교하세요."]],
    caveats: ["출처는 환율·수수료 분리 원칙 참고용이며 국내 송금 법률 판단이 아닙니다."], relatedSlugs: ["exchange-spread-cost", "export-quote-break-even-rate"],
  }),
  define({
    slug: "leftover-currency-roundtrip", title: "여행 잔돈 재환전 손익 계산기", category: "currency",
    description: "여행 후 남은 외화를 다시 원화로 바꿀 때 받을 금액과 그 외화를 처음 구입한 비용을 비교합니다. 구입·재환전 환율 차이와 별도 수수료를 나누어 잔여 외화의 왕복 환전 손익을 확인합니다.",
    guidance: "처음 산 외화 중 현재 남은 수량에 대응하는 구입원가만 비교합니다. 이미 쓴 외화 비용은 제외하며 구입환율에 당시 비용이 포함되었다면 다시 수수료를 더하지 말고, 동전이나 소액권의 실제 환전 가능 여부도 확인하세요.",
    keywords: ["잔돈 재환전", "왕복 환전 손익", "외화 매도환율"],
    fields: [number("foreign", "남은 외화 수량", 300, "외화 단위", 1e9, "처음 구입한 외화 중 다시 팔 수량입니다.", 0.01), rate("buyRate", "처음 구입한 실제 환율", 1350), rate("sellRate", "지금 재환전 실제 환율", 1280), money("fee", "이번 재환전 고정 수수료", 1000)],
    compute: v => { if (!v.buyRate || !v.sellRate) return invalid("구입환율과 재환전환율을 0보다 크게 입력하세요."); const cost = v.foreign * v.buyRate; const cash = v.foreign * v.sellRate - v.fee; return out("남은 외화 재환전 손익", cash - cost, "원", [["현재 받을 원화 순액", cash], ["남은 외화 구입원가", cost]], cash < 0 ? "수수료가 재환전 대금보다 큽니다. 실제 최소금액과 거래 가능 여부를 확인하세요." : "음수는 구입원가보다 적게 돌려받는 금액입니다. 향후 환율 방향을 예측하지 않습니다."); },
    formula: "재환전 손익 = 남은외화 × (재환전율 − 구입율) − 이번 수수료",
    questions: [["여행 전체 환전비를 비교하나요?", "남은 외화 수량에 대응하는 구입원가만 비교합니다."], ["지금 바꿀지 기다릴지 추천하나요?", "현재 입력조건의 손익만 보여주며 미래 환율은 예측하지 않습니다."], ["수수료가 환율에 포함되면요?", "별도 고정 수수료에 중복으로 넣지 않습니다."]],
    caveats: ["현찰·외화계좌·동전은 취급환율과 환전 가능 조건이 다를 수 있습니다."], relatedSlugs: ["exchange-spread-cost", "currency-converter"],
  }),
  define({
    slug: "export-quote-break-even-rate", title: "수출 견적 손익분기 환율 계산기", category: "currency",
    description: "외화 견적대금에서 비율 수수료와 외화 고정 공제액을 빼고 국내 발생 원가를 충당할 환율을 역산합니다. 비교 환율에서 남는 원화 공헌이익을 함께 보며 수출 거래의 환율 민감도를 확인합니다.",
    guidance: "외화 견적은 계약 통화 한 종류로 통일하고 원화 원가는 해당 주문에 직접 발생하는 제작·운송 등 비용을 넣습니다. 견적대금이 실제 수취되는 시점이나 환헤지 계약을 자동 반영하지 않으며 세금과 고정비는 별도로 검토하세요.",
    keywords: ["수출 손익환율", "외화 견적", "손익분기 환율"],
    fields: [number("invoice", "외화 견적대금", 10000, "외화 단위", 1e9, "한 주문의 계약 통화 대금입니다.", 0.01), percent("feeRate", "견적대금 기준 수수료율", 2), number("fixedFee", "외화 고정 공제액", 100, "외화 단위", 1e9, "계약 통화로 공제되는 고정 수수료입니다.", 0.01), money("cost", "주문 관련 원화 원가", 11000000), rate("exchange", "비교 수취환율", 1300)],
    compute: v => { const net = v.invoice * (1 - v.feeRate / 100) - v.fixedFee; if (net <= 0 || !v.exchange) return invalid("수수료 차감 후 외화 수취액과 비교환율이 0보다 커야 손익환율을 계산할 수 있습니다."); return out("원가 충당 손익분기 환율", v.cost / net, "원/외화", [["수수료 후 수취외화", net, "외화 단위"], ["비교환율의 원화 공헌이익", net * v.exchange - v.cost]]); },
    formula: "손익분기환율 = 원화원가 ÷ [외화견적 × (1 − 수수료율) − 외화 고정료]",
    questions: [["원화 원가를 외화로 넣나요?", "아닙니다. 국내 원화 원가와 계약 외화대금을 별도로 입력합니다."], ["환율이 높아지면 어떻게 되나요?", "원화 기준 원가가 같다면 같은 수취외화의 원화 금액이 늘어납니다."], ["환헤지도 포함되나요?", "자동 계산하지 않습니다. 확정된 헤지환율이 있다면 비교환율로 넣을 수 있습니다."]],
    caveats: ["수출 세무·관세·부도위험·신용장 조건은 판정하지 않습니다."], relatedSlugs: ["remittance-received", "business-margin-quick"],
  }),
  define({
    slug: "foreign-atm-cost", title: "해외 ATM 인출 총비용 계산기", category: "currency",
    description: "해외 ATM에서 받을 현금과 현지 운영자 수수료를 환산하고 인출 비율 수수료·원화 고정료를 더합니다. 실제 손에 받는 외화 기준 체감 환율과 인출 건수에 따른 비용 차이를 확인합니다.",
    guidance: "현지 운영자 수수료는 인출액에 더해 환산되며 비율 수수료도 그 합계 원화에 적용되는 가정입니다. 실제 카드·은행 계약의 수수료 기준을 확인하고, 현금서비스 이자나 ATM의 원화환산 제안은 별도 조건으로 구분하세요.",
    keywords: ["해외ATM 수수료", "해외 현금 인출", "ATM 체감환율"],
    fields: [number("cash", "받을 외화 현금", 200, "외화 단위", 1e9, "실제로 인출하여 받는 현금 금액입니다.", 0.01), number("operator", "현지 ATM 운영자 수수료", 5, "외화 단위", 1e9, "인출액과 같은 현지통화로 부과되는 금액입니다.", 0.01), rate("exchange", "예상 인출 적용환율", 1300), percent("feeRate", "환산 합계 기준 비율 수수료", 1), money("fixed", "원화 건당 고정료", 3000)],
    compute: v => { if (!v.cash || !v.exchange) return invalid("인출할 외화와 환율은 0보다 커야 총비용과 체감환율을 계산할 수 있습니다."); const base = (v.cash + v.operator) * v.exchange; const total = base * (1 + v.feeRate / 100) + v.fixed; return out("1회 인출 원화 총부담", total, "원", [["수수료 원화 합계", total - v.cash * v.exchange], ["받는 현금 기준 체감환율", total / v.cash, "원/외화"]]); },
    formula: "총부담 = (받는현금 + 현지수수료) × 환율 × (1 + 비율수수료) + 원화고정료; 체감환율 = 총부담 ÷ 받는현금",
    questions: [["현금서비스 이자도 포함되나요?", "인출 수수료만 계산하며 신용공여 이자는 별도입니다."], ["소액을 여러 번 빼면요?", "건당 고정료가 반복되므로 각 인출 조건을 따로 계산해 합산합니다."], ["ATM 원화환산을 선택하면요?", "제시된 원화 총액과 별도 비교해야 하며 DCC 가산율은 자동 적용하지 않습니다."]],
    caveats: ["해외 인출 가능 여부·한도·제휴 우대는 카드와 은행 안내를 확인하세요."], relatedSlugs: ["overseas-card-cost", "exchange-spread-cost"],
  }),
];
